# -*- coding: utf-8 -*-
import json

c = []

# AFRICA 1-8
c.append(dict(code="ML",name="Mali",flag="\U0001F1F2\U0001F1F1",continent="Afrique",capital="Bamako",languages=["Fran\u00e7ais","Bambara"],currency=dict(code="XOF",symbol="CFA",name="Franc CFA (BCEAO)"),drivingSide="right",authority="Direction Nationale de l'Automobile",emergencyPhone="17 / 15",minAge=18,speedUrban=50,speedRural=80,speedHighway=100,bloodAlcohol=0.8,requiredDocuments=["Permis de conduire","Carte grise","Assurance","Contr\u00f4le technique"],requiredEquipment=["Triangle de signalisation","Gilet de s\u00e9curit\u00e9","Extincteur","Trousse de premiers secours"],specialFeatures=["Priorit\u00e9 \u00e0 droite","Circulation en convoi possible hors agglom\u00e9ration"],licenseCategories=["AM","A1","A2","A","B","BE","C1","C","CE","D1","D","DE"],commonInfractions=["Exc\u00e8s de vitesse","Non-port du gilet","Non-port du casque","D\u00e9passement dangereux"],sanctions=["Amende: 5 000 - 50 000 CFA","Retrait de points: 1-4 points","Suspension du permis","Emprisonnement possible"]))

c.append(dict(code="SN",name="S\u00e9n\u00e9gal",flag="\U0001F1F8\U0001F1F3",continent="Afrique",capital="Dakar",languages=["Fran\u00e7ais","Wolof"],currency=dict(code="XOF",symbol="CFA",name="Franc CFA (BCEAO)"),drivingSide="right",authority="Direction de la R\u00e9glementation et de la Circulation Routi\u00e8re",emergencyPhone="17 / 15",minAge=18,speedUrban=50,speedRural=90,speedHighway=110,bloodAlcohol=0.5,requiredDocuments=["Permis de conduire","Carte grise","Assurance","Visite technique"],requiredEquipment=["Triangle de signalisation","Gilet de s\u00e9curit\u00e9","Extincteur"],specialFeatures=["Priorit\u00e9 \u00e0 droite","Alcool\u00e9mie contr\u00f4l\u00e9e couramment"],licenseCategories=["AM","A1","A2","A","B","BE","C1","C","CE","D1","D","DE"],commonInfractions=["Exc\u00e8s de vitesse","Conduite en \u00e9tat d'ivresse","Non-port de la ceinture","T\u00e9l\u00e9phone au volant"],sanctions=["Amende: 10 000 - 100 000 CFA","Retrait de points","Suspension du permis: 1-3 mois","Emprisonnement en cas de r\u00e9cidive"]))

c.append(dict(code="CI",name="C\u00f4te d'Ivoire",flag="\U0001F1E8\U0001F1EE",continent="Afrique",capital="Yamoussoukro",languages=["Fran\u00e7ais"],currency=dict(code="XOF",symbol="CFA",name="Franc CFA (BCEAO)"),drivingSide="right",authority="Direction G\u00e9n\u00e9rale des Transports Terrestres",emergencyPhone="170 / 185",minAge=18,speedUrban=50,speedRural=80,speedHighway=110,bloodAlcohol=0.8,requiredDocuments=["Permis de conduire","Carte grise","Assurance","Visite technique"],requiredEquipment=["Triangle de signalisation","Gilet de s\u00e9curit\u00e9","Extincteur"],specialFeatures=["Priorit\u00e9 \u00e0 droite","Taxis-motos tr\u00e8s nombreux \u00e0 Abidjan"],licenseCategories=["AM","A1","A2","A","B","BE","C1","C","CE","D1","D","DE"],commonInfractions=["Exc\u00e8s de vitesse","Conduite sans permis","Non-port du casque (2 roues)","Non-respect des feux"],sanctions=["Amende: 5 000 - 300 000 CFA","Retrait de points","Suspension du permis","Emprisonnement possible"]))

c.append(dict(code="BF",name="Burkina Faso",flag="\U0001F1E7\U0001F1EB",continent="Afrique",capital="Ouagadougou",languages=["Fran\u00e7ais","Moore","Dioula"],currency=dict(code="XOF",symbol="CFA",name="Franc CFA (BCEAO)"),drivingSide="right",authority="Direction G\u00e9n\u00e9rale des Transports et de la S\u00e9curit\u00e9 Routi\u00e8re",emergencyPhone="17 / 15",minAge=18,speedUrban=50,speedRural=80,speedHighway=100,bloodAlcohol=0.8,requiredDocuments=["Permis de conduire","Carte grise","Assurance","Contr\u00f4le technique"],requiredEquipment=["Triangle de signalisation","Gilet de s\u00e9curit\u00e9","Extincteur"],specialFeatures=["Priorit\u00e9 \u00e0 droite","Nombreux v\u00e9hicules \u00e0 deux roues"],licenseCategories=["AM","A1","A2","A","B","BE","C1","C","CE","D1","D","DE"],commonInfractions=["Exc\u00e8s de vitesse","Conduite sans assurance","Non-port du casque","D\u00e9passement interdit"],sanctions=["Amende: 5 000 - 100 000 CFA","Suspension du permis","Immobilisation du v\u00e9hicule","Emprisonnement possible"]))

c.append(dict(code="NE",name="Niger",flag="\U0001F1F3\U0001F1EA",continent="Afrique",capital="Niamey",languages=["Fran\u00e7ais","Hausa","Zarma"],currency=dict(code="XOF",symbol="CFA",name="Franc CFA (BCEAO)"),drivingSide="right",authority="Direction des Transports Routiers",emergencyPhone="17 / 15",minAge=18,speedUrban=50,speedRural=80,speedHighway=100,bloodAlcohol=0.8,requiredDocuments=["Permis de conduire","Carte grise","Assurance","Visite technique"],requiredEquipment=["Triangle de signalisation","Gilet de s\u00e9curit\u00e9","Extincteur"],specialFeatures=["Priorit\u00e9 \u00e0 droite","Pistes sablonneuses fr\u00e9quentes"],licenseCategories=["AM","A1","A2","A","B","BE","C1","C","CE","D1","D","DE"],commonInfractions=["Exc\u00e8s de vitesse","Conduite sans permis","Non-port du casque","D\u00e9passement dangereux"],sanctions=["Amende: 5 000 - 50 000 CFA","Retrait de points","Suspension du permis","Emprisonnement en cas d'accident"]))

c.append(dict(code="GN",name="Guin\u00e9e",flag="\U0001F1EC\U0001F1F3",continent="Afrique",capital="Conakry",languages=["Fran\u00e7ais"],currency=dict(code="GNF",symbol="FG",name="Franc guin\u00e9en"),drivingSide="right",authority="Direction Nationale de la S\u00e9curit\u00e9 Routi\u00e8re",emergencyPhone="17 / 15",minAge=18,speedUrban=50,speedRural=80,speedHighway=100,bloodAlcohol=0.8,requiredDocuments=["Permis de conduire","Carte grise","Assurance"],requiredEquipment=["Triangle de signalisation","Gilet de s\u00e9curit\u00e9","Extincteur"],specialFeatures=["Priorit\u00e9 \u00e0 droite","\u00c9tat des routes variable"],licenseCategories=["A","B","C","D","E"],commonInfractions=["Exc\u00e8s de vitesse","Conduite en \u00e9tat d'ivresse","Non-port du casque","Non-respect du code de la route"],sanctions=["Amende: 50 000 - 500 000 GNF","Suspension du permis","Emprisonnement possible"]))

c.append(dict(code="CM",name="Cameroun",flag="\U0001F1E8\U0001F1F2",continent="Afrique",capital="Yaound\u00e9",languages=["Fran\u00e7ais","Anglais"],currency=dict(code="XAF",symbol="CFA",name="Franc CFA (BEAC)"),drivingSide="right",authority="Minist\u00e8re des Transports - Direction de la S\u00e9curit\u00e9 Routi\u00e8re",emergencyPhone="117 / 15",minAge=18,speedUrban=60,speedRural=90,speedHighway=110,bloodAlcohol=0.8,requiredDocuments=["Permis de conduire","Carte grise","Assurance","Visite technique","Contr\u00f4le technique"],requiredEquipment=["Triangle de signalisation","Gilet de s\u00e9curit\u00e9","Extincteur","Trousse de premiers secours"],specialFeatures=["Priorit\u00e9 \u00e0 droite","Gendarmes et police routi\u00e8re pr\u00e9sents","Bilinguisme officiel"],licenseCategories=["A","B","C","D","E","F"],commonInfractions=["Exc\u00e8s de vitesse","Conduite sans permis","T\u00e9l\u00e9phone au volant","D\u00e9passement dangereux"],sanctions=["Amende: 5 000 - 100 000 CFA","Retrait de permis","Prison ferme en cas d'homicide"]))

c.append(dict(code="TG",name="Togo",flag="\U0001F1F9\U0001F1EC",continent="Afrique",capital="Lom\u00e9",languages=["Fran\u00e7ais","\u00c9w\u00e9"],currency=dict(code="XOF",symbol="CFA",name="Franc CFA (BCEAO)"),drivingSide="right",authority="Direction G\u00e9n\u00e9rale des Transports Terrestres",emergencyPhone="117 / 15",minAge=18,speedUrban=50,speedRural=80,speedHighway=100,bloodAlcohol=0.8,requiredDocuments=["Permis de conduire","Carte grise","Assurance","Visite technique"],requiredEquipment=["Triangle de signalisation","Gilet de s\u00e9curit\u00e9"],specialFeatures=["Priorit\u00e9 \u00e0 droite","Zemidjans (motos-taxis) omnipr\u00e9sents"],licenseCategories=["A","B","C","D","E"],commonInfractions=["Exc\u00e8s de vitesse","Non-port du casque","Non-respect des feux","Conduite sans permis"],sanctions=["Amende: 2 000 - 50 000 CFA","Suspension du permis","Emprisonnement possible"]))

print(f'Part 1: {len(c)} countries')

# Store intermediate
with open('/tmp/seed_data.json', 'w', encoding='utf-8') as f:
    json.dump(c, f, ensure_ascii=False, indent=2)
print('Saved part 1')
