'use client';

import React, { useState, useEffect } from 'react';
import dynamic from 'next/dynamic';
import { motion } from 'framer-motion';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Skeleton } from '@/components/ui/skeleton';
import { Globe, Car, ShieldCheck, BookOpen, GraduationCap, Shield, Truck, Building2, ArrowRight } from 'lucide-react';
import { useViewStore, type AppModule, type LearningTab } from '@/stores/view-store';
import CountryExplorer from './CountryExplorer';
import CoursesView from './CoursesView';
import RoadSignsLibrary from './RoadSignsLibrary';
import SchoolProgram from './SchoolProgram';
import RegulationsView from './RegulationsView';

const LicenseBrowser = dynamic(() => import('./LicenseBrowser'), { ssr: false, loading: () => <TabLoader /> });
const ExamPlatform = dynamic(() => import('./ExamPlatform'), { ssr: false, loading: () => <TabLoader /> });
const PracticalExercises = dynamic(() => import('./PracticalExercises'), { ssr: false, loading: () => <TabLoader /> });
const ProgressDashboard = dynamic(() => import('./ProgressDashboard'), { ssr: false, loading: () => <TabLoader /> });

interface SeedCounts { countries: number; licenses: number; signs: number; questions: number; practical: number; }
function TabLoader() { return <div className="flex items-center justify-center py-16"><div className="text-center space-y-3"><div className="w-8 h-8 border-3 border-emerald-500 border-t-transparent rounded-full animate-spin mx-auto" /><p className="text-slate-500 text-sm">Chargement...</p></div></div>; }
function StatCard({ icon: Icon, label, value, delay }: { icon: React.ElementType; label: string; value: number; delay: number }) { return <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay }} className="bg-slate-900/80 border border-slate-800/60 rounded-xl p-4 flex items-center gap-3"><div className="w-10 h-10 rounded-lg bg-emerald-500/10 flex items-center justify-center shrink-0"><Icon className="w-5 h-5 text-emerald-500" /></div><div><p className="text-2xl font-bold text-white">{value}</p><p className="text-xs text-slate-400">{label}</p></div></div>; }

const OFFERS: { id: AppModule; icon: React.ElementType; title: string; description: string }[] = [
  { id: 'driving', icon: Car, title: 'Conducteur', description: 'Préparation au permis et accompagnement progressif vers une conduite responsable.' },
  { id: 'security', icon: Shield, title: 'Sécurité routière', description: 'Prévention, culture du risque et apprentissage des bons réflexes.' },
  { id: 'insurance', icon: ShieldCheck, title: 'Prévention & assurance', description: 'Programmes de prévention et partenariats autour de la sécurité.' },
  { id: 'fleet', icon: Truck, title: 'Conducteurs professionnels & flottes', description: 'Formation, prévention et pilotage des équipes de mobilité professionnelle.' },
  { id: 'enterprise', icon: Building2, title: 'Écoles, universités & entreprises', description: 'Déploiement de programmes ADSO à l’échelle d’un établissement ou d’une organisation.' },
];

export default function LearningPlatform() {
  const [counts, setCounts] = useState<SeedCounts | null>(null);
  const setView = useViewStore(s => s.setView);
  const learningTab = useViewStore(s => s.learningTab);
  const setLearningTab = useViewStore(s => s.setLearningTab);

  useEffect(() => { const controller = new AbortController(); (async () => { try { const res = await fetch('/api/seed', { signal: controller.signal, cache: 'no-store' }); if (res.ok) { const data = await res.json(); setCounts(data.counts); } } catch (error) { if (!(error instanceof DOMException && error.name === 'AbortError')) console.warn('[ADSO] learning stats unavailable'); } })(); return () => controller.abort(); }, []);

  return <div className="min-h-screen bg-slate-950 pb-10">
    <section className="relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-emerald-600/20 via-slate-950 to-emerald-900/10" /><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_rgba(16,185,129,0.15),transparent_60%)]" /><div className="relative max-w-6xl mx-auto px-4 pt-7 pb-4 sm:pt-9 sm:pb-6"><motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="text-center space-y-2.5"><h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight">Éducation routière <span className="bg-gradient-to-r from-emerald-400 to-emerald-600 bg-clip-text text-transparent">ADSO</span></h1><p className="text-slate-300 text-sm sm:text-base max-w-2xl mx-auto leading-relaxed">De l&apos;école au conducteur responsable : cours, images, signalisation, scènes immersives, exercices, certification et progression dans une même expérience.</p></motion.div><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.2 }} className="mt-5 grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 max-w-3xl mx-auto">{counts ? <><StatCard icon={Globe} label="Pays" value={counts.countries} delay={0.3} /><StatCard icon={Car} label="Permis" value={counts.licenses} delay={0.4} /><StatCard icon={ShieldCheck} label="Signalisation" value={counts.signs} delay={0.5} /><StatCard icon={BookOpen} label="Questions" value={counts.questions} delay={0.6} /></> : Array.from({ length: 4 }).map((_, i) => <div key={i} className="bg-slate-900/80 border border-slate-800/60 rounded-xl p-4"><Skeleton className="h-5 w-10 mb-1 bg-slate-800" /><Skeleton className="h-3 w-16 bg-slate-800" /></div>)}</motion.div></div></section>
    <section className="max-w-6xl mx-auto px-4"><Tabs value={learningTab} onValueChange={(value) => setLearningTab(value as LearningTab)} className="w-full"><div className="overflow-x-auto -mx-4 px-4 scrollbar-none"><TabsList className="bg-slate-900/80 border border-slate-800/60 rounded-xl h-auto p-1.5 gap-1 min-w-max"><TabsTrigger value="explorer" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white text-slate-400 rounded-lg px-3 py-2 text-sm">🌍 Explorer</TabsTrigger><TabsTrigger value="cours" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white text-slate-400 rounded-lg px-3 py-2 text-sm">📚 Cours</TabsTrigger><TabsTrigger value="programme" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white text-slate-400 rounded-lg px-3 py-2 text-sm">🎓 Écoles & Universités</TabsTrigger><TabsTrigger value="signalisation" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white text-slate-400 rounded-lg px-3 py-2 text-sm">🚦 Signalisation</TabsTrigger><TabsTrigger value="reglementations" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white text-slate-400 rounded-lg px-3 py-2 text-sm">⚖️ Réglementations</TabsTrigger><TabsTrigger value="permis" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white text-slate-400 rounded-lg px-3 py-2 text-sm">🪪 Permis</TabsTrigger><TabsTrigger value="examens" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white text-slate-400 rounded-lg px-3 py-2 text-sm">📝 Examens</TabsTrigger><TabsTrigger value="exercices" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white text-slate-400 rounded-lg px-3 py-2 text-sm">🎬 Scènes & exercices</TabsTrigger><TabsTrigger value="progression" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white text-slate-400 rounded-lg px-3 py-2 text-sm">📊 Progression</TabsTrigger></TabsList></div><TabsContent value="explorer"><CountryExplorer /></TabsContent><TabsContent value="cours"><CoursesView /></TabsContent><TabsContent value="programme"><SchoolProgram /></TabsContent><TabsContent value="signalisation"><RoadSignsLibrary /></TabsContent><TabsContent value="reglementations"><RegulationsView /></TabsContent><TabsContent value="permis"><LicenseBrowser /></TabsContent><TabsContent value="examens"><ExamPlatform /></TabsContent><TabsContent value="exercices"><PracticalExercises /></TabsContent><TabsContent value="progression"><ProgressDashboard /></TabsContent></Tabs></section>
    <section className="max-w-6xl mx-auto px-4 mt-8"><div className="flex items-end justify-between gap-4 mb-4"><div><p className="text-emerald-400 text-xs font-semibold uppercase tracking-[0.18em]">ADSO — parcours de vie</p><h2 className="text-white text-2xl font-bold mt-1">Apprendre tôt. Prévenir mieux. Devenir responsable.</h2><p className="text-slate-400 text-sm mt-1">La Formation reste le cœur ; les autres offres prolongent le parcours vers le conducteur responsable, le professionnel et l’établissement.</p></div><GraduationCap className="hidden sm:block w-8 h-8 text-emerald-400" /></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{OFFERS.map(({ id, icon: Icon, title, description }) => <button key={id} onClick={() => setView(id)} className="group text-left rounded-xl border border-slate-800 bg-slate-900/70 p-4 hover:border-emerald-700/60 hover:bg-slate-900 transition-colors"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-emerald-500/10 flex items-center justify-center"><Icon className="w-4 h-4 text-emerald-400" /></div><h3 className="text-white font-semibold text-sm">{title}</h3><ArrowRight className="w-4 h-4 text-slate-600 ml-auto group-hover:text-emerald-400" /></div><p className="text-slate-400 text-xs leading-relaxed mt-3">{description}</p></button>)}</div></section>
  </div>;
}