'use client';

import React, { useCallback, useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { ChevronDown, ChevronUp, ExternalLink, Target, ClipboardList, Shield, Leaf, ImageOff } from 'lucide-react';

interface Exercise { id: string; title: string; description: string; category: string; difficulty: string; objectives: string[]; steps: string[]; criteria: string[]; tips: string[]; scoring: Record<string, string | number>; countryCode: string; licenseCode: string; }
const CATEGORIES: Record<string, string> = { city: 'Ville', highway: 'Autoroute', rural: 'Campagne', mountain: 'Montagne', night: 'Nuit', rain: 'Pluie', fog: 'Brouillard', snow: 'Neige', parking: 'Stationnement', maneuver: 'Manœuvres', intersection: 'Intersection', priority: 'Priorité', roundabout: 'Rond-point', overtaking: 'Dépassement', emergency_braking: "Freinage d'urgence", eco_driving: 'Éco-conduite' };
const DIFFICULTIES: Record<string, string> = { beginner: 'Débutant', intermediate: 'Intermédiaire', advanced: 'Avancé' };

const VISUALS: Record<string, { image: string; source: string; alt: string }> = {
  city: { image: 'https://static.independent.co.uk/2026/01/05/04/Zimbabwe_Road_Safety_28808.jpg?fit=crop&height=1200&width=1200', source: 'The Independent — Zimbabwe urban traffic reference', alt: 'Circulation urbaine africaine avec piétons, voitures et motos' },
  highway: { image: 'https://images.unsplash.com/photo-1561089095-5b672d1587f0?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=85&w=2200', source: 'Unsplash — African interurban road reference', alt: 'Route interurbaine africaine asphaltée' },
  rural: { image: 'https://images.unsplash.com/photo-1561089095-5b672d1587f0?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=85&w=2200', source: 'Unsplash — African rural road reference', alt: 'Route rurale africaine asphaltée' },
  mountain: { image: 'https://3.bp.blogspot.com/-_BhAGcezQMA/UAgO7jlGc6I/AAAAAAAAAPo/Kv8jNcKvp1Q/s1600/IMG_0998a.jpg', source: 'Lesotho mountain-road photographic reference', alt: 'Route de montagne enneigée en Afrique australe' },
  night: { image: 'https://robofinity.com/cdn/shop/articles/1031_1.png?v=1761881976&width=2048', source: 'Night/rain road-safety photographic reference', alt: 'Conduite nocturne avec pluie, phares et chaussée mouillée' },
  rain: { image: 'https://robofinity.com/cdn/shop/articles/1031_1.png?v=1761881976&width=2048', source: 'Rain road-safety photographic reference', alt: 'Conduite sous forte pluie' },
  fog: { image: 'https://images.unsplash.com/photo-1523612289255-d0b991b941b6?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=85&w=2200', source: 'Unsplash — South Africa fog road', alt: 'Route africaine dans le brouillard' },
  snow: { image: 'https://3.bp.blogspot.com/-_BhAGcezQMA/UAgO7jlGc6I/AAAAAAAAAPo/Kv8jNcKvp1Q/s1600/IMG_0998a.jpg', source: 'Lesotho mountain-road photographic reference', alt: 'Route enneigée du Lesotho' },
  parking: { image: 'https://www.robertharding.com/watermark.php?im=RM%2FRH%2FHORIZONTAL%2F971-30&type=preview', source: 'Robert Harding — Luanda street/parking reference', alt: 'Stationnement et circulation urbaine à Luanda' },
  maneuver: { image: 'https://static.independent.co.uk/2026/01/05/04/Zimbabwe_Road_Safety_28808.jpg?fit=crop&height=1200&width=1200', source: 'The Independent — urban manoeuvre reference', alt: 'Manœuvres dans une circulation urbaine africaine dense' },
  intersection: { image: 'https://static.globalissues.org/ips/2023/04/unroadsafetyfund1-629x451.jpg', source: 'Global Issues / UN Road Safety Fund — Lusaka reference', alt: 'Intersection urbaine africaine à forte circulation' },
  priority: { image: 'https://static.globalissues.org/ips/2023/04/unroadsafetyfund1-629x451.jpg', source: 'Global Issues / UN Road Safety Fund — Lusaka reference', alt: 'Gestion des priorités dans un carrefour africain' },
  roundabout: { image: 'https://static.globalissues.org/ips/2023/04/unroadsafetyfund1-629x451.jpg', source: 'Global Issues / UN Road Safety Fund — Lusaka roundabout', alt: 'Rond-point très fréquenté à Lusaka' },
  overtaking: { image: 'https://www.arrivealive.co.za/ckfinder/userfiles/images/Army%20unsafe%20overtaking.jpg', source: 'Arrive Alive — overtaking safety reference', alt: 'Situation de dépassement sur route interurbaine' },
  emergency_braking: { image: 'https://images.pistonheads.com/nimg/37987/ab1.jpg', source: 'PistonHeads — emergency braking reference', alt: 'Freinage d’urgence vu depuis le poste de conduite' },
  eco_driving: { image: 'https://images.unsplash.com/photo-1561089095-5b672d1587f0?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=85&w=2200', source: 'Unsplash — steady African road-driving reference', alt: 'Conduite régulière et anticipée sur route africaine' },
};

const FALLBACK_TITLES: Record<string, string> = { city: 'Circulation urbaine et usagers vulnérables', highway: 'Conduite sur grand axe interurbain', rural: 'Route rurale et partage de la chaussée', mountain: 'Conduite en relief et virages', night: 'Conduite de nuit et visibilité', rain: 'Chaussée mouillée et adhérence', fog: 'Visibilité réduite par brouillard', snow: 'Conduite sur chaussée enneigée', parking: 'Stationnement en environnement dense', maneuver: 'Manœuvres et contrôle du véhicule', intersection: 'Lecture et franchissement d’une intersection', priority: 'Analyse d’une situation de priorité', roundabout: 'Approche et circulation dans un rond-point', overtaking: 'Dépassement et observation', emergency_braking: 'Freinage d’urgence et évitement', eco_driving: 'Anticipation et éco-conduite' };

function buildFallback(category: string, difficulty: string): Exercise {
  const level = DIFFICULTIES[difficulty]; const label = CATEGORIES[category];
  return { id: `visual-${category}-${difficulty}`, title: `${FALLBACK_TITLES[category] || label} — ${level}`, description: `Situation pédagogique ${level.toLowerCase()} : observer l’environnement, identifier les risques et choisir une conduite sûre. Cette scène constitue un socle de mobilité et ne prétend pas décrire une loi nationale.`, category, difficulty, objectives: ['Observer la scène avant d’agir', 'Identifier les usagers, obstacles et conditions de visibilité', 'Choisir une marge de sécurité adaptée'], steps: ['Balayer visuellement la chaussée et ses abords', 'Anticiper les trajectoires et les changements de situation', 'Adapter allure, distance et positionnement', 'Contrôler avant toute manœuvre'], criteria: ['Observation complète', 'Anticipation', 'Maîtrise du véhicule', 'Protection des usagers vulnérables'], tips: ['Ne jamais accélérer pour compenser une visibilité insuffisante', 'Privilégier l’anticipation et une marge de sécurité', 'Les règles nationales particulières sont à vérifier dans le module pays'], scoring: { observation: 25, anticipation: 25, sécurité: 30, maîtrise: 20 }, countryCode: 'COMMON', licenseCode: 'COMMON' };
}

export default function PracticalExercises() {
  const [items, setItems] = useState<Exercise[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [category, setCategory] = useState<string | null>(null); const [difficulty, setDifficulty] = useState<string | null>(null); const [expanded, setExpanded] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const p = new URLSearchParams(); if (category) p.set('category', category); if (difficulty) p.set('difficulty', difficulty); const r = await fetch(`/api/learning/practical${p.toString() ? `?${p}` : ''}`, { cache: 'no-store' }); if (!r.ok) throw new Error(`practical request failed: ${r.status}`); const data = await r.json(); const apiItems: Exercise[] = Array.isArray(data.exercises) ? data.exercises : []; const categories = category ? [category] : Object.keys(CATEGORIES); const difficulties = difficulty ? [difficulty] : Object.keys(DIFFICULTIES); const existing = new Set(apiItems.map(x => `${x.category}:${x.difficulty}`)); const fallback = categories.flatMap(c => difficulties.filter(d => !existing.has(`${c}:${d}`)).map(d => buildFallback(c, d))); const merged = [...apiItems, ...fallback]; setItems(merged); setTotal(merged.length); } catch (error) { console.error('[ADSO] immersive exercises unavailable', error); const categories = category ? [category] : Object.keys(CATEGORIES); const difficulties = difficulty ? [difficulty] : Object.keys(DIFFICULTIES); const fallback = categories.flatMap(c => difficulties.map(d => buildFallback(c, d))); setItems(fallback); setTotal(fallback.length); } finally { setLoading(false); } }, [category, difficulty]);
  useEffect(() => { load(); }, [load]);
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="space-y-5"><div className="rounded-xl border border-emerald-900/50 bg-emerald-950/20 p-4"><p className="text-emerald-300 text-sm font-semibold">Couverture immersive complète</p><p className="text-slate-400 text-xs mt-1">ADSO couvre 16 réalités routières, chacune déclinée en Débutant, Intermédiaire et Avancé. Les photos illustrent l’environnement ; elles ne remplacent pas la règle nationale applicable.</p></div><div className="flex flex-wrap gap-2">{Object.entries(CATEGORIES).map(([k, v]) => <button key={k} onClick={() => setCategory(category === k ? null : k)} className={`px-3 py-1.5 rounded-lg text-xs ${category === k ? 'bg-emerald-600 text-white' : 'bg-slate-900 border border-slate-800 text-slate-400'}`}>{v}</button>)}<button onClick={() => setCategory(null)} className={`px-3 py-1.5 rounded-lg text-xs ${category === null ? 'bg-emerald-600 text-white' : 'bg-slate-900 border border-slate-800 text-slate-400'}`}>Toutes</button></div><div className="flex flex-wrap gap-2"><button onClick={() => setDifficulty(null)} className={`px-3 py-1.5 rounded-lg text-xs ${difficulty === null ? 'bg-emerald-600 text-white' : 'bg-slate-900 border border-slate-800 text-slate-400'}`}>Toutes difficultés</button>{Object.entries(DIFFICULTIES).map(([k, v]) => <button key={k} onClick={() => setDifficulty(difficulty === k ? null : k)} className={`px-3 py-1.5 rounded-lg text-xs ${difficulty === k ? 'bg-emerald-600 text-white' : 'bg-slate-900 border border-slate-800 text-slate-400'}`}>{v}</button>)}</div>{!loading && <p className="text-xs text-slate-500">{total} scénario{total !== 1 ? 's' : ''} disponible{total !== 1 ? 's' : ''} dans ADSO.</p>}{loading && <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="rounded-xl bg-slate-900 border border-slate-800 p-4 space-y-3"><Skeleton className="h-36 bg-slate-800" /><Skeleton className="h-5 w-40 bg-slate-800" /><Skeleton className="h-3 w-full bg-slate-800" /></div>)}</div>}{!loading && <ScrollArea className="h-[760px]"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 pr-3">{items.map(x => <ExerciseCard key={x.id} item={x} open={expanded === x.id} onToggle={() => setExpanded(expanded === x.id ? null : x.id)} />)}</div></ScrollArea>}</motion.div>;
}

function ImmersiveVisual({ item, visual }: { item: Exercise; visual?: { image: string; source: string; alt: string } }) {
  const [failed, setFailed] = useState(false);
  if (!visual || failed) return <div className="relative h-48 bg-gradient-to-br from-emerald-950 via-slate-800 to-slate-950 flex items-center justify-center overflow-hidden"><div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_center,rgba(16,185,129,0.55),transparent_60%)]" /><div className="relative text-center px-6"><div className="text-4xl mb-2">🚗</div><p className="text-white font-semibold text-sm">Situation immersive</p><p className="text-slate-300 text-xs mt-1 line-clamp-2">{item.title}</p><div className="flex items-center justify-center gap-1.5 mt-2 text-[10px] text-slate-400"><ImageOff className="w-3 h-3" />Illustration indisponible — scénario conservé</div></div></div>;
  return <div className="relative h-48 bg-slate-800 overflow-hidden"><img src={visual.image} alt={visual.alt} loading="eager" decoding="async" referrerPolicy="no-referrer" className="h-full w-full object-cover" onError={() => setFailed(true)} /><div className="absolute bottom-0 inset-x-0 bg-black/75 px-2 py-1.5 flex justify-between gap-2"><span className="text-[9px] text-white truncate">Illustration réelle · {visual.source}</span><a href={visual.image} target="_blank" rel="noreferrer" aria-label="Voir la source de l'image" className="text-emerald-300"><ExternalLink className="w-3 h-3" /></a></div></div>;
}

function ExerciseCard({ item, open, onToggle }: { item: Exercise; open: boolean; onToggle: () => void }) { const visual = VISUALS[item.category]; return <Card className="bg-slate-900/90 border-slate-800 rounded-xl overflow-hidden"><ImmersiveVisual item={item} visual={visual} /><button onClick={onToggle} className="w-full text-left p-4 focus-visible:ring-2 focus-visible:ring-emerald-500" aria-expanded={open}><div className="flex justify-between gap-2"><h3 className="text-white font-semibold text-sm">{item.title}</h3>{open ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}</div><p className="text-slate-400 text-xs mt-1.5 line-clamp-3">{item.description}</p><div className="flex gap-2 mt-3"><Badge variant="outline" className="text-emerald-400 border-emerald-700/40">{CATEGORIES[item.category] || item.category}</Badge><Badge variant="outline" className="text-slate-300">{DIFFICULTIES[item.difficulty] || item.difficulty}</Badge></div></button><AnimatePresence>{open && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} className="overflow-hidden"><Separator className="bg-slate-800" /><div className="p-4 space-y-4"><List title="Objectifs" icon={Target} items={item.objectives} /><List title="Étapes" icon={ClipboardList} items={item.steps} numbered /><List title="Critères d'évaluation" icon={Shield} items={item.criteria} /><List title="Conseils" icon={Leaf} items={item.tips} />{Object.keys(item.scoring || {}).length > 0 && <div><p className="text-slate-500 text-[10px] uppercase tracking-wider">Barème</p><div className="grid grid-cols-2 gap-1 mt-1">{Object.entries(item.scoring).map(([k, v]) => <div key={k} className="bg-slate-800/50 rounded px-2 py-1 text-xs flex justify-between"><span className="text-slate-300">{k}</span><b className="text-emerald-400">{v}</b></div>)}</div></div>}</div></motion.div>}</AnimatePresence></Card>; }
function List({ title, icon: Icon, items, numbered = false }: { title: string; icon: React.ElementType; items: string[]; numbered?: boolean }) { if (!items?.length) return null; return <div><p className="text-slate-500 text-[10px] uppercase tracking-wider flex items-center gap-1.5"><Icon className="w-3 h-3 text-emerald-400" />{title}</p><ul className="mt-1.5 space-y-1">{items.map((x, i) => <li key={`${i}-${x}`} className="text-slate-200 text-xs leading-relaxed flex gap-2"><span className="text-emerald-400 shrink-0">{numbered ? `${i + 1}.` : '•'}</span>{x}</li>)}</ul></div>; }
