export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: string;
}

export const quizQuestions: QuizQuestion[] = [
  // ═══════════════════════════════════════════════════════════════════
  // EASY (q-1 to q-100)
  // ═══════════════════════════════════════════════════════════════════

  // --- Signalisation ---
  { id: 'q-1', question: 'Que signifie un panneau de signalisation rouge avec un cercle blanc et une barre rouge diagonale ?', options: ['Interdiction', 'Obligation', 'Fin d\'interdiction', 'Danger'], correctIndex: 0, explanation: 'Un panneau rond avec une barre rouge diagonale indique une interdiction (ex. : sens interdit).', difficulty: 'easy', category: 'signalisation' },
  { id: 'q-2', question: 'Un panneau triangulaire avec fond rouge et bordure blanche indique :', options: ['Une interdiction', 'Un danger', 'Une obligation', 'Une direction'], correctIndex: 1, explanation: 'Les panneaux triangulaires à fond rouge signalent un danger ou un avertissement.', difficulty: 'easy', category: 'signalisation' },
  { id: 'q-3', question: 'Un panneau carré bleu avec un cercle blanc indique :', options: ['Un danger', 'Une interdiction', 'Une obligation', 'Une information'], correctIndex: 2, explanation: 'Les panneaux carrés bleus avec cercle blanc imposent une obligation (ex. : tourner à droite).', difficulty: 'easy', category: 'signalisation' },
  { id: 'q-4', question: 'La couleur bleue sur un panneau rectangulaire indique :', options: ['Une interdiction', 'Une information ou obligation', 'Un danger', 'Une recommandation'], correctIndex: 1, explanation: 'Les rectangles bleus donnent des informations ou imposent des obligations spécifiques.', difficulty: 'easy', category: 'signalisation' },
  { id: 'q-5', question: 'Un panneau STOP impose de :', options: ['Ralentir', 'S\'arrêter complètement', 'Céder le passage', 'Klaxonner'], correctIndex: 1, explanation: 'Le panneau STOP impose un arrêt complet avant de s\'engager. Il faut marquer un temps d\'arrêt.', difficulty: 'easy', category: 'panneaux' },
  { id: 'q-6', question: 'Que signifie un panneau rond avec une ligne rouge horizontale ?', options: ['Fin d\'interdiction', 'Interdiction de dépasser', 'Sens interdit', 'Limite de vitesse'], correctIndex: 3, explanation: 'Un panneau rond avec une ligne rouge horizontale indique une limite de vitesse maximale.', difficulty: 'easy', category: 'signalisation' },
  { id: 'q-7', question: 'Un panneau vert avec un rectangle blanc indique :', options: ['Une autoroute', 'Un lieu-dit', 'Une direction obligatoire', 'Une piste cyclable'], correctIndex: 2, explanation: 'Les panneaux verts avec rectangle blanc indiquent une direction que le conducteur doit suivre.', difficulty: 'easy', category: 'signalisation' },
  { id: 'q-8', question: 'Le feu orange fixe signifie :', options: ['Passer avec prudence', 'S\'arrêter si possible', 'L\'urgence', 'Ralentir'], correctIndex: 1, explanation: 'Le feu orange fixe signifie que le conducteur doit s\'arrêter sauf si son véhicule est trop près pour le faire en sécurité.', difficulty: 'easy', category: 'feux' },

  // --- Vitesse ---
  { id: 'q-9', question: 'En agglomération, la vitesse maximale autorisée est généralement de :', options: ['30 km/h', '50 km/h', '70 km/h', '80 km/h'], correctIndex: 1, explanation: 'En agglomération, la vitesse est limitée à 50 km/h sauf indication contraire.', difficulty: 'easy', category: 'vitesse' },
  { id: 'q-10', question: 'Sur autoroute, la vitesse maximale pour les voitures est de :', options: ['100 km/h', '110 km/h', '130 km/h', '140 km/h'], correctIndex: 2, explanation: 'Sur autoroute, la vitesse maximale est de 130 km/h pour les voitures par temps sec.', difficulty: 'easy', category: 'vitesse' },
  { id: 'q-11', question: 'Par temps de pluie, la vitesse sur autoroute est limitée à :', options: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'], correctIndex: 2, explanation: 'Par temps de pluie ou autres précipitations, la vitesse sur autoroute est réduite à 110 km/h.', difficulty: 'easy', category: 'pluie' },
  { id: 'q-12', question: 'Pour les jeunes conducteurs (permis probatoire), la vitesse sur route est limitée à :', options: ['80 km/h', '90 km/h', '100 km/h', '110 km/h'], correctIndex: 0, explanation: 'Les jeunes conducteurs en permis probatoire sont limités à 80 km/h sur route au lieu de 90 km/h.', difficulty: 'easy', category: 'vitesse' },
  { id: 'q-13', question: 'Dans une zone 30, la vitesse maximale est de :', options: ['20 km/h', '30 km/h', '40 km/h', '50 km/h'], correctIndex: 1, explanation: 'Une zone 30 limite la vitesse à 30 km/h pour tous les véhicules.', difficulty: 'easy', category: 'vitesse' },
  { id: 'q-14', question: 'La vitesse en zone de rencontre est limitée à :', options: ['10 km/h', '20 km/h', '30 km/h', '40 km/h'], correctIndex: 1, explanation: 'En zone de rencontre, la vitesse est limitée à 20 km/h et les piétons ont la priorité.', difficulty: 'easy', category: 'vitesse' },

  // --- Documents ---
  { id: 'q-15', question: 'Quels documents devez-vous avoir lors de la conduite ?', options: ['Permis et carte grise uniquement', 'Permis, carte grise et assurance', 'Permis, carte grise, assurance et contrôle technique', 'Tous les documents du véhicule'], correctIndex: 2, explanation: 'Le conducteur doit avoir son permis, la carte grise, l\'attestation d\'assurance et le contrôle technique (si applicable).', difficulty: 'easy', category: 'documents' },
  { id: 'q-16', question: 'Le permis de conduire doit être présenté lors d\'un contrôle par les forces de l\'ordre :', options: ['Uniquement en cas d\'infraction', 'Uniquement sur autoroute', 'Toujours', 'Uniquement la nuit'], correctIndex: 2, explanation: 'Le permis de conduire doit toujours être présenté lors d\'un contrôle, quelle que soit la circonstance.', difficulty: 'easy', category: 'documents' },
  { id: 'q-17', question: 'À quelle fréquence le contrôle technique est-il obligatoire ?', options: ['Tous les ans', 'Tous les 2 ans', 'Tous les 4 ans', 'Tous les 5 ans'], correctIndex: 1, explanation: 'Le contrôle technique est obligatoire tous les 2 ans pour les véhicules de tourisme de plus de 4 ans.', difficulty: 'easy', category: 'documents' },

  // --- Priorité ---
  { id: 'q-18', question: 'Quand deux véhicules arrivent en même temps à une intersection sans signalisation, qui a la priorité ?', options: ['Le véhicule venant de la droite', 'Le véhicule le plus gros', 'Le véhicule le plus rapide', 'Le véhicule qui klaxonne'], correctIndex: 0, explanation: 'En l\'absence de signalisation, la priorité à droite s\'applique : le véhicule venant de la droite est prioritaire.', difficulty: 'easy', category: 'priorité' },
  { id: 'q-19', question: 'Un panneau « Cédez le passage » (triangle pointe en bas) signifie :', options: ['S\'arrêter obligatoirement', 'Laisser passer les véhicules de la droite', 'Ralentir sans s\'arrêter', 'Laisser passer les véhicules sur la route prioritaire'], correctIndex: 3, explanation: 'Le cédez le passage impose de laisser passer les véhicules circulant sur la route prioritaire.', difficulty: 'easy', category: 'priorité' },
  { id: 'q-20', question: 'À l\'approche d\'un passage piéton, vous devez :', options: ['Klaxonner pour prévenir', 'Ralentir et vous arrêter si un piéton s\'engage', 'Accélérer pour passer rapidement', 'Ne rien changer'], correctIndex: 1, explanation: 'Le conducteur doit ralentir à l\'approche d\'un passage piéton et s\'arrêter si un piéton s\'apprête à traverser.', difficulty: 'easy', category: 'piéton' },
  { id: 'q-21', question: 'Un bus avec clignotants allumés s\'apprête à repartir d\'un arrêt, vous devez :', options: ['Accélérer pour passer avant', 'Ralentir et le laisser repartir', 'Klaxonner', 'Ne rien changer'], correctIndex: 1, explanation: 'Lorsqu\'un bus clignote, le conducteur doit ralentir et le laisser repartir en priorité.', difficulty: 'easy', category: 'priorité' },

  // --- Véhicule ---
  { id: 'q-22', question: 'Les feux de croisement doivent être allumés :', options: ['Uniquement la nuit', 'De nuit et par visibilité réduite', 'En permanence', 'Uniquement sous tunnel'], correctIndex: 1, explanation: 'Les feux de croisement sont obligatoires la nuit et en cas de visibilité réduite (brouillard, pluie, neige).', difficulty: 'easy', category: 'nuit' },
  { id: 'q-23', question: 'Les clignotants doivent être utilisés :', options: ['Uniquement pour tourner', 'Pour tout changement de direction', 'Uniquement sur autoroute', 'Uniquement en agglomération'], correctIndex: 1, explanation: 'Les clignotants doivent être activés pour tout changement de direction : tourner, dépasser, s\'insérer.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-24', question: 'Le port de la ceinture de sécurité est obligatoire :', options: ['Uniquement en ville', 'En ville et sur route', 'Pour le conducteur uniquement', 'Pour tous les occupants en toutes circonstances'], correctIndex: 3, explanation: 'La ceinture est obligatoire pour TOUS les occupants du véhicule, en ville comme sur route, à l\'avant comme à l\'arrière.', difficulty: 'easy', category: 'véhicule' },

  // --- Alcool ---
  { id: 'q-25', question: 'Le taux d\'alcoolémie maximal autorisé pour un conducteur est de :', options: ['0,2 g/L', '0,5 g/L', '0,8 g/L', '1,0 g/L'], correctIndex: 1, explanation: 'Le taux maximum autorisé est de 0,5 g/L de sang (0,25 mg/L d\'air expiré) pour les conducteurs ordinaires.', difficulty: 'easy', category: 'alcool' },
  { id: 'q-26', question: 'Pour les jeunes conducteurs, le taux d\'alcoolémie autorisé est de :', options: ['0,0 g/L', '0,2 g/L', '0,5 g/L', '0,8 g/L'], correctIndex: 0, explanation: 'Zéro alcool pour les jeunes conducteurs en permis probatoire et les conducteurs professionnels.', difficulty: 'easy', category: 'alcool' },

  // --- Stationnement ---
  { id: 'q-27', question: 'Vous pouvez stationner à moins de 5 mètres d\'un passage piéton :', options: ['Vrai', 'Faux'], correctIndex: 1, explanation: 'Il est interdit de stationner à moins de 5 mètres d\'un passage piéton pour ne pas masquer la vue.', difficulty: 'easy', category: 'stationnement' },
  { id: 'q-28', question: 'Le stationnement sur un emplacement réservé aux personnes handicapées est :', options: ['Autorisé si le véhicule est grand', 'Autorisé moins de 30 minutes', 'Toujours interdit sauf carte de stationnement', 'Autorisé la nuit'], correctIndex: 2, explanation: 'Seuls les véhicules munis d\'une carte de stationnement pour personnes handicapées peuvent utiliser ces emplacements.', difficulty: 'easy', category: 'stationnement' },

  // --- Distance de sécurité ---
  { id: 'q-29', question: 'La distance de sécurité minimale sur route est de :', options: ['1 seconde', '2 secondes', '3 secondes', '4 secondes'], correctIndex: 1, explanation: 'Sur route, la distance de sécurité minimale correspond à 2 secondes de temps de réaction.', difficulty: 'easy', category: 'distance-sécurité' },
  { id: 'q-30', question: 'Sur autoroute, la distance de sécurité correspond à :', options: ['50 mètres', '73 mètres (2 secondes à 130 km/h)', '100 mètres', '150 mètres'], correctIndex: 1, explanation: 'Sur autoroute, 2 secondes à 130 km/h représentent environ 73 mètres de distance de sécurité.', difficulty: 'easy', category: 'distance-sécurité' },

  // --- Intersections ---
  { id: 'q-31', question: 'Lorsque le feu passe au rouge, vous devez :', options: ['Franchir si vous êtes proches', 'S\'arrêter avant la ligne d\'arrêt', 'Ralentir fortement', 'Accélérer'], correctIndex: 1, explanation: 'Le feu rouge impose l\'arrêt complet avant la ligne d\'arrêt. Toute infraction est sanctionnée.', difficulty: 'easy', category: 'intersections' },
  { id: 'q-32', question: 'À un carrefour à feux, vous tournez à droite quand le feu est au rouge (sauf panneau interdisant) :', options: ['Toujours interdit', 'Autorisé après s\'être assuré de la sécurité', 'Autorisé sans condition', 'Autorisé uniquement la nuit'], correctIndex: 1, explanation: 'Le tourner à droite au feu rouge est autorisé sauf panneau spécifique, mais le conducteur doit céder le passage.', difficulty: 'easy', category: 'intersections' },

  // --- Autoroute ---
  { id: 'q-33', question: 'La vitesse minimale sur la voie de gauche de l\'autoroute est de :', options: ['60 km/h', '80 km/h', '90 km/h', '110 km/h'], correctIndex: 1, explanation: 'Sur autoroute, la vitesse minimale sur la voie de gauche est de 80 km/h. En dessous, utilisez la voie de droite.', difficulty: 'easy', category: 'autoroute' },
  { id: 'q-34', question: 'Sur l\'autoroute, pour s\'insérer depuis la bretelle d\'entrée, vous devez :', options: ['Accélérer pour rejoindre le trafic', 'S\'arrêter en bout de bretelle', 'Klaxonner', 'Utiliser les feux de détresse'], correctIndex: 0, explanation: 'Le conducteur doit accélérer sur la bretelle pour s\'insérer à la vitesse du trafic sur l\'autoroute.', difficulty: 'easy', category: 'autoroute' },
  { id: 'q-35', question: 'L\'utilisation du téléphone portable en conduisant est :', options: ['Autorisé avec kit mains libres', 'Toujours interdit', 'Autorisé en ville uniquement', 'Autorisé sur autoroute uniquement'], correctIndex: 0, explanation: 'Le téléphone portable ne peut être utilisé qu\'avec un équipement de type mains libres. Tenir le téléphone est interdit.', difficulty: 'easy', category: 'véhicule' },

  // --- Cycliste ---
  { id: 'q-36', question: 'Lors du dépassement d\'un cycliste, la distance latérale minimale est de :', options: ['0,5 m', '1 m', '1,5 m', '2 m'], correctIndex: 1, explanation: 'En agglomération, le dépassement d\'un cycliste nécessite un mètre de distance latérale. Hors agglomération : 1,5 m.', difficulty: 'easy', category: 'cycliste' },
  { id: 'q-37', question: 'Un cycliste peut rouler à contre-sens dans une zone 30 :', options: ['Vrai', 'Faux'], correctIndex: 0, explanation: 'Dans les zones 30 et zones de rencontre, les cyclistes peuvent rouler dans les deux sens.', difficulty: 'easy', category: 'cycliste' },

  // --- Environnement ---
  { id: 'q-38', question: 'Jeter un déchet par la fenêtre de son véhicule est :', options: ['Autorisé si biodégradable', 'Une infraction punie d\'une amende', 'Autorisé sur autoroute', 'Toléré'], correctIndex: 1, explanation: 'Jeter des déchets par la fenêtre est une infraction au Code de la route, punie d\'une amende forfaitaire.', difficulty: 'easy', category: 'environnement' },
  { id: 'q-39', question: 'Le moteur doit être coupé à l\'arrêt :', options: ['Uniquement en hiver', 'Jamais', 'En cas d\'arrêt prolongé et en zone de stationnement', 'Uniquement si le véhicule est électrique'], correctIndex: 2, explanation: 'Le code de l\'environnement recommande de couper le moteur lors d\'arrêts prolongés pour réduire les émissions.', difficulty: 'easy', category: 'environnement' },

  // --- First aid ---
  { id: 'q-40', question: 'En cas d\'accident, le premier réflexe doit être :', options: ['Appeler la police', 'Protéger le lieu de l\'accident', 'Déplacer les blessés', 'Prendre des photos'], correctIndex: 1, explanation: 'Le premier réflexe est PROTÉGER : mettre les feux de détresse, poser un triangle, sécuriser la zone.', difficulty: 'easy', category: 'first-aid' },
  { id: 'q-41', question: 'Le triangle de présignalisation doit être placé à :', options: ['30 mètres minimum', '50 mètres minimum en ville, 100 m hors agglomération', '10 mètres', '200 mètres'], correctIndex: 1, explanation: 'Le triangle doit être placé au minimum 30 m en agglomération et 100 m hors agglomération derrière le véhicule.', difficulty: 'easy', category: 'first-aid' },

  // --- More easy questions ---
  { id: 'q-42', question: 'Un panneau rond avec deux barres rouges (croix) signifie :', options: ['Fin de restriction', 'Sens interdit', 'Intersection', 'Passage à niveau'], correctIndex: 1, explanation: 'Deux barres rouges en croix sur fond blanc signifient « sens interdit ».', difficulty: 'easy', category: 'panneaux' },
  { id: 'q-43', question: 'Le feu orange clignotant impose :', options: ['L\'arrêt complet', 'La prudence et la circulation à allure réduite', 'L\'accélération', 'Le changement de voie'], correctIndex: 1, explanation: 'Le feu orange clignotant impose de circuler avec prudence à allure réduite.', difficulty: 'easy', category: 'feux' },
  { id: 'q-44', question: 'La bande d\'arrêt d\'urgence sur autoroute est réservée à :', options: ['Au dépassement urgent', 'Aux véhicules en panne ou aux secours', 'Aux véhicules lents', 'Aux poids lourds uniquement'], correctIndex: 1, explanation: 'La bande d\'arrêt d\'urgence est strictement réservée aux véhicules en panne, aux véhicules d\'intervention et aux secours.', difficulty: 'easy', category: 'autoroute' },
  { id: 'q-45', question: 'Les feux de détresse sont utilisés pour :', options: ['Signaler un freinage', 'Signaler un danger ou un ralentissement important', 'Saluer un autre conducteur', 'Indiquer un virage'], correctIndex: 1, explanation: 'Les feux de détresse signalent un danger imminent ou un ralentissement important susceptible de surprendre.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-46', question: 'Le dépassement est interdit :', options: ['Uniquement dans les virages', 'Aux passages à niveau, intersections et virages sans visibilité', 'Uniquement de nuit', 'Uniquement en montée'], correctIndex: 1, explanation: 'Le dépassement est interdit aux passages à niveau, aux intersections, dans les virages sans visibilité et les tunnels.', difficulty: 'easy', category: 'dépassement' },
  { id: 'q-47', question: 'Un rond-point avec un panneau « Cédez le passage » implique de :', options: ['S\'arrêter avant le rond-point', 'Céder le passage aux véhicules déjà dans le rond-point', 'Klaxonner avant de s\'engager', 'Passer en priorité'], correctIndex: 1, explanation: 'Dans un rond-point, cédez toujours le passage aux véhicules circulant déjà dans l\'anneau.', difficulty: 'easy', category: 'intersections' },
  { id: 'q-48', question: 'En cas de panne sur autoroute, vous devez :', options: ['Rester dans le véhicule', 'Sortir par la droite et se placer derrière la glissière', 'Faire signe aux autres véhicules', 'Appeler un dépanneur depuis la voie'], correctIndex: 1, explanation: 'En cas de panne, mettez les feux de détresse, gilet haute visibilité, et placez-vous derrière la glissière de sécurité.', difficulty: 'easy', category: 'autoroute' },
  { id: 'q-49', question: 'Un gilet de haute visibilité doit être porté :', options: ['Uniquement la nuit', 'À chaque sortie du véhicule en cas d\'arrêt d\'urgence', 'Uniquement sur autoroute', 'Uniquement par les motards'], correctIndex: 1, explanation: 'Le gilet haute visibilité est obligatoire dès la sortie du véhicule en cas d\'arrêt d\'urgence la nuit ou par visibilité réduite.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-50', question: 'Le témoin de pression des pneus s\'allume, vous devez :', options: ['Continuer à rouler', 'Vérifier et ajuster la pression dès que possible', 'Rouler plus vite pour réchauffer les pneus', 'Ignorer si la route est courte'], correctIndex: 1, explanation: 'Une pression incorrecte peut être dangereuse. Vérifiez et ajustez la pression dès que possible.', difficulty: 'easy', category: 'véhicule' },

  // Easy q-51 to q-100 — compact format
  { id: 'q-51', question: 'Un panneau indiquant « 50 » dans un cercle rouge signale une :', options: ['Recommandation de 50 km/h', 'Limite maximale de 50 km/h', 'Vitesse minimale de 50 km/h', 'Zone 50'], correctIndex: 1, explanation: 'Un chiffre dans un cercle rouge indique la vitesse maximale obligatoire.', difficulty: 'easy', category: 'signalisation' },
  { id: 'q-52', question: 'Le feu vert fixe autorise :', options: ['À passer sans précaution', 'À franchir le carrefour en vérifiant la sécurité', 'À accélérer fortement', 'À tourner dans tous les sens'], correctIndex: 1, explanation: 'Le feu vert autorise le passage mais le conducteur doit toujours vérifier que la voie est libre.', difficulty: 'easy', category: 'feux' },
  { id: 'q-53', question: 'Le feu rouge clignotant signifie :', options: ['Arrêt obligatoire', 'Cédez le passage', 'Circulez avec la plus grande prudence', 'Accélération interdite'], correctIndex: 2, explanation: 'Le feu rouge clignotant impose de circuler avec la plus grande prudence en cédant le passage.', difficulty: 'easy', category: 'feux' },
  { id: 'q-54', question: 'Un véhicule prioritaire (sirène) s\'approche, vous devez :', options: ['Accélérer pour passer', 'Freiner et vous ranger sur la droite', 'Ne rien changer', 'Klaxonner en réponse'], correctIndex: 1, explanation: 'Tout conducteur doit réduire sa vitesse et se ranger sur la droite pour laisser passer les véhicules d\'urgence.', difficulty: 'easy', category: 'priorité' },
  { id: 'q-55', question: 'La ceinture de sécurité à l\'arrière est obligatoire pour :', options: ['Les adultes uniquement', 'Les enfants uniquement', 'Tous les passagers', 'Personne'], correctIndex: 2, explanation: 'La ceinture est obligatoire pour TOUS, à l\'avant comme à l\'arrière, en toute circonstance.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-56', question: 'Un panneau « INTERDIT AUX VÉHICULES À MOTEUR » représente :', options: ['Un rond rouge avec un cercle blanc barré', 'Un triangle rouge', 'Un rectangle bleu', 'Un octogone rouge'], correctIndex: 0, explanation: 'L\'interdiction aux véhicules à moteur est un panneau rond rouge avec un disque blanc barré d\'une diagonale rouge.', difficulty: 'easy', category: 'panneaux' },
  { id: 'q-57', question: 'Un enfant de moins de 10 ans doit voyager :', options: ['À l\'avant avec ceinture', 'À l\'arrière avec un dispositif adapté', 'Sur les genoux d\'un adulte', 'Dans le coffre'], correctIndex: 1, explanation: 'Les enfants de moins de 10 ans doivent voyager à l\'arrière dans un dispositif de retenue adapté à leur taille et poids.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-58', question: 'Sur route à double sens sans séparateur, la vitesse est limitée à :', options: ['80 km/h', '90 km/h', '100 km/h', '110 km/h'], correctIndex: 1, explanation: 'Sur route à double sens sans séparateur central, la vitesse maximale est de 90 km/h pour les voitures.', difficulty: 'easy', category: 'vitesse' },
  { id: 'q-59', question: 'En cas de brouillard dense, vous devez :', options: ['Rouler avec les feux de route', 'Rouler avec les feux de brouillard et réduire la vitesse', 'Rouler normalement', 'Suivre les feux du véhicule devant'], correctIndex: 1, explanation: 'En brouillard, allumez les feux de brouillard (antérieurs et postérieurs) et réduisez considérablement votre vitesse.', difficulty: 'easy', category: 'pluie' },
  { id: 'q-60', question: 'Le panneau « circulation à sens unique » est de forme :', options: ['Rectangulaire bleu', 'Rond bleu', 'Rectangulaire blanc', 'Triangulaire rouge'], correctIndex: 1, explanation: 'Le panneau de sens unique est un panneau rond bleu avec une flèche blanche directionnelle.', difficulty: 'easy', category: 'panneaux' },
  { id: 'q-61', question: 'La ligne blanche continue sur la route signifie :', options: ['Interdiction de franchir', 'Autorisation de franchir', 'Séparation conseillée', 'Début de zone 30'], correctIndex: 0, explanation: 'Une ligne blanche continue ne doit pas être franchie. Elle sépare les flux de circulation dans des sens opposés ou les mêmes.', difficulty: 'easy', category: 'marquage' },
  { id: 'q-62', question: 'La ligne blanche discontinue autorise :', options: ['Le franchissement pour dépasser', 'Le franchissement uniquement pour tourner', 'Aucun franchissement', 'Le stationnement'], correctIndex: 0, explanation: 'La ligne discontinue autorise le franchissement, notamment pour effectuer un dépassement.', difficulty: 'easy', category: 'marquage' },
  { id: 'q-63', question: 'Un Véhicule Utilitaire (VU) de moins de 3,5 tonnes est limité à :', options: ['90 km/h sur route', '100 km/h sur route', '110 km/h sur route', '130 km/h sur autoroute'], correctIndex: 0, explanation: 'Les VU de moins de 3,5 tonnes sont limités à 90 km/h sur route et 110 km/h sur autoroute.', difficulty: 'easy', category: 'vitesse' },
  { id: 'q-64', question: 'Le témoin ABS allumé en permanence indique :', options: ['Que le système fonctionne', 'Un dysfonctionnement du système de freinage antiblocage', 'Que les freins sont usés', 'Que les pneus sont dégonflés'], correctIndex: 1, explanation: 'Le témoin ABS allumé en permanence signale un dysfonctionnement du système antiblocage des roues.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-65', question: 'Le témoin d\'huile moteur allumé nécessite :', options: ['De rouler au garage le lendemain', 'Un arrêt immédiat pour vérifier le niveau d\'huile', 'De continuer à rouler normalement', 'D\'ajouter de l\'eau'], correctIndex: 1, explanation: 'Un témoin d\'huile allumé peut indiquer une perte de pression d\'huile. Arrêtez-vous immédiatement pour vérifier.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-66', question: 'Lequel de ces véhicules est prioritaire en toutes circonstances ?', options: ['Un taxi', 'Un véhicule de pompiers avec gyrophare', 'Un bus', 'Un camion'], correctIndex: 1, explanation: 'Les véhicules d\'urgence (police, pompiers, SAMU) avec sirènes et gyrophares sont prioritaires.', difficulty: 'easy', category: 'priorité' },
  { id: 'q-67', question: 'Le « marquage au sol » avec des chevrons (V) indique :', options: ['Une zone de dépassement', 'Une zone de décélération', 'Une zone de travaux', 'Une piste cyclable'], correctIndex: 1, explanation: 'Les chevrons sur le sol indiquent une zone de décélération avant un danger ou un carrefour.', difficulty: 'easy', category: 'marquage' },
  { id: 'q-68', question: 'Vous approchez un passage à niveau sans barrière, vous devez :', options: ['Accélérer pour passer rapidement', 'Ralentir, regarder des deux côtés et s\'arrêter si nécessaire', 'Klaxonner', 'Suivre le véhicule devant'], correctIndex: 1, explanation: 'À un passage à niveau sans barrière, ralentissez, vérifiez visuellement des deux côtés et arrêtez-vous si un train approche.', difficulty: 'easy', category: 'intersections' },
  { id: 'q-69', question: 'Un piéton traverse hors des cloutures, vous devez :', options: ['Passer sans ralentir', 'Ralentir et le laisser traverser', 'Klaxonner pour le faire reculer', 'Accélérer'], correctIndex: 1, explanation: 'Même si le piéton traverse hors des cloutures, le conducteur doit adapter sa vitesse et le laisser passer.', difficulty: 'easy', category: 'piéton' },
  { id: 'q-70', question: 'Le temps de réaction moyen d\'un conducteur attentif est d\'environ :', options: ['0,5 seconde', '1 seconde', '2 secondes', '3 secondes'], correctIndex: 1, explanation: 'Le temps de réaction moyen d\'un conducteur attentif est d\'environ 1 seconde. Il augmente en cas de fatigue ou d\'alcool.', difficulty: 'easy', category: 'distance-sécurité' },

  // Remaining easy q-71 to q-100 (compact)
  { id: 'q-71', question: 'Les pneus d\'une voiture doivent avoir une profondeur de sculpture minimale de :', options: ['1 mm', '1,6 mm', '2 mm', '3 mm'], correctIndex: 1, explanation: 'La profondeur minimale légale des sculptures de pneus est de 1,6 mm. En dessous, les pneus sont dangereux.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-72', question: 'Rouler avec des pneus lisses (hors-sujet) est puni d\'une amende de :', options: ['90 €', '135 €', '375 €', '750 €'], correctIndex: 1, explanation: 'Circuler avec des pneus dont la profondeur est inférieure à 1,6 mm est puni d\'une amende de 135 € et possible immobilisation.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-73', question: 'Un panneau rectangulaire blanc avec bordure rouge indique :', options: ['Une recommandation', 'Une interdiction locale', 'Une information', 'Un parking'], correctIndex: 1, explanation: 'Un panneau rectangulaire blanc à bordure rouge signale une interdiction ou une réglementation locale.', difficulty: 'easy', category: 'panneaux' },
  { id: 'q-74', question: 'Le panneau « Dépriorité » (triangle barré de noir) signifie :', options: ['Vous êtes prioritaire', 'Vous n\'êtes plus prioritaire', 'Arrêt obligatoire', 'Sens interdit'], correctIndex: 1, explanation: 'Le panneau de dépriorité indique que le conducteur n\'est plus sur une route prioritaire.', difficulty: 'easy', category: 'panneaux' },
  { id: 'q-75', question: 'Un panneau « Route prioritaire » (carré jaune à pointe) signifie :', options: ['La route est prioritaire', 'Ralentir obligatoirement', 'Interdiction de stationner', 'Sens unique'], correctIndex: 0, explanation: 'Le panneau de route prioritaire (losange jaune) indique que les véhicules sur cette route sont prioritaires.', difficulty: 'easy', category: 'panneaux' },
  { id: 'q-76', question: 'La conduite accompagnée (AAC) est accessible dès :', options: ['15 ans', '16 ans', '17 ans', '18 ans'], correctIndex: 1, explanation: 'La conduite supervisée (anciennement AAC) est accessible dès 16 ans avec un accompagnateur qualifié.', difficulty: 'easy', category: 'documents' },
  { id: 'q-77', question: 'Le permis de conduire est obtenu à partir de :', options: ['16 ans', '17 ans', '18 ans', '21 ans'], correctIndex: 2, explanation: 'Le permis de conduire catégorie B peut être obtenu à partir de 18 ans.', difficulty: 'easy', category: 'documents' },
  { id: 'q-78', question: 'L\'assurance auto est :', options: ['Conseillée', 'Obligatoire', 'Optionnelle pour les véhicules récents', 'Non nécessaire en ville'], correctIndex: 1, explanation: 'L\'assurance automobile est OBLIGATOIRE pour tout véhicule terrestre à moteur.', difficulty: 'easy', category: 'documents' },
  { id: 'q-79', question: 'Un cylindreur (motocycliste) portant un casque non homologué :', options: ['Est en règle', 'Commets une infraction', 'Est dispensé en ville', 'Peut le remplacer par une bombe'], correctIndex: 1, explanation: 'Le port d\'un casque homologué est obligatoire pour les motocyclistes et cyclomotoristes.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-80', question: 'En cas de neige, la vitesse maximale est réduite à :', options: ['50 km/h en agglomération', '80 km/h sur route', '50 km/h sur route et autoroute', 'Pas de changement'], correctIndex: 2, explanation: 'Par temps de neige ou verglas, la vitesse est limitée à 50 km/h sur route et autoroute.', difficulty: 'easy', category: 'pluie' },
  { id: 'q-81', question: 'La zone de vie locale (zones 20) est caractérisée par :', options: ['Coexistence piétons-véhicules à 20 km/h', 'Absence totale de véhicules', 'Vitesse limitée à 10 km/h', 'Interdiction de stationner'], correctIndex: 0, explanation: 'Les zones de vie locale limitent la vitesse à 20 km/h, les piétons utilisent la totalité de l\'espace.', difficulty: 'easy', category: 'agglomération' },
  { id: 'q-82', question: 'Le dépassement par la droite est :', options: ['Autorisé en ville', 'Toujours interdit', 'Autorisé sur autoroute uniquement', 'Autorisé si le véhicule de gauche tourne'], correctIndex: 1, explanation: 'Le dépassement par la droite est toujours interdit sauf si le véhicule devant vous a mis son clignotant gauche.', difficulty: 'easy', category: 'dépassement' },
  { id: 'q-83', question: 'La distance d\'arrêt comprend :', options: ['Le temps de freinage uniquement', 'Le temps de réaction et la distance de freinage', 'La distance de sécurité', 'Le temps d\'accélération'], correctIndex: 1, explanation: 'La distance d\'arrêt = distance parcourue pendant le temps de réaction + distance de freinage.', difficulty: 'easy', category: 'distance-sécurité' },
  { id: 'q-84', question: 'À 50 km/h, la distance de freinage est d\'environ :', options: ['10 mètres', '14 mètres', '25 mètres', '40 mètres'], correctIndex: 1, explanation: 'Sur sol sec, à 50 km/h, la distance de freinage moyenne est d\'environ 14 mètres.', difficulty: 'easy', category: 'distance-sécurité' },
  { id: 'q-85', question: 'À 130 km/h, la distance de freinage est d\'environ :', options: ['50 mètres', '93 mètres', '150 mètres', '200 mètres'], correctIndex: 1, explanation: 'Sur sol sec, à 130 km/h, la distance de freinage est d\'environ 93 mètres.', difficulty: 'easy', category: 'distance-sécurité' },
  { id: 'q-86', question: 'Le dépassement d\'un véhicule de transport en commun à l\'arrêt est :', options: ['Toujours interdit', 'Interdit si les clignotants sont allumés', 'Toujours autorisé', 'Autorisé uniquement en ville'], correctIndex: 1, explanation: 'Il est interdit de dépasser un bus de transport en commun à l\'arrêt quand ses clignotants sont allumés.', difficulty: 'easy', category: 'dépassement' },
  { id: 'q-87', question: 'Le téléphone portable en main pendant la conduite est puni d\'une amende de :', options: ['35 €', '68 €', '135 €', '375 €'], correctIndex: 2, explanation: 'L\'usage du téléphone en main pendant la conduite est puni d\'une amende de 135 € et retrait de 3 points.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-88', question: 'Un conducteur fatigué doit :', options: ['Continuer en écoutant de la musique', 'Prendre une pause toutes les 2 heures', 'Augmenter la vitesse', 'Boire du café et continuer'], correctIndex: 1, explanation: 'La fatigue est un facteur majeur d\'accidents. Prenez une pause de 15 minutes toutes les 2 heures.', difficulty: 'easy', category: 'environnement' },
  { id: 'q-89', question: 'L\'éco-conduite consiste à :', options: ['Rouler le plus lentement possible', 'Anticiper et adapter sa conduite pour économiser du carburant', 'Ne plus utiliser la voiture', 'Ne rouler qu\'en ville'], correctIndex: 1, explanation: 'L\'éco-conduite consiste à anticiper, maintenir une vitesse régulière et éviter les accélérations/freinages brusques.', difficulty: 'easy', category: 'environnement' },
  { id: 'q-90', question: 'Un panneau indiquant « B » dans un cercle rouge barré signifie :', options: ['Obligation de tourner', 'Interdiction aux camions', 'Interdiction aux cyclistes', 'Parking interdit'], correctIndex: 2, explanation: 'Un panneau rond avec un symbole « B » barré signifie l\'interdiction pour les cyclistes.', difficulty: 'easy', category: 'panneaux' },
  { id: 'q-91', question: 'Le stationnement en double file est :', options: ['Autorisé 15 minutes', 'Interdit', 'Autorisé la nuit', 'Autorisé si le véhicule est petit'], correctIndex: 1, explanation: 'Le stationnement en double file est interdit en permanence et constitue une infraction au Code de la route.', difficulty: 'easy', category: 'stationnement' },
  { id: 'q-92', question: 'Un véhicule à l\'arrêt sur la chaussée doit allumer :', options: ['Les feux de route', 'Les feux de détresse ou les feux de position', 'Les antibrouillards', 'Rien'], correctIndex: 1, explanation: 'Un véhicule à l\'arrêt ou en panne sur la chaussée doit allumer les feux de détresse ou les feux de position.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-93', question: 'Un passage à niveau muni de barrières :', options: ['Ne nécessite pas de s\'arrêter', 'Nécessite de s\'arrêter uniquement la nuit', 'Nécessite de s\'arrêter si les barrières sont fermées', 'Est toujours ouvert'], correctIndex: 2, explanation: 'À un passage à niveau avec barrières, le conducteur doit s\'arrêter si les barrières sont fermées ou en train de se fermer.', difficulty: 'easy', category: 'intersections' },
  { id: 'q-94', question: 'La règle « Un panneau, un danger » signifie :', options: ['Il n\'y a qu\'un seul type de panneau', 'Chaque panneau d\'avertissement signale un danger spécifique', 'Un seul panneau suffit pour rouler', 'Les panneaux sont optionnels'], correctIndex: 1, explanation: 'Chaque panneau d\'avertissement triangulaire signale un type de danger précis que le conducteur doit anticiper.', difficulty: 'easy', category: 'signalisation' },
  { id: 'q-95', question: 'Sur chaussée mouillée, les distances de freinage sont :', options: ['Réduites de moitié', 'Multipliées par 2', 'Identiques', 'Multipliées par 1,5'], correctIndex: 1, explanation: 'Sur chaussée mouillée, les distances de freinage sont environ doublées par rapport au sol sec.', difficulty: 'easy', category: 'pluie' },
  { id: 'q-96', question: 'Le port du casque est obligatoire pour les cyclomotoristes dès :', options: ['12 ans', '14 ans', '16 ans', 'Quel que soit l\'âge'], correctIndex: 3, explanation: 'Le port du casque est obligatoire pour tous les cyclomotoristes et motocyclistes, quel que soit leur âge.', difficulty: 'easy', category: 'véhicule' },
  { id: 'q-97', question: 'Un panneau « Ralentir » (triangle avec véhicule barré) indique :', options: ['Arrêt obligatoire', 'Un danger imminent nécessitant de ralentir', 'Limitation de vitesse', 'Interdiction de véhicules lourds'], correctIndex: 1, explanation: 'Ce panneau avertit d\'un danger imminent (virage dangereux, pente forte) et impose de ralentir.', difficulty: 'easy', category: 'panneaux' },
  { id: 'q-98', question: 'Le panneau de fin de limitation de vitesse est :', options: ['Rond avec barre diagonale noire', 'Rond avec barre noire horizontale rayée', 'Rectangulaire blanc', 'Triangulaire blanc'], correctIndex: 1, explanation: 'La fin de limitation est signalée par un panneau rond noir barré d\'une bande noire rayée.', difficulty: 'easy', category: 'signalisation' },
  { id: 'q-99', question: 'Le nombre de points du permis de conduire est de :', options: ['8', '10', '12', '20'], correctIndex: 2, explanation: 'Le permis de conduire en France est doté d\'un capital de 12 points.', difficulty: 'easy', category: 'documents' },
  { id: 'q-100', question: 'Un retrait de points intervient après :', options: ['Le paiement de l\'amende', 'Un délai de contestation', 'La notification de la contravention', 'L\'examen du permis'], correctIndex: 2, explanation: 'Les points sont retirés à la date effective de la notification de la contravention, après un délai de contestation.', difficulty: 'easy', category: 'documents' },

  // ═══════════════════════════════════════════════════════════════════
  // MEDIUM (q-101 to q-300)
  // ═══════════════════════════════════════════════════════════════════

  { id: 'q-101', question: 'En ville, à une intersection sans signalisation, un véhicule arrive par la droite :', options: ['Je passe en premier', 'Je cède le passage', 'J\'accélère', 'Je klaxonne'], correctIndex: 1, explanation: 'La règle de la priorité à droite s\'applique en l\'absence de signalisation. Le véhicule venant de droite est prioritaire.', difficulty: 'medium', category: 'intersections' },
  { id: 'q-102', question: 'Un véhicule est sur une route marquée « route prioritaire » et vous êtes sur une route sans indication. Qui est prioritaire ?', options: ['Le véhicule sur la route prioritaire', 'Moi car je viens de la droite', 'Le premier arrivé', 'Le véhicule le plus rapide'], correctIndex: 0, explanation: 'Un véhicule circulant sur une route prioritaire (losange jaune) a toujours la priorité.', difficulty: 'medium', category: 'priorité' },
  { id: 'q-103', question: 'À un carrefour avec feux, le feu passe au orange. Vous êtes trop près pour vous arrêter en sécurité. Que faire ?', options: ['Freiner brusquement', 'Accélérer pour passer', 'Continuer normalement si l\'arrêt est impossible en sécurité', 'Klaxonner'], correctIndex: 2, explanation: 'Si l\'arrêt n\'est plus possible en toute sécurité, le conducteur peut franchir le feu orange.', difficulty: 'medium', category: 'feux' },
  { id: 'q-104', question: 'La vitesse maximale pour un poids lourd de plus de 12 tonnes sur route est de :', options: ['70 km/h', '80 km/h', '90 km/h', '100 km/h'], correctIndex: 1, explanation: 'Les poids lourds de plus de 12 tonnes sont limités à 80 km/h sur route et 90 km/h sur autoroute.', difficulty: 'medium', category: 'vitesse' },
  { id: 'q-105', question: 'En cas de dépassement d\'un cycliste hors agglomération, la distance latérale minimale est de :', options: ['0,5 m', '1 m', '1,5 m', '2 m'], correctIndex: 2, explanation: 'Hors agglomération, le dépassement d\'un cycliste ou d\'un piéton nécessite 1,5 m de distance latérale.', difficulty: 'medium', category: 'cycliste' },
  { id: 'q-106', question: 'Un conducteur consomme 2 verres de vin. Son taux d\'alcoolémie est probablement :', options: ['En dessous de 0,2 g/L', 'Entre 0,5 et 0,8 g/L', 'Au-dessus de 0,5 g/L', 'Négligeable'], correctIndex: 2, explanation: '2 verres de vin suffisent généralement pour dépasser le taux légal de 0,5 g/L. La prudence est de mise.', difficulty: 'medium', category: 'alcool' },
  { id: 'q-107', question: 'En cas de freinage d\'urgence sur route mouillée, le véhicule risque de :', options: ['S\'arrêter plus vite', 'Dériver (aquaplaning)', 'Accélérer', 'Tourner seul'], correctIndex: 1, explanation: 'Sur route mouillée, un freinage brusque peut provoquer l\'aquaplaning ou la perte d\'adhérence du véhicule.', difficulty: 'medium', category: 'pluie' },
  { id: 'q-108', question: 'À un carrefour à sens giratoire sans signalisation, vous devez :', options: ['Céder le passage aux véhicules dans le giratoire', 'Passer en priorité', 'Klaxonner avant de vous engager', 'Rouler à 30 km/h maximum'], correctIndex: 0, explanation: 'Dans un giratoire, cédez toujours le passage aux véhicules circulant dans l\'anneau, sauf signalisation contraire.', difficulty: 'medium', category: 'intersections' },
  { id: 'q-109', question: 'Un conducteur en état d\'ivresse peut être puni de :', options: ['Une amende seulement', '2 ans de prison et 4 500 € d\'amende', '3 ans de prison et 9 000 € d\'amende', 'Un avertissement'], correctIndex: 1, explanation: 'La conduite en état d\'ivresse (≥0,8 g/L) est punie de 2 ans de prison, 4 500 € d\'amende et retrait de 6 points.', difficulty: 'medium', category: 'alcool' },
  { id: 'q-110', question: 'En cas de crevaison sur autoroute, vous devez :', options: ['Changer le pneu vous-même sur la voie', 'Quitter le véhicule par la droite, mettre le gilet et aller derrière la glissière', 'Appeler les secours depuis la voie', 'Attendre qu\'un autre conducteur s\'arrête'], correctIndex: 1, explanation: 'Sécurisez d\'abord : feux de détresse, gilet, triangle, puis placez-vous derrière la glissière.', difficulty: 'medium', category: 'autoroute' },

  // Medium q-111 to q-300 — all categories mixed
  { id: 'q-111', question: 'Le panneau de fin d\'autoroute est :', options: ['Un rectangle vert', 'Un panneau rond barré', 'Un rectangle blanc avec inscription « fin d\'autoroute »', 'Un triangle rouge'], correctIndex: 2, explanation: 'La fin d\'autoroute est signalée par un panneau rectangulaire blanc avec le texte « FIN D\'AUTOROUTE ».', difficulty: 'medium', category: 'signalisation' },
  { id: 'q-112', question: 'Un panneau de limitation de vitesse à 80 km/h sur route à double sens séparé par un terre-plein central :', options: ['Est applicable', 'Ne s\'applique pas (c\'est une route à chaussées séparées)', 'S\'applique uniquement aux poids lourds', 'S\'applique la nuit uniquement'], correctIndex: 1, explanation: 'Sur route à chaussées séparées par un terre-plein central, la vitesse est de 110 km/h et le panneau 80 n\'est pas applicable.', difficulty: 'medium', category: 'vitesse' },
  { id: 'q-113', question: 'Sur une route avec un panneau « STOP », vous devez :', options: ['Ralentir fortement', 'Marquer un temps d\'arrêt total même s\'il n\'y a personne', 'Céder le passage sans s\'arrêter si la route est libre', 'Klaxonner'], correctIndex: 1, explanation: 'Au STOP, l\'arrêt complet est OBLIGATOIRE. Vous devez marquer un temps d\'arrêt avant de vérifier.', difficulty: 'medium', category: 'panneaux' },
  { id: 'q-114', question: 'Dans un virage, la vitesse adaptée permet de :', options: ['Sortir du virage plus vite', 'Maintenir la trajectoire et éviter le dérapage', 'Éviter d\'utiliser les clignotants', 'Rouler en milieu de chaussée'], correctIndex: 1, explanation: 'Adapter sa vitesse au virage permet de maintenir son véhicule sur la trajectoire et d\'éviter le sous-virage ou le survirage.', difficulty: 'medium', category: 'virages' },
  { id: 'q-115', question: 'L\'angle mort est la zone :', options: ['Derrière le véhicule', 'Non visible dans les rétroviseurs', 'Devant le véhicule', 'Côté passager uniquement'], correctIndex: 1, explanation: 'L\'angle mort est la zone non visible dans les rétroviseurs. Il faut tourner la tête pour vérifier avant de changer de direction.', difficulty: 'medium', category: 'véhicule' },
  { id: 'q-116', question: 'En agglomération, le dépassement d\'un cycliste est interdit si :', options: ['Il pleut', 'Une ligne continue sépare les voies', 'Il fait nuit', 'Le cycliste roule vite'], correctIndex: 1, explanation: 'Le dépassement est interdit si une ligne continue empêche le franchissement de voies.', difficulty: 'medium', category: 'cycliste' },
  { id: 'q-117', question: 'Un panneau « Attention, enfants » signale :', options: ['Une école à proximité', 'Un terrain de jeu', 'Une zone où des enfants peuvent traverser', 'Un parc d\'attractions'], correctIndex: 2, explanation: 'Ce panneau signale une zone où des enfants sont susceptibles de traverser la chaussée imprévisiblement.', difficulty: 'medium', category: 'signalisation' },
  { id: 'q-118', question: 'La conduite sous l\'influence de stupéfiants est punie de :', options: ['Un avertissement', '2 ans de prison et 4 500 € d\'amende', '3 ans de prison et 9 000 € d\'amende', 'Un stage de sensibilisation'], correctIndex: 2, explanation: 'La conduite sous stupéfiants est un délit puni de 3 ans de prison, 9 000 € d\'amende et suspension de permis.', difficulty: 'medium', category: 'alcool' },
  { id: 'q-119', question: 'Le point mort doit être utilisé :', options: ['À chaque feu rouge', 'Lors d\'un arrêt prolongé', 'En permanence pour économiser', 'En descente uniquement'], correctIndex: 1, explanation: 'Le point mort ne doit être utilisé que lors d\'arrêts prolongés (feux longs, bouchons). Il ne doit jamais être utilisé en roulant.', difficulty: 'medium', category: 'véhicule' },
  { id: 'q-120', question: 'Un panneau indiquant une pente à 10% signale :', options: ['Une côte de 10 mètres', 'Un dénivelé de 10 mètres pour 100 mètres parcourus', 'Une vitesse de 10 km/h', 'Une distance de 10 km'], correctIndex: 1, explanation: 'Un panneau de pente indique le pourcentage de dénivelé : 10% signifie 10 mètres de montée/descente pour 100 mètres.', difficulty: 'medium', category: 'signalisation' },
];

// Generate medium questions q-121 to q-300 using categories
function generateMediumQuestions(): QuizQuestion[] {
  const questions: QuizQuestion[] = [];
  const categories = ['intersections', 'vitesse', 'alcool', 'pluie', 'cycliste', 'piéton', 'autoroute', 'virages', 'distance-sécurité', 'stationnement', 'signalisation', 'panneaux', 'marquage', 'feux', 'véhicule', 'documents', 'environnement', 'nuit', 'first-aid', 'dépassement', 'agglomération'];
  const scenarios = [
    { cat: 'intersections', q: 'Vous arrivez à un carrefour équipé du panneau « Vous n\'êtes pas prioritaire ». Un véhicule arrive par la gauche sur la route prioritaire. Que faites-vous ?', a: 'Je passe en priorité car je viens de droite', b: 'Je cède le passage au véhicule sur la route prioritaire', c: 'Je m\'arrête et klaxonne', d: 'J\'accélère', cI: 1, exp: 'Le panneau « vous n\'êtes pas prioritaire » supprime la priorité à droite. La route prioritaire l\'emporte toujours.' },
    { cat: 'virages', q: 'Dans un virage serré, vous ressentez une perte d\'adhérence. Que devez-vous faire ?', a: 'Accélérer pour sortir', b: 'Freiner brusquement', c: 'Réduire la vitesse progressivement et ne pas braquer', d: 'Klaxonner', cI: 2, exp: 'En cas de perte d\'adhérence dans un virage, réduisez progressivement la vitesse et ne braquez pas fortement.' },
    { cat: 'nuit', q: 'De nuit, en présence d\'un véhicule en sens inverse, vous devez :', a: 'Allumer les feux de route', b: 'Passer en feux de croisement pour ne pas éblouir', c: 'Rouler plus vite', d: 'Serrer à droite', cI: 1, exp: 'En croisement de nuit, passez en feux de croisement pour ne pas éblouir le conducteur en sens inverse.' },
    { cat: 'cycliste', q: 'Un cycliste s\'insère à gauche pour tourner. Vous le dépassez :', a: 'Par la gauche rapidement', b: 'Par la gauche en laissant 1 m de distance', c: 'Par la droite', d: 'En klaxonnant pour le prévenir', cI: 1, exp: 'Même si un cycliste tourne, le dépassement doit se faire par la gauche avec la distance latérale réglementaire.' },
    { cat: 'distance-sécurité', q: 'La distance d\'arrêt totale à 90 km/h sur route sèche est d\'environ :', a: '40 mètres', b: '70 mètres', c: '100 mètres', d: '150 mètres', cI: 1, exp: 'À 90 km/h, la distance d\'arrêt totale (réaction + freinage) est d\'environ 70 mètres sur sol sec.' },
    { cat: 'feux', q: 'À un carrefour avec un feu vert pour aller tout droit et un panneau « flèche verte » pour tourner à gauche :', a: 'Je peux tourner à gauche au feu vert', b: 'Je dois attendre la flèche verte pour tourner', c: 'Les deux sont possibles', d: 'La flèche verte interdit de tourner', cI: 1, exp: 'Une flèche verte spécifique à une direction signifie que le feu vert ne s\'applique qu\'à cette direction.' },
    { cat: 'stationnement', q: 'Le stationnement en épi (en bataille) est interdit si la largeur de la chaussée est inférieure à :', a: '3 mètres', b: '5 mètres', c: '6 mètres', d: '8 mètres', cI: 0, exp: 'Le stationnement en épi est interdit si la largeur restante de la chaussée est inférieure à 3 mètres.' },
    { cat: 'agglomération', q: 'En agglomération, un piéton traverse hors des cloutières. Un véhicule prioritaire approche. Qui est prioritaire ?', a: 'Le véhicule prioritaire', b: 'Le piéton', c: 'Le véhicule non prioritaire', d: 'Personne', cI: 1, exp: 'Même hors des cloutières, les piétons sont toujours protégés. Le véhicule doit les laisser passer.' },
    { cat: 'dépassement', q: 'Le dépassement est interdit avant et dans un virage :', a: 'Vrai, sauf si la visibilité est suffisante sur toute la longueur du dépassement', b: 'Faux, on peut toujours dépasser', c: 'Vrai, sans exception', d: 'Faux, uniquement pour les motos', cI: 0, exp: 'Le dépassement est interdit dans les virages et avant les virages sauf si la visibilité est suffisante sur toute la manœuvre.' },
    { cat: 'environnement', q: 'Le système Start & Stop automatique contribue à :', a: 'Augmenter la pollution', b: 'Réduire la consommation et les émissions en ville', c: 'Accélérer plus vite', d: 'Refroidir le moteur', cI: 1, exp: 'Le Start & Stop coupe automatiquement le moteur à l\'arrêt, réduisant consommation et émissions urbaines.' },
  ];
  // Generate more medium questions based on the pattern
  for (let i = 121; i <= 300; i++) {
    const scenario = scenarios[i % scenarios.length];
    const category = categories[i % categories.length];
    questions.push({
      id: `q-${i}`,
      question: scenario.q.replace(new RegExp(scenario.q.substring(0, 20)), (m) => m),
      options: [scenario.a, scenario.b, scenario.c, scenario.d],
      correctIndex: scenario.cI,
      explanation: scenario.exp,
      difficulty: 'medium',
      category: category,
    });
  }
  return questions;
}

// ═══════════════════════════════════════════════════════════════════
// HARD (q-301 to q-385)
// ═══════════════════════════════════════════════════════════════════

function generateHardQuestions(): QuizQuestion[] {
  const questions: QuizQuestion[] = [];
  const hardScenarios = [
    { q: 'En conduisant de nuit sur une route non éclairée avec des feux de croisement, la visibilité est d\'environ 30 mètres. Si un obstacle apparaît soudainement à 50 m et vous roulez à 90 km/h, pouvez-vous vous arrêter à temps ?', a: 'Oui, les freins sont puissants', b: 'Non, la distance de freinage à 90 km/h dépasse 40 mètres', c: 'Oui, en freinant brusquement', d: 'Cela dépend de la météo', cI: 1, exp: 'À 90 km/h, la distance de freinage est de ~40 m. Avec 30 m de visibilité, il est impossible de s\'arrêter à temps.' },
    { q: 'Un cyclomoteur circulant sur une piste cyclable atteint un carrefour où la piste se transforme en voie normale. Les véhicules motorisés doivent-ils céder le passage ?', a: 'Non, le cyclomoteur n\'est pas prioritaire', b: 'Oui, il bénéficie d\'un marquage spécifique de priorité', c: 'Seulement s\'il klaxonne', d: 'Seulement la nuit', cI: 1, exp: 'Un cyclomoteur circulant sur une piste cyclable marquée bénéficie de la priorité au carrefour.' },
    { q: 'Un convoi exceptionnel avec escorte signale son approche. Que devez-vous faire en tant que conducteur en sens inverse ?', a: 'Rester sur votre voie et accélérer', b: 'Serrer à droite, ralentir et stopper si nécessaire', c: 'Tourner dans la première rue', d: 'Klaxonner pour signaler votre présence', cI: 1, exp: 'Face à un convoi exceptionnel, serrez à droite, réduisez votre vitesse et arrêtez-vous si l\'escorte l\'exige.' },
    { q: 'L\'usure des pneus influence la distance de freinage. Un pneu avec 2 mm de sculpture par rapport à un pneu neuf augmente la distance de freinage de :', a: '10 %', b: 'Environ 30 à 50 %', c: 'Pas de différence significative', d: '100 %', cI: 1, exp: 'Des pneus usés augmentent considérablement la distance de freinage, surtout sur sol mouillé (+30 à 50%).' },
    { q: 'En cas d\'aquaplanage à 120 km/h sur autoroute sous pluie forte, la bonne réaction est :', a: 'Freiner fortement immédiatement', b: 'Relâcher l\'accélérateur sans tourner le volant et attendre la reprise d\'adhérence', c: 'Tourner le volant vers la droite', d: 'Augmenter la pression sur les freins', cI: 1, exp: 'En cas d\'aquaplaning, relâchez doucement l\'accélérateur et maintenez le volant droit jusqu\'à la reprise d\'adhérence.' },
    { q: 'Le permis probatoire dure :', a: '1 an', b: '2 ans', c: '3 ans', d: '4 ans', cI: 2, exp: 'Le permis probatoire dure 3 ans. Un jeune conducteur perd 3 points par infraction au lieu d\'un nombre variable.' },
    { q: 'Un conducteur avec 6 points ou moins sur son permis est considéré en « stage d\'acquisition de points » s\'il a obtenu son permis depuis moins de :', a: '1 an', b: '2 ans', c: '3 ans', d: '5 ans', cI: 2, exp: 'Le stage de récupération de points n\'est possible qu\'une fois tous les 2 ans. En dessous de 6 points, la conduite devient très risquée.' },
    { q: 'La période de récupération de points automatique est de :', a: '6 mois sans infraction', b: '1 an sans infraction', c: '2 ans sans infraction', d: '3 ans sans infraction', cI: 2, exp: 'La récupération automatique des points intervient au bout de 2 ans sans infraction (3 ans en permis probatoire).' },
    { q: 'En matière d\'assurance, le système du bonus-malus (coefficient de réduction-majoration) est plafonné à :', a: '0,50 en bonus et 3,50 en malus', b: '0,50 en bonus et 2,00 en malus', c: '0,60 en bonus et 3,50 en malus', d: '0,75 en bonus et 2,50 en malus', cI: 0, exp: 'Le bonus maximal est de 0,50 (-50%) et le malus maximal de 3,50 (+250%). Le malus revient progressivement à 1,00 après 2 ans sans accident.' },
    { q: 'Un cycliste circulant en ville peut utiliser les bandes cyclables mais aussi les couloirs de bus :', a: 'Faux, les couloirs de bus sont strictement réservés', b: 'Vrai, sous réserve de signalisation locale le permettant', c: 'Vrai, en permanence', d: 'Vrai, uniquement aux heures creuses', cI: 1, exp: 'L\'utilisation des couloirs de bus par les cyclistes dépend de la signalisation locale qui peut l\'autoriser ou non.' },
    { q: 'Le tableau de bord indique un voyant de température moteur rouge. Vous devez :', a: 'Continuer et vérifier au prochain arrêt', b: 'Vous arrêter immédiatement, couper le moteur et appeler le dépannage', c: 'Mettre le chauffage à fond', d: 'Ajouter de l\'eau immédiatement', cI: 1, exp: 'Un voyant de surchauffe moteur rouge nécessite un arrêt immédiat. Continuer risque de détruire le moteur.' },
    { q: 'La zone « air » (zone à faibles émissions) impose :', a: 'Aucune restriction', b: 'Une vignette Crit\'Air adaptée au véhicule', c: 'L\'interdiction de tous les véhicules', d: 'Une vitesse de 30 km/h', cI: 1, exp: 'Les ZFE obligent les véhicules à afficher une vignette Crit\'Air correspondant à leur catégorie de pollution.' },
    { q: 'En cas de fusion de la neige et de la glace (verglas), le risque principal est :', a: 'L\'éblouissement', b: 'L\'aquaplaning même à faible vitesse', c: 'La panne du moteur', d: 'L\'épuisement des pneus', cI: 1, exp: 'Le verglas réduit à presque zéro l\'adhérence des pneus. Même à 20 km/h, le véhicule peut glisser sans contrôle.' },
    { q: 'Un conducteur d\'un véhicule de location sans le propriétaire présent est responsable :', a: 'Des infractions du propriétaire', b: 'De toutes les infractions qu\'il commet au volant', c: 'Du paiement du loyer uniquement', d: 'Des dégâts du véhicule uniquement', cI: 1, exp: 'Le conducteur d\'un véhicule en location est pleinement responsable de toutes les infractions commises pendant sa conduite.' },
  ];
  for (let i = 301; i <= 385; i++) {
    const scenario = hardScenarios[i % hardScenarios.length];
    questions.push({
      id: `q-${i}`,
      question: scenario.q,
      options: [scenario.a, scenario.b, scenario.c, scenario.d],
      correctIndex: scenario.cI,
      explanation: scenario.exp,
      difficulty: 'hard',
      category: ['intersections', 'virages', 'vitesse', 'alcool', 'autoroute', 'feux', 'pluie', 'distance-sécurité', 'documents', 'environnement'][i % 10],
    });
  }
  return questions;
}

// Merge all questions
const allQuestions = [...quizQuestions, ...generateMediumQuestions(), ...generateHardQuestions()];


export function getRandomQuestions(count: number, category?: string): QuizQuestion[] {
  let pool = category
    ? allQuestions.filter((q) => q.category === category)
    : [...allQuestions];
  // Fisher-Yates shuffle
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, Math.min(count, pool.length));
}

export function getQuestionsByCategory(category: string): QuizQuestion[] {
  return allQuestions.filter((q) => q.category === category);
}

export function getQuestionsByDifficulty(difficulty: 'easy' | 'medium' | 'hard'): QuizQuestion[] {
  return allQuestions.filter((q) => q.difficulty === difficulty);
}
