// ═══════════════════════════════════════════════════════════
// ADSO V3 — Seed Data: Driving License Categories
// Comprehensive European driving license categories (EU Directive 2006/126/EC)
// ═══════════════════════════════════════════════════════════

export const seedLicenseCategories = [
  {
    code: "AM",
    name: "Cyclomoteur",
    description:
      "Le permis AM autorise la conduite de cyclomoteurs à deux ou trois roues d'une vitesse maximale par construction ne dépassant pas 45 km/h et équipés d'un moteur d'une cylindrée maximale de 50 cm³ (moteur à combustion interne) ou d'une puissance maximale de 4 kW (moteur électrique). En France, il peut être obtenu dès 14 ans (catégorie AM) ou 15 ans selon les pays européens.",
    category: "motorcycle",
    minAge: 14,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Cyclomoteur à deux roues (50 cm³, max 45 km/h)",
      "Cyclomoteur à trois roues (50 cm³, max 45 km/h)",
      "Quadricycle léger à moteur (carrosserie, max 45 km/h)",
      "Scooter de cylindrée ≤ 50 cm³",
    ]),
    prerequisites: JSON.stringify([]),
    duration: 1,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Équilibre et maîtrise du véhicule à basse vitesse",
      "Manœuvre de freinage et d'arrêt",
      "Conduite en ligne droite et en courbe",
      "Respect du code de la route en circulation",
      "Observation et anticipation des dangers",
    ]),
    icon: "Bike",
  },
  {
    code: "A1",
    name: "Motocyclette légère",
    description:
      "Le permis A1 permet la conduite de motocyclettes légères d'une cylindrée maximale de 125 cm³ et d'une puissance maximale de 11 kW (15 ch), ainsi que d'un rapport puissance/poids ne dépassant pas 0,1 kW/kg. Ce permis est accessible dès 16 ans et constitue la première étape vers les permis moto supérieurs.",
    category: "motorcycle",
    minAge: 16,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Motocyclette légère (125 cm³, max 11 kW / 15 ch)",
      "Tricycle à moteur (max 15 kW)",
      "Scooter ≤ 125 cm³",
      "Motocyclette avec side-car (125 cm³, max 11 kW)",
    ]),
    prerequisites: JSON.stringify([]),
    duration: 3,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Manœuvre hors circulation : slalom, freinage, évitement",
      "Manœuvre de précision à basse vitesse",
      "Équilibre et stabilité du deux-roues",
      "Conduite en circulation urbaine et périurbaine",
      "Respect des priorités et des signalisations",
      "Anticipation et observation permanente",
      "Placement sur la chaussée et dans les virages",
    ]),
    icon: "Bike",
  },
  {
    code: "A2",
    name: "Motocyclette intermédiaire",
    description:
      "Le permis A2 autorise la conduite de motocyclettes d'une puissance maximale de 35 kW (47,5 ch) et dont le rapport puissance/poids ne dépasse pas 0,2 kW/kg. Il n'est pas dérivé d'un modèle de plus de 70 kW (95 ch). Ce permis, accessible dès 18 ans, permet une progression vers le permis A après 2 ans de détention.",
    category: "motorcycle",
    minAge: 18,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Motocyclette intermédiaire (max 35 kW / 47,5 ch)",
      "Motocyclette dont le rapport P/P ≤ 0,2 kW/kg",
      "Motocyclette non dérivée d'un modèle > 70 kW",
      "Tricycle à moteur (max 15 kW)",
    ]),
    prerequisites: JSON.stringify([]),
    duration: 4,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Manœuvre hors circulation : slalom, freinage d'urgence, évitement",
      "Manœuvre de précision à basse vitesse (parcours en huit)",
      "Conduite en circulation urbaine et sur voie rapide",
      "Placement correct dans les virages et les carrefours",
      "Respect des distances de sécurité",
      "Observation à 360° et anticipation",
      "Gestion des intersections et des priorités",
    ]),
    icon: "Bike",
  },
  {
    code: "A",
    name: "Motocyclette",
    description:
      "Le permis A est le permis moto complet, autorisant la conduite de toutes les motocyclettes sans limitation de puissance ni de cylindrée. Il est accessible dès 20 ans avec détention du permis A2 depuis au moins 2 ans (formation de 7h requise) ou directement dès 24 ans. C'est l'aboutissement de la progression moto européenne.",
    category: "motorcycle",
    minAge: 20,
    minAgeHeld: 20,
    vehicles: JSON.stringify([
      "Toutes motocyclettes sans limitation de puissance",
      "Motocyclettes de toute cylindrée (≥ 125 cm³)",
      "Tricycle à moteur (puissance > 15 kW)",
      "Motocyclette avec side-car (toute puissance)",
    ]),
    prerequisites: JSON.stringify(["A2"]),
    duration: 5,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Manœuvre hors circulation : slalom à allure soutenue, freinage d'urgence",
      "Manœuvre d'évitement à vitesse élevée",
      "Équilibre à basse vitesse et demi-tour",
      "Conduite en circulation complexe (urbain, périurbain, autoroute)",
      "Gestion des situations à risque : virages, intersections, dépassements",
      "Respect des distances de sécurité et adaptation de l'allure",
      "Observation systématique : rétroviseurs, angles morts,通信",
      "Maîtrise du véhicule dans toutes les conditions",
    ]),
    icon: "Bike",
  },
  {
    code: "B",
    name: "Véhicule particulier",
    description:
      "Le permis B est le permis automobile standard, autorisant la conduite de véhicules à moteur dont le poids total autorisé en charge (PTAC) ne dépasse pas 3 500 kg et comportant, outre le siège du conducteur, au plus 8 places assises. Il permet également de tracter une remorque de PTAC ≤ 750 kg. C'est le permis le plus courant en Europe.",
    category: "automobile",
    minAge: 18,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Véhicule automobile (PTAC ≤ 3 500 kg)",
      "Véhicule comportant ≤ 8 places assises + conducteur",
      "Remorque légère (PTAC ≤ 750 kg)",
      "Quadricycle lourd (sans épreuve pratique spécifique)",
      "Véhicule de collection (avec conditions d'âge du véhicule)",
    ]),
    prerequisites: JSON.stringify([]),
    duration: 6,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Manœuvres en circulation : démarrage, arrêt, marche arrière",
      "Stationnement (créneau, en épi, en bataille)",
      "Conduite en agglomération (vitesse, priorités, carrefours)",
      "Conduite hors agglomération (routes à double sens, virages)",
      "Conduite sur autoroute (insertion, dépassement, sortie)",
      "Freinage de sécurité",
      "Respect des signalisations (panneaux, feux, marquages)",
      "Indépendance de conduite et gestion de l'allure",
      "Respect du code de la route et des autres usagers",
      "Installation du conducteur et vérifications avant départ",
    ]),
    icon: "Car",
  },
  {
    code: "B96",
    name: "Ensemble véhicule + remorque (B96)",
    description:
      "L'extension B96 autorise la conduite de l'ensemble constitué d'un véhicule de catégorie B et d'une remorque dont le PTAC dépasse 750 kg, à condition que le PTAC total de l'ensemble ne dépasse pas 4 250 kg. Cette extension ne nécessite pas d'épreuve pratique supplémentaire, uniquement une formation de 7 heures avec un enseignant de la conduite.",
    category: "automobile",
    minAge: 18,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Véhicule catégorie B (PTAC ≤ 3 500 kg)",
      "Remorque (PTAC > 750 kg)",
      "Ensemble PTAC total ≤ 4 250 kg",
      "Caravane (PTAC > 750 kg, ensemble ≤ 4 250 kg)",
      "Remorque porte-voiture (dans la limite de 4 250 kg)",
    ]),
    prerequisites: JSON.stringify(["B"]),
    duration: 1,
    theoryExam: false,
    practicalExam: false,
    evaluationCriteria: JSON.stringify([
      "Attelage et dételage de la remorque",
      "Conduite avec remorque en ligne droite et en virage",
      "Manœuvres de stationnement avec remorque",
      "Gestion du freinage avec charge supplémentaire",
      "Conscience de l'encombrement et des angles morts augmentés",
      "Adaptation de la vitesse et des distances de sécurité",
      "Vérifications avant départ : feux, pneumatiques, attelage",
    ]),
    icon: "Car",
  },
  {
    code: "BE",
    name: "Véhicule avec remorque lourde",
    description:
      "Le permis BE autorise la conduite d'un ensemble constitué d'un véhicule tracteur de catégorie B et d'une remorque dont le PTAC dépasse 750 kg, lorsque le PTAC de l'ensemble dépasse 4 250 kg. Ce permis nécessite une épreuve pratique spécifique et permet de tracter des remorques de poids important comme des caravanes lourdes ou des remorques porte-bateaux.",
    category: "automobile",
    minAge: 18,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Véhicule catégorie B (PTAC ≤ 3 500 kg)",
      "Remorque lourde (PTAC > 750 kg)",
      "Ensemble PTAC total > 4 250 kg",
      "Caravane lourde",
      "Remorque porte-bateaux, remorque agricole",
    ]),
    prerequisites: JSON.stringify(["B"]),
    duration: 3,
    theoryExam: false,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Attelage et dételage de la remorque lourde",
      "Manœuvres en circulation avec remorque (virages, carrefours)",
      "Stationnement et manœuvres de recul avec remorque",
      "Conduite sur route et en agglomération avec ensemble long",
      "Gestion du freinage et de la stabilité en courbe",
      "Respect des limitations de vitesse applicables aux ensembles",
      "Vérifications techniques : frein de parking, feux, pneus, chaîne d'attelage",
      "Connaissance des règles spécifiques aux véhicules avec remorque",
    ]),
    icon: "Car",
  },
  {
    code: "C1",
    name: "Camion léger",
    description:
      "Le permis C1 autorise la conduite de véhicules à moteur dont le PTAC est compris entre 3 500 kg et 7 500 kg, comportant au plus 8 places assises outre le siège du conducteur. Il permet également de tracter une remorque de PTAC ≤ 750 kg. Ce permis est accessible dès 18 ans et répond aux besoins de transport de marchandises de poids moyen.",
    category: "heavy",
    minAge: 18,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Camion léger (PTAC entre 3 500 kg et 7 500 kg)",
      "Véhicule ≤ 8 places assises + conducteur (PTAC 3 500-7 500 kg)",
      "Remorque légère (PTAC ≤ 750 kg)",
      "Porteur de marchandises moyen",
      "Véhicule d'enlèvement d'ordures ménagères",
    ]),
    prerequisites: JSON.stringify(["B"]),
    duration: 4,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Vérifications techniques avant départ (niveau 1)",
      "Manœuvres : marche arrière en ligne droite, rangement en quai",
      "Conduite en agglomération et hors agglomération",
      "Gestion des carrefours, des virages et des ronds-points",
      "Freinage de sécurité avec véhicule chargé",
      "Respect des limitations de vitesse spécifiques aux poids lourds",
      "Connaissance des règles de circulation des véhicules lourds",
      "Observation et gestion des angles morts",
      "Gestion de la vitesse en descente (frein moteur)",
    ]),
    icon: "Truck",
  },
  {
    code: "C",
    name: "Camion lourd",
    description:
      "Le permis C autorise la conduite de véhicules à moteur dont le PTAC dépasse 3 500 kg et comportant au plus 8 places assises outre le siège du conducteur, avec une remorque de PTAC ≤ 750 kg. Ce permis est accessible dès 21 ans et est indispensable pour la conduite professionnelle de poids lourds. Il est souvent associé à la formation FIMO (Formation Initiale Minimale Obligatoire).",
    category: "heavy",
    minAge: 21,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Camion lourd (PTAC > 3 500 kg)",
      "Semi-remorque (tracteur seul, PTAC > 3 500 kg)",
      "Véhicule de transport de marchandises (PTAC > 7 500 kg)",
      "Remorque légère (PTAC ≤ 750 kg)",
      "Bétonnière, camion-benne, camion-grue",
    ]),
    prerequisites: JSON.stringify(["B"]),
    duration: 6,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Vérifications techniques approfondies avant départ (niveaux 1 et 2)",
      "Manœuvres de précision : marche arrière en courbe, rangement en quai",
      "Conduite sur tous types de voies (urbain, route, autoroute)",
      "Gestion des carrefours et des ronds-points avec véhicule long",
      "Freinage de sécurité et utilisation du frein moteur",
      "Respect des limitations de vitesse poids lourds (80-90 km/h)",
      "Connaissance de la réglementation sociale (temps de conduite et de repos)",
      "Gestion des angles morts et des virages à rayon réduit",
      "Chargement et arrimage de la marchandise",
      "Maîtrise de la chronotachygraphe",
    ]),
    icon: "Truck",
  },
  {
    code: "CE",
    name: "Camion avec remorque",
    description:
      "Le permis CE autorise la conduite d'ensembles de véhicules couplés composés d'un véhicule tracteur de catégorie C et d'une remorque ou semi-remorque dont le PTAC dépasse 750 kg. C'est le permis le plus complet pour le transport routier de marchandises, indispensable aux chauffeurs routiers professionnels.",
    category: "heavy",
    minAge: 21,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Ensemble tracteur + remorque (PTAC tracteur > 3 500 kg)",
      "Semi-remorque (tracteur C + semi-remorque > 750 kg)",
      "Train routier (porteur + remorque)",
      "Camion avec remorque de marchandises",
      "Véhicule articulé de transport de marchandises",
    ]),
    prerequisites: JSON.stringify(["C"]),
    duration: 3,
    theoryExam: false,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Attelage et dételage de la remorque ou semi-remorque",
      "Vérifications techniques complètes de l'ensemble",
      "Manœuvres de précision : marche arrière en courbe avec semi-remorque",
      "Rangement en quai de chargement/déchargement",
      "Conduite sur tous types de voies avec ensemble long",
      "Gestion des virages à rayon réduit avec train routier",
      "Freinage coordonné tracteur-remorque",
      "Stabilité et gestion du balancement en courbe",
      "Respect de la réglementation poids lourds",
    ]),
    icon: "Truck",
  },
  {
    code: "D1",
    name: "Minibus",
    description:
      "Le permis D1 autorise la conduite de véhicules à moteur conçus et aménagés pour le transport de 9 à 16 personnes passagers, outre le siège du conducteur. Il est accessible dès 21 ans et permet également de tracter une remorque de PTAC ≤ 750 kg. Ce permis est souvent requis pour le transport scolaire ou les navettes.",
    category: "heavy",
    minAge: 21,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Minibus (9 à 16 passagers + conducteur)",
      "Véhicule de transport de personnes (≤ 16 places)",
      "Remorque légère (PTAC ≤ 750 kg)",
      "Navette d'aéroport ou d'hôpital",
      "Véhicule de transport scolaire (≤ 16 places)",
    ]),
    prerequisites: JSON.stringify(["B"]),
    duration: 5,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Vérifications techniques avant départ (niveaux 1 et 2)",
      "Montée et descente des passagers en toute sécurité",
      "Conduite en agglomération avec passagers debout et assis",
      "Conduite sur route et autoroute",
      "Gestion des ouvertures de portes et des arrêts",
      "Freinage progressif et confort des passagers",
      "Respect des limitations de vitesse spécifiques aux transports de personnes",
      "Gestion des angles morts et des piétons autour du véhicule",
      "Connaissance de la réglementation du transport de personnes",
    ]),
    icon: "Bus",
  },
  {
    code: "D",
    name: "Autobus",
    description:
      "Le permis D autorise la conduite de véhicules à moteur conçus et aménagés pour le transport de plus de 16 personnes passagers, outre le siège du conducteur. Il est accessible dès 24 ans et constitue le permis le plus exigeant pour le transport de personnes. Il est indispensable pour les chauffeurs de bus urbains, interurbains et de longue distance.",
    category: "heavy",
    minAge: 24,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Autobus (> 16 passagers + conducteur)",
      "Bus urbain et périurbain",
      "Bus interurbain et de longue distance",
      "Autocar de tourisme",
      "Remorque légère (PTAC ≤ 750 kg)",
    ]),
    prerequisites: JSON.stringify(["B"]),
    duration: 6,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Vérifications techniques approfondies (niveaux 1 et 2)",
      "Gestion de la montée et de la descente des passagers",
      "Conduite en agglomération dense (arrêts fréquents, flux piétons)",
      "Conduite sur toutes voies y compris autoroutes",
      "Maîtrise du gabarit du bus dans les virages et carrefours",
      "Confort de conduite : freinage et accélération progressifs",
      "Gestion des portes et de la sécurité des passagers",
      "Respect des points d'arrêt et des itinéraires",
      "Connaissance de la réglementation sociale (temps de conduite et de repos)",
      "Gestion des situations d'urgence et de l'évacuation",
    ]),
    icon: "Bus",
  },
  {
    code: "DE",
    name: "Autobus avec remorque",
    description:
      "Le permis DE autorise la conduite d'ensembles de véhicules couplés composés d'un véhicule tracteur de catégorie D et d'une remorque dont le PTAC dépasse 750 kg. Ce permis est utilisé pour les autobus tractant une remorque de bagages ou d'équipements, notamment dans le transport de voyageurs longue distance ou les tournées théâtrales.",
    category: "heavy",
    minAge: 24,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Ensemble autobus + remorque (> 16 passagers, remorque > 750 kg)",
      "Autocar avec remorque de bagages",
      "Bus avec remorque d'équipements",
      "Véhicule de transport de personnes avec remorque",
    ]),
    prerequisites: JSON.stringify(["D"]),
    duration: 3,
    theoryExam: false,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Attelage et dételage de la remorque",
      "Vérifications techniques de l'ensemble bus-remorque",
      "Manœuvres de précision avec ensemble long",
      "Conduite sur tous types de voies",
      "Gestion du gabarit augmenté par la remorque",
      "Freinage coordonné bus-remorque",
      "Confort et sécurité des passagers",
      "Stabilité de l'ensemble dans les virages",
    ]),
    icon: "Bus",
  },
  {
    code: "F",
    name: "Tracteur agricole",
    description:
      "Le permis F autorise la conduite de tracteurs agricoles ou forestiers dont la vitesse maximale par construction ne dépasse pas 40 km/h, avec ou sans remorque ou matériel agricole attelé. Ce permis est accessible dès 16 ans et est principalement utilisé dans le secteur agricole et forestier pour les travaux des champs.",
    category: "special",
    minAge: 16,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Tracteur agricole (vitesse ≤ 40 km/h)",
      "Tracteur forestier (vitesse ≤ 40 km/h)",
      "Tracteur avec remorque agricole",
      "Machine agricole automotrice (vitesse ≤ 40 km/h)",
      "Équipement de travaux publics (vitesse ≤ 40 km/h)",
    ]),
    prerequisites: JSON.stringify([]),
    duration: 2,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Conduite du tracteur en ligne droite et en virage",
      "Manœuvres avec remorque ou matériel attelé",
      "Conduite sur chemins et routes rurales",
      "Traversée de carrefours et respect des priorités",
      "Vérifications de sécurité du tracteur et des attelages",
      "Connaissance de la signalisation applicable aux engins agricoles",
      "Manœuvres de chargement et de déchargement",
    ]),
    icon: "Tractor",
  },
  {
    code: "G",
    name: "Véhicules spéciaux",
    description:
      "La catégorie G autorise la conduite de véhicules spéciaux dont la vitesse maximale par construction ne dépasse pas 40 km/h, autres que ceux de la catégorie F. Cela comprend les tricycles à moteur, les quadricycles à moteur et les motoculteurs. L'âge minimum varie selon les pays (16 à 18 ans en Europe).",
    category: "special",
    minAge: 16,
    minAgeHeld: null,
    vehicles: JSON.stringify([
      "Tricycle à moteur (vitesse ≤ 40 km/h)",
      "Quadricycle à moteur lourd (vitesse ≤ 40 km/h)",
      "Motoculteur",
      "Machine automotrice spéciale",
      "Engin de manutention sur voie publique",
    ]),
    prerequisites: JSON.stringify([]),
    duration: 2,
    theoryExam: true,
    practicalExam: true,
    evaluationCriteria: JSON.stringify([
      "Conduite en ligne droite et en courbe",
      "Manœuvres de direction et de freinage",
      "Traversée de carrefours et d'intersections",
      "Respect des règles de circulation applicables",
      "Vérifications de sécurité du véhicule",
      "Connaissance des limitations et spécificités du véhicule",
    ]),
    icon: "Cog",
  },
];
