// ═══════════════════════════════════════════════════════════
// ADSO V3 — Seed Data: French Road Signs Database
// Comprehensive road sign data for France (code "FR")
// Based on the Convention de Vienne and French road signage regulations
// ═══════════════════════════════════════════════════════════

export const seedRoadSigns = [
  // ═══════════════════════════════════════════════════════════════
  // DANGER SIGNS (A1 - A31) — Triangles rouges bordés de blanc
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "turn",
    name: "Virage dangereux",
    description: "Panneau triangulaire à fond blanc bordé de rouge avec un symbole de virage en noir.",
    meaning: "Signale l'approche d'un virage dangereux. Le conducteur doit réduire sa vitesse et adapter sa trajectoire. Ce panneau ne précise pas le sens du virage et indique un virage généralement de plus de 90 degrés ou avec un rayon de courbure réduit.",
    useCase: "Placé avant un virage serré en rase campagne ou en zone urbaine où la visibilité est réduite, notamment en montagne ou sur routes sinueuses.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "turn",
    name: "Virage dangereux à gauche",
    description: "Panneau triangulaire avec un symbole de virage orienté vers la gauche.",
    meaning: "Signale l'approche d'un virage dangereux à gauche. Le conducteur doit ralentir suffisamment avant le virage, se placer sur la partie droite de la chaussée et veiller aux véhicules pouvant déborder dans le virage.",
    useCase: "Installé avant un virage à gauche dont le rayon est réduit, sur routes de campagne, en montagne ou en sortie de virage en épingles.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "turn",
    name: "Virage dangereux à droite",
    description: "Panneau triangulaire avec un symbole de virage orienté vers la droite.",
    meaning: "Signale l'approche d'un virage dangereux à droite. Le conducteur doit ralentir, rester sur le côté droit de sa voie et faire attention aux véhicules à gauche qui peuvent couper le virage.",
    useCase: "Placé avant un virage à gauche serré, notamment en montagne, sur routes sinueuses ou à proximité d'un virage aveugle.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "turn",
    name: "Série de virages dangereux",
    description: "Panneau triangulaire avec un symbole en forme de S représentant plusieurs virages successifs.",
    meaning: "Signale l'approche d'une succession de virages dangereux, généralement au moins trois virages rapprochés. Le conducteur doit adopter une allure modérée sur l'ensemble de la section et rester vigilant entre chaque virage.",
    useCase: "Installé en entrée de section sinueuse, routes de montagne, cols, et routes en lacets où plusieurs virages se succèdent sans possibilité de reprise.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_condition",
    name: "Chaussée rétrécie par la droite",
    description: "Panneau triangulaire montrant une chaussée dont la largeur diminue du côté droit.",
    meaning: "Signale que la chaussée va se rétrécir par la droite. Les véhicules circulant sur la voie de droite doivent céder le passage ou se serrer. Le conducteur doit ralentir et s'assurer de pouvoir maintenir sa trajectoire.",
    useCase: "Placé avant un pont étroit, un rétrécissement dû à des travaux, un pont de voie unique ou une zone où les accotements disparaissent.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_condition",
    name: "Chaussée rétrécie par la gauche",
    description: "Panneau triangulaire montrant une chaussée dont la largeur diminue du côté gauche.",
    meaning: "Signale que la chaussée va se rétrécir par la gauche. Les véhicules circulant sur la gauche doivent se serrer ou céder le passage. Le conducteur doit ralentir et rester dans sa voie.",
    useCase: "Installé avant un rétrécissement de la chaussée côté gauche, pont étroit, ou zone de travaux réduisant la largeur de la route.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_condition",
    name: "Chaussée rétrécie des deux côtés",
    description: "Panneau triangulaire montrant une chaussée qui se rétrécit simultanément des deux côtés.",
    meaning: "Signale que la chaussée va se rétrécir des deux côtés, laissant généralement une seule voie de circulation. Les conducteurs doivent ralentir et se concerter pour le passage en alternance si nécessaire.",
    useCase: "Placé avant un pont à voie unique, un passage étroit sous un ouvrage d'art, ou un rétrécissement significatif de la chaussée.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "priority",
    name: "Cédez le passage",
    description: "Panneau triangulaire pointe en bas avec un contour rouge épais et fond blanc. Pas de pictogramme intérieur.",
    meaning: "Oblige le conducteur de céder le passage aux véhicules circulant sur la route croisée ou engagée, même s'ils arrivent par la droite. L'arrêt n'est obligatoire que si un véhicule approche. Le conducteur doit ralentir et s'assurer qu'il peut traverser sans gêner personne.",
    useCase: "Installé à l'approche de toutes les intersections non régulées par des feux ou des stops, où la route croisée est prioritaire. Très courant en France en rase campagne et en agglomération.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "railway",
    name: "Passage à niveau sans barrière",
    description: "Panneau triangulaire représentant une locomotive de profil sur des rails.",
    meaning: "Signale l'approche d'un passage à niveau non gardé, sans barrières ni demi-barrières. Le conducteur doit ralentir, regarder des deux côtés et ne s'engager que s'il est certain qu'aucun train n'approche. L'arrêt n'est pas obligatoire sauf si un train est signalé, mais la plus grande prudence est requise.",
    useCase: "Placé à environ 50 mètres avant un passage à niveau non gardé sur routes secondaires ou rurales en France.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "railway",
    name: "Passage à niveau avec barrière",
    description: "Panneau triangulaire avec un symbole de barrière abaissée sur des rails.",
    meaning: "Signale l'approche d'un passage à niveau gardé, équipé de barrières ou demi-barrières. Malgré la présence de barrières, le conducteur ne doit jamais s'engager si les feux clignotent ou si une sonnerie retentit. Il doit s'arrêter devant la barrière si elle est fermée ou en cours de fermeture.",
    useCase: "Installé à environ 50 mètres avant un passage à niveau gardé, sur routes principales et secondaires.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "slope",
    name: "Pente dangereuse (descente)",
    description: "Panneau triangulaire avec une flèche orientée vers le bas et un pourcentage indiqué en dessous.",
    meaning: "Signale l'approche d'une descente forte dont le pourcentage est indiqué (par exemple 10 %). Le conducteur doit utiliser le frein moteur pour contrôler sa vitesse, éviter de freiner brutalement et rester maître de son véhicule. Les poids lourds doivent utiliser les voies de décélération si elles existent.",
    useCase: "Placé en début de descente forte sur routes de montagne, côtes raides et sorties d'autoroute en terrain accidenté.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "slope",
    name: "Pente dangereuse (montée)",
    description: "Panneau triangulaire avec une flèche orientée vers le haut et un pourcentage indiqué.",
    meaning: "Signale l'approche d'une montée forte dont le pourcentage est indiqué. Le conducteur doit adapter sa vitesse et son rapport de boîte avant la montée. Les véhicules lents doivent se serrer à droite pour permettre les dépassements.",
    useCase: "Installé en début de montée forte, notamment en montagne, sur routes de cols et sur voies rapides en terrain vallonné.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_works",
    name: "Travaux",
    description: "Panneau triangulaire avec un pictogramme représentant un personnage avec une pelle.",
    meaning: "Signale la présence de travaux sur la chaussée ou à proximité immédiate. Le conducteur doit ralentir, se conformer aux éventuelles déviations et rester attentif aux travailleurs, aux engins et aux modifications temporaires de la signalisation.",
    useCase: "Placé avant les chantiers routiers, zones de réfection, installation de réseaux ou tout intervention sur la voie publique.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_condition",
    name: "Danger isolé",
    description: "Panneau triangulaire avec un point d'exclamation noir au centre sur fond blanc.",
    meaning: "Signale un danger qui ne correspond à aucun des panneaux de danger spécifiques. Il attire l'attention du conducteur sur un risque particulier non codifié, comme un obstacle imprévu, une chaussée dégradée ou tout autre situation inhabituelle nécessitant de la prudence.",
    useCase: "Utilisé en complément ou en remplacement d'un panneau spécifique lorsque le danger ne correspond à aucune catégorie prévue par la réglementation.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "animal",
    name: "Animaux sauvages",
    description: "Panneau triangulaire avec un pictogramme de cerf au galop.",
    meaning: "Signale un risque de présence d'animaux sauvages sur la chaussée, notamment des cervidés. Le conducteur doit ralentir, rester très vigilant, surtout à l'aube et au crépuscule, et être prêt à s'arrêter. En cas de présence d'animaux, le conducteur doit ralentir et klaxonner pour les éloigner.",
    useCase: "Installé dans les zones forestières, parcs naturels, et régions où les collisions avec la faune sauvage sont fréquentes, notamment dans l'Est et le Centre de la France.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_condition",
    name: "Chutes de pierres",
    description: "Panneau triangulaire avec un pictogramme de pierres tombant d'une falaise.",
    meaning: "Signale un risque de chutes de pierres ou d'éboulements sur la chaussée. Le conducteur doit rouler à allure modérée, ne pas s'arrêter dans la zone concernée et rester vigilant face aux véhicules qui précèdent. En cas de chute effective, ne pas s'arrêter pour la photographier.",
    useCase: "Placé dans les zones montagneuses, gorges, falaises et coupures de route où le risque de chute de blocs rocheux est réel et documenté.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "weather",
    name: "Vent latéral",
    description: "Panneau triangulaire avec un pictogramme de souffle latéral déportant un véhicule.",
    meaning: "Signale un risque de vents latéraux violents pouvant déstabiliser les véhicules, en particulier les motos, les véhicules hauts et les poids lourds avec remorque. Le conducteur doit réduire sa vitesse, maintenir fermement le volant et anticiper les rafales, notamment à la sortie de tunnels ou de zones abritées.",
    useCase: "Installé sur les ponts, viaducs, zones côtières, plateaux exposés et sorties de tunnels où le vent est particulièrement fort et soudain.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "weather",
    name: "Zone inondable",
    description: "Panneau triangulaire avec un pictogramme de vagues sur la chaussée.",
    meaning: "Signale une zone régulièrement inondable ou à risque de submersion. Le conducteur doit être prudent, particulièrement en période de pluie ou de crue, et ne pas s'engager sur une chaussée recouverte d'eau. Il ne faut jamais traverser une zone inondée à pied ou en véhicule si la profondeur est incertaine.",
    useCase: "Placé dans les zones de plaine inondable, près des cours d'eau, en bordure de zones marécageuses et dans les secteurs historiquement touchés par les crues.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "weather",
    name: "Neige ou glace",
    description: "Panneau triangulaire avec un pictogramme de flocons de neige ou de glaçons.",
    meaning: "Signale une zone où la chaussée peut être recouverte de neige ou de verglas, notamment en hiver. Le conducteur doit rouler à allure très réduite, éviter les freinages brusques et les accélérations fortes, et équiper son véhicule de pneus hiver ou de chaînes si nécessaire.",
    useCase: "Installé sur les routes de montagne, cols, et zones exposées aux conditions hivernales difficiles, souvent en complément du panneau d'obligation de chaînes.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_condition",
    name: "Pont étroit",
    description: "Panneau triangulaire avec un pictogramme de pont dont la largeur est inférieure à celle de la route.",
    meaning: "Signale l'approche d'un pont dont la largeur est inférieure à la chaussée normale. Le passage peut être à sens unique avec alternance ou nécessiter une réduction de vitesse. Le conducteur doit ralentir et vérifier qu'aucun véhicule n'est engagé.",
    useCase: "Placé avant les ponts anciens ou à voie unique, notamment en zone rurale et sur le réseau secondaire.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_condition",
    name: "Zone aérodrome",
    description: "Panneau triangulaire avec un pictogramme d'avion au sol.",
    meaning: "Signale la proximité d'un aérodrome et le risque de survol bas d'aéronefs ou de présence d'avions sur la chaussée. Le conducteur doit rester attentif et respecter les éventuelles signalisations spécifiques liées à l'activité aéronautique.",
    useCase: "Installé à proximité des aérodromes, aéroclubs et zones où les routes croisent ou longent les pistes d'atterrissage.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "intersection",
    name: "Croisement de routes",
    description: "Panneau triangulaire avec un pictogramme de croisement de deux routes.",
    meaning: "Signale l'approche d'un carrefour où aucune route n'est prioritaire (croisement de routes de même importance). Le conducteur doit appliquer la règle de la priorité à droite et ralentir pour évaluer la circulation aux quatre branches du carrefour.",
    useCase: "Placé avant les carrefours non signalisés par des feux ou des panneaux de priorité, en rase campagne et en zone urbaine.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_condition",
    name: "Rapprochement du bord de la route",
    description: "Panneau triangulaire montrant une route dont le bord s'approche dangereusement.",
    meaning: "Signale que le bord de la chaussée est proche et potentiellement dangereux (talus, fossé, paroi rocheuse). Le conducteur doit se tenir au centre de la voie et ne pas trop se rapprocher du bord droit.",
    useCase: "Installé sur les routes de montagne sans accotement, les routes bordées de fossés profonds ou de falaises.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "road_condition",
    name: "Chaussée glissante",
    description: "Panneau triangulaire avec un pictogramme de voiture dérapant.",
    meaning: "Signale que la chaussée est particulièrement glissante (feuilles mortes, boue, huile, pavés mouillés). Le conducteur doit réduire sa vitesse, éviter les accélérations et freinages brusques, et augmenter les distances de sécurité.",
    useCase: "Placé sur les sections de route connues pour leur faible adhérence, notamment sous les arbres (feuilles mortes), sur pavés, et après des virages ou ponts.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "pedestrian",
    name: "Passage pour piétons",
    description: "Panneau triangulaire avec un pictogramme de piéton marchant.",
    meaning: "Signale l'approche d'un passage pour piétons. Le conducteur doit ralentir et être prêt à céder le passage aux piétons qui s'engagent ou sont sur le passage. Le dépassement est interdit à l'approche d'un passage piéton si un véhicule s'est arrêté pour laisser passer un piéton.",
    useCase: "Installé avant les passages piétons non signalés par des feux, en agglomération et en rase campagne, à proximité des écoles, commerces et zones résidentielles.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "children",
    name: "Enfants",
    description: "Panneau triangulaire avec un pictogramme de deux enfants marchant.",
    meaning: "Signale un lieu fréquenté par des enfants (écoles, aires de jeux, parcs). Le conducteur doit rouler à allure modérée et rester extrêmement vigilant, car les enfants peuvent se précipiter imprudemment sur la chaussée sans prévenir.",
    useCase: "Placé à proximité des écoles maternelles et primaires, crèches, aires de jeux et terrains de sport fréquentés par des enfants.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "danger",
    subcategory: "cyclist",
    name: "Cyclistes",
    description: "Panneau triangulaire avec un pictogramme de cycliste.",
    meaning: "Signale l'approche d'un lieu où des cyclistes peuvent traverser ou circuler. Le conducteur doit ralentir, vérifier ses angles morts et maintenir une distance latérale suffisante lors du dépassement (minimum 1 mètre en agglomération, 1,5 mètre hors agglomération).",
    useCase: "Installé à proximité des pistes cyclables, intersections fréquentées par les cyclistes, et zones de forte pratique du vélo.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  // ═══════════════════════════════════════════════════════════════
  // PROHIBITION SIGNS (B1 - B30) — Cercles rouges
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_entry",
    name: "Sens interdit",
    description: "Panneau rond à fond blanc avec un liseré rouge et un trait horizontal noir.",
    meaning: "Interdit l'accès à tous les véhicules dans le sens indiqué. Seuls les piétons et les cyclistes peuvent l'emprunter. Le panneau s'applique à partir de son emplacement jusqu'au prochain carrefour ou panneau de fin d'interdiction.",
    useCase: "Installé en entrée de sens unique, rues en sens interdit, zones piétonnes et voies à contre-sens pour empêcher la circulation dans la direction interdite.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_entry",
    name: "Interdiction de tourner à gauche",
    description: "Panneau rond avec une flèche noire tournant à gauche barrée de rouge.",
    meaning: "Interdit aux véhicules de tourner à gauche à l'intersection où le panneau est placé. Cette interdiction s'applique à partir du panneau jusqu'au prochain carrefour ou panneau de fin d'interdiction. Le demi-tour reste généralement possible sauf indication contraire.",
    useCase: "Installé aux intersections où le virage à gauche est dangereux, créerait des conflits de circulation ou est interdit pour des raisons de fluidité du trafic.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_entry",
    name: "Interdiction de tourner à droite",
    description: "Panneau rond avec une flèche noire tournant à droite barrée de rouge.",
    meaning: "Interdit aux véhicules de tourner à droite à l'intersection où le panneau est placé. Le demi-tour reste possible sauf panneau contraire. Le panneau s'applique jusqu'au prochain carrefour.",
    useCase: "Placé aux intersections où le virage à droite est interdit pour des raisons de sécurité ou de gestion du trafic.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_entry",
    name: "Interdiction de demi-tour",
    description: "Panneau rond avec un pictogramme de demi-tour barré de rouge.",
    meaning: "Interdit aux véhicules d'effectuer un demi-tour à l'endroit où le panneau est placé. Cette interdiction vise à éviter les manœuvres dangereuses sur les voies à trafic dense ou les routes à visibilité réduite.",
    useCase: "Installé sur les voies rapides, les ponts, les tunnels, les autoroutes et les carrefours à visibilité réduite où le demi-tour est dangereux.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_entry",
    name: "Accès interdit aux piétons",
    description: "Panneau rond avec un pictogramme de piéton barré de rouge.",
    meaning: "Interdit l'accès aux piétons sur la section de voie concernée. Les cyclistes sont également concernés s'ils poussent leur vélo à la main. Cette interdiction vise à protéger les piétons des véhicules sur des voies dangereuses.",
    useCase: "Placé en entrée d'autoroute, de tunnel, de pont et de voie rapide où la présence de piétons est interdite.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_entry",
    name: "Accès interdit aux véhicules à moteur",
    description: "Panneau rond avec un pictogramme de voiture barré de rouge.",
    meaning: "Interdit l'accès à tous les véhicules à moteur. Seuls les véhicules non motorisés (cyclistes, cavaliers, charrettes) et les piétons peuvent emprunter la voie. Les cyclomoteurs sont considérés comme des véhicules à moteur et sont donc interdits.",
    useCase: "Installé en entrée de zones piétonnes, pistes cyclables, allées de parcs et voies réservées aux modes doux.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_entry",
    name: "Accès interdit aux cyclistes",
    description: "Panneau rond avec un pictogramme de cycliste barré de rouge.",
    meaning: "Interdit l'accès aux cyclistes, y compris ceux poussant leur vélo à la main. Cette interdiction est utilisée pour protéger les cyclistes sur des voies dangereuses ou réserver certaines voies à d'autres usagers.",
    useCase: "Placé sur les autoroutes, voies rapides, tunnels, et sections de route où la circulation des vélos est interdite.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "weight_limit",
    name: "Limite de poids (tonnes)",
    description: "Panneau rond avec un chiffre (par exemple 3,5, 7,5, 12, 19, etc.) et l'inscription 't' barrés de rouge.",
    meaning: "Interdit l'accès aux véhicules dont le poids total autorisé en charge (PTAC) ou le poids total roulant autorisé (PTRA) dépasse le chiffre indiqué en tonnes. Les véhicules doivent détourner leur itinéraire s'ils dépassent la limite.",
    useCase: "Installé sur les ponts, routes étroites, zones résidentielles et voies dont la structure ne supporte pas les véhicules lourds.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "dimension_limit",
    name: "Limite de hauteur",
    description: "Panneau rond avec un chiffre et l'inscription 'm' barrés de rouge.",
    meaning: "Interdit l'accès aux véhicules dont la hauteur, y compris le chargement, dépasse le chiffre indiqué en mètres. Le conducteur doit vérifier la hauteur de son véhicule et de son chargement avant de s'engager sous un ouvrage d'art ou dans un parking.",
    useCase: "Placé avant les ponts, passages souterrains, parkings, tunnels et tout ouvrage avec une hauteur libre limitée.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "dimension_limit",
    name: "Limite de largeur",
    description: "Panneau rond avec un chiffre et l'inscription 'm' barrés de rouge.",
    meaning: "Interdit l'accès aux véhicules dont la largeur, y compris le chargement, dépasse le chiffre indiqué en mètres. Cette limitation vise à prévenir les blocages dans les passages étroits.",
    useCase: "Installé avant les passages étroits, ponts anciens, zones de travaux et ruelles où la largeur est insuffisante pour certains véhicules.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "speed_limit",
    name: "Vitesse maximale 30 km/h",
    description: "Panneau rond avec le chiffre 30 barré de rouge.",
    meaning: "Interdit de dépasser la vitesse de 30 km/h sur la section de route qui suit. Cette limitation est en vigueur jusqu'au prochain panneau de fin de limitation ou un nouveau panneau de vitesse différente. Le conducteur doit adapter sa vitesse aux conditions de circulation.",
    useCase: "Installé dans les zones 30, à proximité des écoles, dans les zones résidentielles, les centres-villes et les rues à forte fréquentation piétonne.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "speed_limit",
    name: "Vitesse maximale 50 km/h",
    description: "Panneau rond avec le chiffre 50 barré de rouge.",
    meaning: "Interdit de dépasser la vitesse de 50 km/h. C'est la vitesse par défaut en agglomération en France depuis 2018, sauf signalisation contraire. En cas de pluie ou autres précipitations, la vitesse maximale est de 80 km/h sur routes à double sens sans séparateur central et 110 km/h sur autoroute.",
    useCase: "Installé en agglomération comme vitesse réglementaire, sur routes à double sens et à l'approche de zones à risque.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "speed_limit",
    name: "Vitesse maximale 80 km/h",
    description: "Panneau rond avec le chiffre 80 barré de rouge.",
    meaning: "Interdit de dépasser la vitesse de 80 km/h. C'est la vitesse par défaut sur routes à double sens sans séparateur central en France (depuis 2018). Par temps de pluie, cette vitesse reste la limite maximale.",
    useCase: "Installé sur routes à double sens sans séparateur central, routes départementales et à l'entrée des agglomérations depuis la réduction de 90 à 80 km/h.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "speed_limit",
    name: "Vitesse maximale 90 km/h",
    description: "Panneau rond avec le chiffre 90 barré de rouge.",
    meaning: "Interdit de dépasser la vitesse de 90 km/h. Cette limite s'applique sur routes à chaussées séparées par un terre-plein central et par temps de pluie sur autoroutes. Elle était la vitesse par défaut sur routes à double sens avant la réforme de 2018.",
    useCase: "Installé sur routes à chaussées séparées, routes départementales à deux fois deux voies et par temps de pluie sur les autoroutes.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "speed_limit",
    name: "Vitesse maximale 110 km/h",
    description: "Panneau rond avec le chiffre 110 barré de rouge.",
    meaning: "Interdit de dépasser la vitesse de 110 km/h. C'est la vitesse par défaut sur autoroutes en temps de pluie et pour les jeunes conducteurs en permis probatoire. Par temps clair, la limite est de 130 km/h pour les conducteurs expérimentés.",
    useCase: "Installé sur autoroutes par temps de pluie, pour les jeunes conducteurs, et sur certaines voies rapides urbaines.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "speed_limit",
    name: "Vitesse maximale 130 km/h",
    description: "Panneau rond avec le chiffre 130 barré de rouge.",
    meaning: "Interdit de dépasser la vitesse de 130 km/h. C'est la vitesse maximale autorisée sur autoroute par temps clair en France pour les conducteurs titulaires de leur permis définitif depuis plus de 3 ans. Par temps de pluie ou pour les jeunes conducteurs, cette limite est abaissée à 110 km/h.",
    useCase: "Installé à l'entrée des autoroutes et voies assimilées par temps clair, comme vitesse de référence sur le réseau autoroutier français.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_horn",
    name: "Interdiction de klaxonner",
    description: "Panneau rond avec un pictogramme de klaxon barré de rouge.",
    meaning: "Interdit l'usage du klaxon ou de tout avertisseur sonore, sauf en cas de danger immédiat pour prévenir d'un accident. Cette interdiction vise à préserver la tranquillité des riverains, notamment la nuit et dans les zones résidentielles, hospitalières et scolaires.",
    useCase: "Placé à l'entrée des zones résidentielles, aux abords des hôpitaux, écoles, églises et dans les centres-villes historiques.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_parking",
    name: "Interdiction de stationnement",
    description: "Panneau rond bleu avec une barre rouge diagonale et un seul trait.",
    meaning: "Interdit le stationnement de tout véhicule sur le côté de la chaussée où le panneau est implanté. L'arrêt reste autorisé, mais le conducteur ne doit pas quitter son véhicule et doit le déplacer à la demande des forces de l'ordre. Le stationnement alterné demi-mensuel peut être indiqué par un panneau complémentaire.",
    useCase: "Installé sur les voies à fort trafic, à proximité des commerces, dans les zones où la circulation doit rester fluide, et en bordure de routes principales.",
    shape: "circle",
    colors: JSON.stringify(["red", "blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_stopping",
    name: "Interdiction de s'arrêter et de stationner",
    description: "Panneau rond bleu avec deux barres rouges croisées en diagonale.",
    meaning: "Interdit à la fois l'arrêt et le stationnement de tout véhicule du côté où le panneau est implanté. Aucun véhicule ne doit s'arrêter, même brièvement, sauf en cas de force majeure (accident, panne, ordre des forces de l'ordre). Les livraisons et les montées/descentes de passagers sont également interdites.",
    useCase: "Placé devant les passages piétons, aux carrefours, à proximité des feux, sur les voies rapides, tunnels, et partout où un arrêt créerait un danger ou une gêne.",
    shape: "circle",
    colors: JSON.stringify(["red", "blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "stop",
    name: "Stop",
    description: "Panneau octogonal rouge avec l'inscription 'STOP' en blanc.",
    meaning: "Oblige le conducteur à marquer un arrêt complet avant la ligne d'arrêt (ou le bord de la chaussée s'il n'y a pas de ligne). Le conducteur doit s'assurer qu'aucun véhicule ne circule sur la route prioritaire avant de s'engager. Même en l'absence de circulation, l'arrêt complet est obligatoire. Le non-respect de l'arrêt est un délit passible d'un retrait de 4 points et d'une amende.",
    useCase: "Installé aux intersections où la visibilité est réduite, aux carrefours dangereux, à l'entrée de routes prioritaires et aux passages à niveau avec barrières en France.",
    shape: "octagon",
    colors: JSON.stringify(["red", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_entry",
    name: "Circulation à sens unique",
    description: "Panneau rectangulaire bleu avec une flèche blanche directionnelle.",
    meaning: "Indique que la circulation est à sens unique dans le sens de la flèche. Le dépassement par un véhicule venant en sens inverse constitue une infraction grave au code de la route. Tous les véhicules doivent circuler dans le sens indiqué.",
    useCase: "Installé dans les rues à sens unique des centres-villes, zones résidentielles, rues étroites et pour optimiser la fluidité de la circulation urbaine.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "prohibition",
    subcategory: "no_overtaking",
    name: "Interdiction de dépasser",
    description: "Panneau rond avec deux véhicules dont le rouge est barré de rouge (un rouge dépassant l'autre).",
    meaning: "Interdit le dépassement de tous les véhicules à moteur par tous les véhicules à moteur, sauf les cycles, les cyclomoteurs et les deux-roues sans side-car qui peuvent dépasser si la manœuvre est sans danger. Les véhicules lents doivent se serrer à droite pour ne pas gêner la circulation.",
    useCase: "Installé dans les virages à visibilité réduite, les côtes, les zones de travaux, les ponts étroits et les routes à double sens sans visibilité suffisante pour dépasser.",
    shape: "circle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  // ═══════════════════════════════════════════════════════════════
  // OBLIGATION SIGNS (B30 - B50) — Cercles bleus
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "direction",
    name: "Sens obligatoire : tout droit",
    description: "Panneau rond bleu avec une flèche blanche pointant vers le haut.",
    meaning: "Oblige les véhicules à continuer tout droit. Tourner à gauche ou à droite est interdit. Le panneau s'applique à l'intersection immédiate qui suit.",
    useCase: "Installé aux carrefours, giratoires et intersections où le trafic doit impérativement continuer en ligne droite.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "direction",
    name: "Sens obligatoire : à droite",
    description: "Panneau rond bleu avec une flèche blanche courbée vers la droite.",
    meaning: "Oblige les véhicules à tourner à droite à l'intersection. Continuer tout droit ou tourner à gauche est interdit. Ce panneau impose une direction unique.",
    useCase: "Placé aux carrefours, sorties d'autoroute, giratoires et intersections où seule la direction droite est autorisée.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "direction",
    name: "Sens obligatoire : à gauche",
    description: "Panneau rond bleu avec une flèche blanche courbée vers la gauche.",
    meaning: "Oblige les véhicules à tourner à gauche à l'intersection. Continuer tout droit ou tourner à droite est interdit.",
    useCase: "Installé aux carrefours et intersections où seule la direction gauche est possible ou autorisée.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "direction",
    name: "Contournement obligatoire par la droite",
    description: "Panneau rond bleu avec une flèche blanche contournant un obstacle par la droite.",
    meaning: "Oblige les véhicules à contourner l'obstacle (îlot, travaux, refuge) par la droite. Le contournement par la gauche est strictement interdit. Ce panneau est souvent utilisé dans les carrefours à sens giratoire et autour d'îlots directionnels.",
    useCase: "Installé autour des îlots, dans les carrefours complexes, et pour guider le trafic autour des obstacles ou travaux.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "direction",
    name: "Contournement obligatoire par la gauche",
    description: "Panneau rond bleu avec une flèche blanche contournant un obstacle par la gauche.",
    meaning: "Oblige les véhicules à contourner l'obstacle par la gauche. Le contournement par la droite est interdit. Utilisé dans les configurations où seul le côté gauche est praticable.",
    useCase: "Placé autour des îlets, refuges centraux et obstacles où le contournement par la droite est impossible ou dangereux.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "speed_limit",
    name: "Vitesse minimale",
    description: "Panneau rond bleu avec un chiffre et l'inscription 'km/h' en blanc.",
    meaning: "Oblige les véhicules à circuler au moins à la vitesse indiquée. Ce panneau ne s'applique qu'aux véhicules à moteur. Il est toujours accompagné d'un panneau de fin de vitesse minimale. Il ne dispense pas de l'obligation de modérer l'allure en cas de circonstances dangereuses.",
    useCase: "Installé sur les voies rapides, autoroutes, tunnels et ponts où une vitesse trop faible pourrait créer un danger pour la circulation.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "equipment",
    name: "Allumage des feux obligatoire",
    description: "Panneau rond bleu avec un pictogramme de phare allumé.",
    meaning: "Oblige tous les véhicules à circuler avec les feux de croisement allumés en permanence, même en plein jour. Le non-respect de cette obligation est puni d'une amende forfaitaire. Cette obligation a remplacé la recommandation de l'allumage des feux de jour.",
    useCase: "Installé à l'entrée des tunnels, sections d'autoroute, routes à forte circulation, et à l'approche de zones à visibilité réduite.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "equipment",
    name: "Chaînes à neige obligatoires",
    description: "Panneau rond bleu avec un pictogramme de pneu avec chaîne.",
    meaning: "Oblige les véhicules à être équipés de chaînes à neige sur au moins deux roues motrices pour pouvoir circuler. En l'absence de chaînes, les pneus hiver ne suffisent pas à répondre à cette obligation. Cette obligation s'applique en période hivernale ou lorsque les conditions l'exigent.",
    useCase: "Installé sur les routes de montagne, cols, et passages exposés aux chutes de neige, généralement en complément du panneau de danger 'Neige ou glace'.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "cycle_lane",
    name: "Piste cyclable obligatoire",
    description: "Panneau rond bleu avec un pictogramme de bicyclette en blanc.",
    meaning: "Oblige les cyclistes et les cyclomotoristes à emprunter la piste cyclable aménagée. Ils ne peuvent plus circuler sur la chaussée adjacente. Les autres véhicules ne sont pas autorisés à circuler sur la piste cyclable.",
    useCase: "Installé en début de piste cyclable équipée d'un revêtement différencié de la chaussée, séparée ou non par un marquage.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "cycle_lane",
    name: "Bande cyclable obligatoire",
    description: "Panneau carré bleu avec un pictogramme de bicyclette sur fond blanc, délimité par deux lignes blanches discontinues.",
    meaning: "Oblige les cyclistes et les cyclomotoristes à emprunter la bande cyclable délimitée par le marquage au sol. Les autres véhicules ne doivent pas circuler sur la bande cyclable mais peuvent la traverser pour tourner à droite si nécessaire.",
    useCase: "Installé le long des voies urbaines où une bande cyclable a été aménagée sur le côté droit de la chaussée.",
    shape: "square",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "equipment",
    name: "Pneus cloutés autorisés",
    description: "Panneau rond bleu avec un pictogramme de pneu avec clous.",
    meaning: "Indique que la circulation avec des pneus cloutés est autorisée sur la section de route concernée. Les pneus cloutés ne sont autorisés en France que sur certains tronçons et à certaines périodes de l'année. La vitesse maximale est généralement limitée à 90 km/h.",
    useCase: "Installé sur les itinéraires autorisés pour la circulation avec pneus cloutés, en montagne et dans les régions à forte densité de neige.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "direction",
    name: "Contournement obligatoire (droite ou gauche)",
    description: "Panneau rond bleu avec une flèche blanche pouvant contourner par la droite ou par la gauche.",
    meaning: "Oblige les véhicules à contourner l'obstacle (îlot central, îlet directionnel) soit par la droite, soit par la gauche, au choix du conducteur. Le franchissement direct de l'îlot est interdit.",
    useCase: "Installé dans les carrefours à îlots centraux et les giratoires où le contournement peut se faire par les deux côtés.",
    shape: "circle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "obligation",
    subcategory: "path",
    name: "Voie réservée aux bus",
    description: "Panneau carré ou rectangulaire bleu avec l'inscription 'BUS' en blanc.",
    meaning: "Réserve la voie ou le couloir aux bus et, selon les cas, aux taxis et aux cyclistes. Les autres véhicules ne sont pas autorisés à circuler sur cette voie sauf pour la traverser afin de tourner. Le non-respect de cette interdiction est verbalisable.",
    useCase: "Installé sur les voies urbaines à forte fréquentation de transports en commun pour leur réserver un couloir de circulation prioritaire.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  // ═══════════════════════════════════════════════════════════════
  // PRIORITY SIGNS — Signalisation de priorité
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "priority",
    subcategory: null,
    name: "Route prioritaire",
    description: "Panneau carré jaune avec un losange blanc au centre, bordé de pointillés.",
    meaning: "Indique que les usagers circulent sur une route prioritaire. Ils bénéficient de la priorité à tous les carrefours rencontrés, sauf indication contraire par un panneau 'Cédez le passage' ou 'Stop' implanté sur leur route. Ce panneau peut être répété après chaque intersection.",
    useCase: "Installé en début de route prioritaire, généralement sur les routes principales et nationales, et répété après chaque carrefour pour rappeler le bénéfice de la priorité.",
    shape: "diamond",
    colors: JSON.stringify(["yellow", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "priority",
    subcategory: null,
    name: "Fin de route prioritaire",
    description: "Panneau carré blanc barré de noir avec un losange hachuré.",
    meaning: "Indique la fin de la route prioritaire. À partir de ce panneau, le conducteur perd le bénéfice de la priorité automatique et doit se conformer aux règles de priorité à droite ou aux signalisations spécifiques à chaque carrefour rencontré.",
    useCase: "Installé à la fin d'une route prioritaire, avant un carrefour à priorité à droite ou une zone où la priorité n'est plus assurée.",
    shape: "square",
    colors: JSON.stringify(["white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "priority",
    subcategory: null,
    name: "Cédez le passage (priorité)",
    description: "Panneau triangulaire inversé pointe en bas, bordé de rouge, sans pictogramme intérieur.",
    meaning: "Oblige le conducteur à céder le passage aux véhicules circulant sur la route prioritaire croisée. L'arrêt n'est obligatoire que si un véhicule approche. Ce panneau peut être accompagné d'un panneau de pré-signalisation (triangulaire) implanté plus en amont.",
    useCase: "Installé à l'approche de chaque carrefour entre une route non prioritaire et une route prioritaire, en rase campagne principalement.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "priority",
    subcategory: null,
    name: "Route à caractéristique prioritaire",
    description: "Panneau carré jaune bordé de pointillés avec un losange blanc, identique au panneau de route prioritaire mais implanté différemment.",
    meaning: "Indique une route prioritaire avec des caractéristiques particulières (largeur, profil, trafic) nécessitant une attention particulière. Le bénéfice de la priorité reste identique au panneau de route prioritaire classique, mais ce panneau attire l'attention sur la nature de la route.",
    useCase: "Installé sur les routes à grande circulation, les routes à caractéristiques particulières et les voies où la priorité est renforcée par la signalisation.",
    shape: "diamond",
    colors: JSON.stringify(["yellow", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "priority",
    subcategory: null,
    name: "Priorité à droite",
    description: "Absence de panneau de priorité : la règle générale de la priorité à droite s'applique.",
    meaning: "Dans les carrefours non signalés par des panneaux de priorité ou des feux, le conducteur doit céder le passage aux véhicules venant de sa droite. C'est la règle générale du code de la route français. Même un véhicule arrivant d'une route secondaire a la priorité s'il vient de la droite.",
    useCase: "S'applique par défaut à tous les carrefours non régulés par une signalisation spécifique (feux, stop, cédez-le-passage, route prioritaire), principalement en agglomération et dans les zones résidentielles.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "priority",
    subcategory: null,
    name: "Priorité aux véhicules des transports en commun",
    description: "Panneau triangulaire avec un pictogramme de bus.",
    meaning: "Indique que les bus des transports en commun bénéficient de la priorité de passage aux carrefours. Les autres véhicules doivent leur céder le passage lorsqu'ils s'engagent dans l'intersection.",
    useCase: "Installé aux carrefours situés sur des lignes de bus à fort trafic, dans les zones de transport en commun en site propre.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "priority",
    subcategory: null,
    name: "Priorité ponctuelle dans le carrefour à sens giratoire",
    description: "Panneau triangulaire inversé pointe en bas avec un pictogramme de giratoire, entouré de flèches.",
    meaning: "Indique que le conducteur doit céder le passage aux véhicules circulant déjà dans le giratoire avant de s'y engager. La priorité à droite ne s'applique pas à l'intérieur du giratoire : les véhicules déjà engagés sont prioritaires.",
    useCase: "Placé à l'entrée de chaque branche d'un carrefour à sens giratoire pour rappeler la règle de priorité à l'entrée du giratoire.",
    shape: "triangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "priority",
    subcategory: null,
    name: "Priorité ponctuelle (temporaire)",
    description: "Panneau de cédez-le-passage de forme triangulaire avec fond jaune.",
    meaning: "Version temporaire du panneau cédez-le-passage, utilisée lors de travaux ou de modifications temporaires de la signalisation. Le conducteur doit céder le passage aux véhicules circulant sur la voie prioritaire.",
    useCase: "Utilisé lors de travaux, déviations temporaires ou modifications de la signalisation de priorité.",
    shape: "triangle",
    colors: JSON.stringify(["yellow", "black"]),
    questions: null,
  },
  // ═══════════════════════════════════════════════════════════════
  // DIRECTION SIGNS — Signalisation directionnelle
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "advance",
    name: "Présignal de direction",
    description: "Panneau rectangulaire blanc bordé de vert avec le nom des directions en noir, implanté en amont du carrefour.",
    meaning: "Indique à l'avance les directions possibles au prochain carrefour. Le conducteur peut ainsi se préparer à changer de voie et à adopter la trajectoire appropriée. Les inscriptions en vert concernent les autoroutes et voies rapides, en blanc les routes nationales et départementales, en jaune les directions locales.",
    useCase: "Implanté environ 1 à 2 km avant un carrefour important, une sortie d'autoroute ou un échangeur, pour permettre au conducteur de se placer dans la bonne voie.",
    shape: "rectangle",
    colors: JSON.stringify(["green", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "confirmation",
    name: "Panneau de direction",
    description: "Panneau rectangulaire blanc ou vert avec les noms de destinations et flèches directionnelles.",
    meaning: "Indique la direction à suivre pour atteindre les destinations mentionnées. Ce panneau est placé à l'entrée du carrefour et oriente le conducteur vers la bonne route. Plusieurs destinations peuvent être regroupées sur un même panneau avec des flèches directionnelles.",
    useCase: "Installé au niveau des carrefours, entrées de giratoires, sorties d'autoroute et bifurcations pour indiquer les directions.",
    shape: "rectangle",
    colors: JSON.stringify(["green", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "highway",
    name: "Sortie d'autoroute",
    description: "Panneau rectangulaire bleu avec le numéro de sortie et les directions.",
    meaning: "Indique l'approche d'une sortie d'autoroute avec son numéro et les destinations accessibles. Le conducteur doit se déporter progressivement vers la voie de droite pour préparer sa sortie. Le panneau de présignalisation est généralement répété à 1 000 m, 500 m et 200 m de la sortie.",
    useCase: "Implanté sur autoroute à 1 000 m, 500 m et à l'entrée de chaque bretelle de sortie pour guider les conducteurs vers leur destination.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "highway",
    name: "Indication de direction (flèche directionnelle)",
    description: "Panneau rectangulaire avec une ou plusieurs flèches blanches sur fond coloré indiquant la direction.",
    meaning: "Oriente le conducteur vers la direction indiquée par la flèche. Les flèches peuvent être obliques (sortie), horizontales (continuation) ou courbes (changement de direction). Le conducteur doit suivre la direction correspondant à sa destination.",
    useCase: "Placé aux carrefours, giratoires, et sur les voies d'insertion et de sortie pour guider les conducteurs.",
    shape: "arrow",
    colors: JSON.stringify(["green", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "confirmation",
    name: "Panneau de confirmation de direction",
    description: "Panneau rectangulaire blanc avec les noms de villes et distances.",
    meaning: "Confirme au conducteur qu'il se dirige vers la bonne destination et indique la distance restante. Ce panneau est généralement implanté après un carrefour important pour rassurer le conducteur sur son itinéraire.",
    useCase: "Installé après les carrefours et les changements de direction pour confirmer l'itinéraire suivi et donner les distances.",
    shape: "rectangle",
    colors: JSON.stringify(["white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "local",
    name: "Indication de direction locale",
    description: "Panneau rectangulaire jaune avec les noms de lieux et directions.",
    meaning: "Indique les directions vers des lieux d'intérêt local : communes, sites touristiques, équipements publics. Le fond jaune distingue ces indications des directions principales (blanc) et des autoroutes (vert/bleu).",
    useCase: "Installé en agglomération et en rase campagne pour signaler les directions vers les villages, lieux-dits, sites touristiques et équipements locaux.",
    shape: "rectangle",
    colors: JSON.stringify(["yellow", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "highway",
    name: "Indication d'autoroute",
    description: "Panneau rectangulaire bleu avec le numéro de l'autoroute et les directions principales.",
    meaning: "Indique l'entrée d'une autoroute ou la direction vers une autoroute. Le numéro de l'autoroute est inscrit dans un écu. En France, les autoroutes sont identifiées par la lettre A suivie d'un numéro (A1, A6, A10, etc.).",
    useCase: "Placé à l'entrée des autoroutes et sur les voies d'insertion pour identifier l'autoroute et ses directions principales.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "confirmation",
    name: "Panneau d'identification de route",
    description: "Panneau rectangulaire avec le numéro de la route (D, N, RN, A) sur fond coloré.",
    meaning: "Identifie le numéro de la route sur laquelle circule le conducteur. Les routes nationales (N) ont un fond rouge, les routes départementales (D) un fond jaune, et les autoroutes (A) un fond bleu. Ce panneau permet de vérifier son itinéraire.",
    useCase: "Implanté à intervalles réguliers sur le réseau routier pour permettre aux conducteurs de s'assurer qu'ils circulent sur la bonne route.",
    shape: "rectangle",
    colors: JSON.stringify(["red", "white", "yellow"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "advance",
    name: "Panneau de présignalisation de sortie",
    description: "Panneau rectangulaire bleu avec la sortie numéro et les destinations, implanté en amont.",
    meaning: "Avertit à l'avance de la proximité d'une sortie d'autoroute. Le conducteur doit anticiper son ralentissement et son positionnement sur la voie de droite. Le panneau est généralement répété à plusieurs distances de la sortie.",
    useCase: "Placé à 2 km, 1 km et 500 m avant une sortie d'autoroute pour permettre au conducteur de se préparer.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "direction",
    subcategory: "highway",
    name: "Dernier panneau avant sortie",
    description: "Panneau rectangulaire bleu avec une flèche oblique et le nom de la sortie.",
    meaning: "Dernière indication avant la bretelle de sortie d'autoroute. Le conducteur doit obligatoirement se reporter sur la voie de droite s'il souhaite sortir. Ce panneau est généralement implanté à environ 200 m de la sortie.",
    useCase: "Installé juste avant la bretelle de sortie d'autoroute, à environ 200 m du début de la décélération.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  // ═══════════════════════════════════════════════════════════════
  // INFORMATION SIGNS — Signalisation d'information
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "information",
    subcategory: "parking",
    name: "Parking",
    description: "Panneau carré bleu avec un 'P' blanc au centre.",
    meaning: "Indique un emplacement de stationnement pour véhicules. Le stationnement est généralement gratuit sauf indication contraire. Le panneau peut être complété par un panneau localisant le type de stationnement (handicapé, courte durée, etc.). Le stationnement doit s'effectuer dans les emplacements marqués.",
    useCase: "Installé à l'entrée des parkings publics, aires de stationnement, et zones de stationnement autorisé en agglomération.",
    shape: "square",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: "medical",
    name: "Hôpital",
    description: "Panneau carré blanc avec un pictogramme de croix rouge sur fond blanc, parfois complété par une indication de distance.",
    meaning: "Indique la proximité d'un hôpital ou d'un établissement de soins d'urgence. Le pictogramme de la croix rouge est réservé aux services médicaux d'urgence. Le conducteur doit adapter sa conduite et être prêt à céder le passage aux véhicules d'urgence.",
    useCase: "Placé à proximité des hôpitaux, cliniques, et centres de soins d'urgence pour guider les patients et les véhicules de secours.",
    shape: "square",
    colors: JSON.stringify(["white", "red"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: "education",
    name: "École",
    description: "Panneau rectangulaire représentant deux enfants avec un livre.",
    meaning: "Signale la proximité d'un établissement scolaire (école maternelle, primaire, collège, lycée). Le conducteur doit redoubler de prudence, réduire sa vitesse et être attentif aux enfants qui peuvent traverser imprudemment la chaussée, surtout aux heures d'entrée et de sortie des classes.",
    useCase: "Installé à proximité des établissements scolaires, aux abords des zones de dépôt et de reprise des élèves.",
    shape: "rectangle",
    colors: JSON.stringify(["white", "blue", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: "zone",
    name: "Zone résidentielle",
    description: "Panneau rectangulaire bleu avec un pictogramme de maison, d'enfant et d'arbre.",
    meaning: "Signale l'entrée d'une zone résidentielle où la priorité à droite s'applique à tous les carrefours. La vitesse est limitée à 20 km/h (sauf indication contraire). Les piétons ont le droit d'utiliser la totalité de la chaussée. Le stationnement est réglementé par des panneaux locaux.",
    useCase: "Installé à l'entrée des zones résidentielles, lotissements et quartiers d'habitation où la circulation doit être apaisée.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: "pedestrian",
    name: "Zone piétonne",
    description: "Panneau rectangulaire bleu avec un pictogramme de piéton.",
    meaning: "Signale l'entrée d'une zone réservée exclusivement aux piétons. L'accès des véhicules est généralement interdit sauf dérogation (livraisons, riverains). Les cyclistes peuvent circuler à allure du pas. Les piétons ont la priorité absolue dans cette zone.",
    useCase: "Installé à l'entrée des zones piétonnes des centres-villes, rues commerçantes et places publiques.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: "cycle",
    name: "Piste cyclable (information)",
    description: "Panneau carré bleu avec un pictogramme de bicyclette, sans caractère obligatoire.",
    meaning: "Indique l'existence d'une piste cyclable à proximité. Contrairement au panneau d'obligation, ce panneau est informatif et n'oblige pas les cyclistes à l'emprunter. Les cyclistes peuvent choisir entre la piste et la chaussée.",
    useCase: "Installé en début de piste cyclable non obligatoire pour en indiquer l'existence aux cyclistes.",
    shape: "square",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: "zone",
    name: "Zone 30",
    description: "Panneau rectangulaire blanc avec un rond rouge contenant le chiffre 30, le tout sur fond blanc avec des inscriptions complémentaires.",
    meaning: "Signale l'entrée d'une zone où la vitesse maximale est limitée à 30 km/h sur l'ensemble de la zone. Le panneau d'entrée est généralement accompagné du panneau de fin de zone 30 en sortie. La priorité à droite s'applique à tous les carrefours de la zone sauf signalisation contraire.",
    useCase: "Installé à l'entrée des zones 30 dans les centres-villes, quartiers résidentiels, à proximité des écoles et des zones commerçantes.",
    shape: "rectangle",
    colors: JSON.stringify(["white", "red", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: "zone",
    name: "Zone de rencontre",
    description: "Panneau rectangulaire blanc avec un pictogramme de piéton, cycliste et voiture.",
    meaning: "Signale l'entrée d'une zone de rencontre où tous les usagers (piétons, cyclistes, automobilistes) partagent le même espace. La vitesse est limitée à 20 km/h. Les piétons ont le droit d'utiliser toute la largeur de la chaussée et peuvent la traverser dans toutes les directions. Le stationnement est interdit sauf emplacements marqués.",
    useCase: "Installé à l'entrée des zones de rencontre dans les centres-villes historiques, places et rues à forte mixité de circulation.",
    shape: "rectangle",
    colors: JSON.stringify(["white", "blue", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: "highway",
    name: "Autoroute",
    description: "Panneau rectangulaire bleu avec un pictogramme de pont autoroutier.",
    meaning: "Indique l'entrée d'une autoroute. Les règles spécifiques de l'autoroute s'appliquent : obligation de circuler sur la voie de droite, interdiction de faire demi-tour, de s'arrêter et de marche arrière. Les véhicules lents ne peuvent pas emprunter l'autoroute. La vitesse maximale est de 130 km/h par temps sec.",
    useCase: "Placé à l'entrée de chaque autoroute, sur la voie d'accélération, pour signaler le début de la section autoroutière.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: null,
    name: "Fin d'autoroute",
    description: "Panneau identique au panneau d'autoroute mais barré d'une ligne rouge diagonale.",
    meaning: "Indique la fin de la section autoroutière. Les règles spécifiques de l'autoroute ne s'appliquent plus. Les limitations de vitesse reprennent celles de la route ordinaire. Le conducteur doit adapter sa vitesse et son comportement.",
    useCase: "Installé à la fin d'une autoroute, avant la reprise du réseau routier normal.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white", "red"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: null,
    name: "Sens unique",
    description: "Panneau rectangulaire bleu avec une flèche blanche directionnelle.",
    meaning: "Indique que la voie est à sens unique dans le sens de la flèche. Tous les véhicules doivent circuler dans le sens indiqué. Le non-respect de cette signalisation constitue une infraction grave pouvant entraîner un retrait de 4 points sur le permis de conduire.",
    useCase: "Placé en entrée et à intervalles réguliers dans les rues à sens unique pour rappeler la direction de circulation.",
    shape: "rectangle",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "information",
    subcategory: "zone",
    name: "Fin de zone 30",
    description: "Panneau rectangulaire blanc avec le même panneau que l'entrée de zone 30 mais barré d'une ligne rouge diagonale.",
    meaning: "Indique la fin de la zone 30 et le retour aux règles de circulation normales de la voie concernée. La limitation de vitesse redevient celle de la voie (50 km/h en agglomération, 80 ou 90 km/h hors agglomération).",
    useCase: "Installé à la sortie d'une zone 30 pour signaler la fin de la limitation spécifique à 30 km/h.",
    shape: "rectangle",
    colors: JSON.stringify(["white", "red", "black"]),
    questions: null,
  },
  // ═══════════════════════════════════════════════════════════════
  // SERVICE SIGNS — Signalisation de services
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "service",
    subcategory: "fuel",
    name: "Station-service",
    description: "Panneau carré bleu avec un pictogramme de pompe à essence.",
    meaning: "Indique la proximité d'une station-service proposant du carburant (essence, diesel, GPL, électrique). Les stations-service sur autoroute sont indiquées par un panneau spécifique avec la distance en kilomètres.",
    useCase: "Placé sur les routes, autoroutes et aires de repos pour signaler la présence d'une station-service.",
    shape: "square",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "service",
    subcategory: "accommodation",
    name: "Hôtel",
    description: "Panneau carré bleu avec un pictogramme de lit.",
    meaning: "Indique la proximité d'un établissement d'hébergement (hôtel, auberge, motel). Ce panneau est souvent regroupé avec d'autres pictogrammes de services sur un même support.",
    useCase: "Installé sur les routes touristiques, autoroutes et à proximité des zones d'hébergement pour guider les voyageurs.",
    shape: "square",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "service",
    subcategory: "food",
    name: "Restaurant",
    description: "Panneau carré bleu avec un pictogramme de couverts (fourchette et couteau).",
    meaning: "Indique la proximité d'un restaurant ou d'un lieu de restauration. Le panneau ne donne pas d'information sur les horaires d'ouverture ou le type de cuisine proposé.",
    useCase: "Placé sur les routes principales, autoroutes et à proximité des zones de restauration.",
    shape: "square",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "service",
    subcategory: "utility",
    name: "Toilettes",
    description: "Panneau carré bleu avec un pictogramme de toilettes.",
    meaning: "Indique la proximité de toilettes publiques accessibles. Ce panneau est fréquemment rencontré sur les aires de repos d'autoroute et les aires de service.",
    useCase: "Installé sur les aires d'autoroute, aires de repos, gares et lieux publics pour signaler la présence de sanitaires.",
    shape: "square",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "service",
    subcategory: "communication",
    name: "Téléphone d'urgence",
    description: "Panneau carré bleu avec un pictogramme de combiné téléphonique.",
    meaning: "Indique la proximité d'un téléphone d'urgence ou d'un point d'appel d'urgence. Ces téléphones permettent de contacter les secours gratuitement en cas d'accident ou de panne. Sur autoroute, les bornes d'appel d'urgence sont situées tous les 2 kilomètres.",
    useCase: "Installé sur les autoroutes, tunnels, et routes isolées pour permettre aux usagers de contacter les secours en cas de besoin.",
    shape: "square",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "service",
    subcategory: "utility",
    name: "Aire de repos",
    description: "Panneau carré bleu avec un pictogramme de table de pique-nique et d'arbre.",
    meaning: "Indique une aire de repos où les conducteurs peuvent s'arrêter pour se reposer. Les aires de repos offrent des installations de base : tables de pique-nique, bancs, toilettes. Elles n'ont pas de station-service. Le temps de repos minimum recommandé est de 15 minutes toutes les 2 heures de conduite.",
    useCase: "Installé sur les autoroutes et voies rapides pour permettre aux conducteurs de faire une pause de repos sans quitter le réseau.",
    shape: "square",
    colors: JSON.stringify(["blue", "white"]),
    questions: null,
  },
  // ═══════════════════════════════════════════════════════════════
  // TEMPORARY SIGNS — Signalisation temporaire
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "temporary",
    subcategory: "road_works",
    name: "Travaux (signalisation temporaire)",
    description: "Panneau triangulaire jaune avec un pictogramme noir de travaux, entouré d'un liseré rouge.",
    meaning: "Version temporaire du panneau de danger 'Travaux'. Signale la présence de travaux sur la chaussée ou à proximité immédiate avec une signalisation provisoire. Le fond jaune distingue ce panneau de la signalisation permanente (fond blanc). Le conducteur doit ralentir et se conformer aux déviations mises en place.",
    useCase: "Utilisé lors de tous chantiers routiers temporaires : réfection de chaussée, travaux de voirie, installation de réseaux, maintenance.",
    shape: "triangle",
    colors: JSON.stringify(["yellow", "red", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "temporary",
    subcategory: "deviation",
    name: "Déviation",
    description: "Panneau rectangulaire jaune avec une flèche noire indiquant une direction de déviation.",
    meaning: "Indique un itinéraire de déviation imposé en raison de travaux, d'un accident ou d'un obstacle sur la route normale. Le conducteur doit obligatoirement suivre la direction indiquée. Les panneaux de déviation sont généralement accompagnés de panneaux de présignalisation et de confirmation.",
    useCase: "Installé lors de fermeture de route pour travaux, accidents, événements ou tout autre nécessitant un détournement temporaire du trafic.",
    shape: "rectangle",
    colors: JSON.stringify(["yellow", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "temporary",
    subcategory: "road_works",
    name: "Chaussée rétrécie (temporaire)",
    description: "Panneau triangulaire jaune avec un pictogramme de rétrécissement de chaussée, bordé de rouge.",
    meaning: "Version temporaire du panneau de danger 'Chaussée rétrécie'. Signale un rétrécissement temporaire de la chaussée dû à des travaux. Le conducteur doit ralentir et se concerter avec les autres véhicules pour le passage alterné si nécessaire.",
    useCase: "Placé lors de travaux réduisant temporairement la largeur de la chaussée.",
    shape: "triangle",
    colors: JSON.stringify(["yellow", "red", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "temporary",
    subcategory: "mobile_signage",
    name: "Signalisation mobile",
    description: "Véhicule de signalisation mobile avec un panneau à chevron fluorescent et gyrophares.",
    meaning: "Signale un danger ou des travaux avec une signalisation mobile (véhicule d'accompagnement). Le conducteur doit ralentir et se conformer aux indications du véhicule de signalisation. Le non-respect des indications d'un véhicule de signalisation mobile est sanctionné comme le non-respect d'un panneau fixe.",
    useCase: "Utilisé lors de travaux mobiles, opérations de maintenance, convois exceptionnels et toute intervention temporaire nécessitant une signalisation roulante.",
    shape: "rectangle",
    colors: JSON.stringify(["yellow", "black", "orange"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "temporary",
    subcategory: "speed_limit",
    name: "Limitation de vitesse temporaire",
    description: "Panneau rond jaune avec un chiffre noir barré de rouge.",
    meaning: "Version temporaire du panneau de limitation de vitesse. Impose une limitation de vitesse temporaire en raison de travaux, de conditions météorologiques défavorables ou d'un incident. Le fond jaune indique qu'il s'agit d'une signalisation temporaire. La vitesse indiquée doit être respectée jusqu'au panneau de fin de limitation temporaire.",
    useCase: "Installé lors de travaux, après un accident, ou par conditions météorologiques dangereuses pour réduire temporairement la vitesse.",
    shape: "circle",
    colors: JSON.stringify(["yellow", "red", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "temporary",
    subcategory: "road_condition",
    name: "Passage pour piétons (temporaire)",
    description: "Panneau triangulaire jaune avec un pictogramme de piéton, bordé de rouge.",
    meaning: "Version temporaire du panneau de danger 'Passage pour piétons'. Signale un passage piéton temporaire mis en place en raison de travaux modifiant l'itinéraire piétonnier habituel. Le conducteur doit ralentir et céder le passage aux piétons.",
    useCase: "Utilisé lors de travaux modifiant temporairement les trajets piétonniers, déviations piétonnes.",
    shape: "triangle",
    colors: JSON.stringify(["yellow", "red", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "temporary",
    subcategory: "road_works",
    name: "Barrière de sécurité temporaire",
    description: "Panneau de signalisation temporaire de type balise de chantier ou barrière de type Vaudrey-Béton.",
    meaning: "Délimite la zone de travaux et interdit l'accès aux véhicules et aux piétons. Le franchissement de ces barrières est interdit et dangereux. Les barrières sont généralement de couleur vive (rouge et blanc) et peuvent être réfléchissantes pour la nuit.",
    useCase: "Placé autour des chantiers pour délimiter la zone de danger et protéger les travailleurs et les usagers.",
    shape: "rectangle",
    colors: JSON.stringify(["red", "white", "black"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "temporary",
    subcategory: "road_works",
    name: "Fin de signalisation temporaire",
    description: "Panneau rond gris avec des barres noires diagonales.",
    meaning: "Indique la fin de toutes les prescriptions liées à la signalisation temporaire. Le conducteur retrouve les conditions de circulation normales et les règles de la signalisation permanente. Ce panneau est obligatoire à la fin de tout chantier pour lever les prescriptions temporaires.",
    useCase: "Installé à la fin d'une zone de travaux ou de signalisation temporaire pour restaurer les règles permanentes de circulation.",
    shape: "circle",
    colors: JSON.stringify(["grey", "black"]),
    questions: null,
  },
  // ═══════════════════════════════════════════════════════════════
  // ROAD MARKINGS — Marquage au sol
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "longitudinal",
    name: "Ligne continue (interdiction de franchir)",
    description: "Ligne blanche continue peinte sur la chaussée, dans le sens de la circulation.",
    meaning: "Interdit le franchissement ou le chevauchement de la ligne. Le conducteur ne doit pas traverser cette ligne pour dépasser, changer de voie ou tourner. Le franchissement d'une ligne continue est une infraction grave au code de la route, passible d'une amende et d'un retrait de points. La ligne continue peut être simple ou double.",
    useCase: "Peinte sur les routes à double sens pour séparer les flux de circulation dans les zones de dépassement interdit (virages, crêtes, visibilité réduite).",
    shape: "rectangle",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "longitudinal",
    name: "Ligne discontinue (franchissement autorisé)",
    description: "Ligne blanche discontinue (tirets) peinte sur la chaussée, dans le sens de la circulation.",
    meaning: "Autorise le franchissement pour dépasser ou changer de voie, à condition que la manœuvre soit effectuée en toute sécurité. Le conducteur doit s'assurer qu'il a la visibilité et l'espace suffisants pour effectuer son dépassement avant de franchir la ligne. Lorsqu'une ligne discontinue est accolée à une ligne continue du côté du conducteur, le franchissement est interdit.",
    useCase: "Peinte sur les routes à double sens pour séparer les flux de circulation dans les zones où le dépassement est autorisé, et entre les voies sur routes à chaussées séparées.",
    shape: "rectangle",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "pedestrian",
    name: "Passage piéton",
    description: "Bandes blanches larges parallèles à la circulation, peintes sur la chaussée (zèbre).",
    meaning: "Indique un passage réservé aux piétons pour traverser la chaussée. Le conducteur doit céder le passage aux piétons qui s'engagent sur le passage ou y sont déjà engagés. Le dépassement est interdit à l'approche d'un passage piéton si un véhicule est arrêté pour laisser passer un piéton. Le stationnement sur un passage piéton est interdit.",
    useCase: "Peint aux carrefours, aux feux, à proximité des écoles, commerces et partout où le passage des piétons doit être sécurisé.",
    shape: "rectangle",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "stop_line",
    name: "Ligne d'arrêt (Stop)",
    description: "Ligne blanche continue épaisse, perpendiculaire à l'axe de la route.",
    meaning: "Indique l'endroit où le conducteur doit obligatoirement marquer l'arrêt complet devant un panneau STOP ou un feu rouge. Le véhicule doit s'immobiliser avant cette ligne. Si aucune ligne n'est peinte, l'arrêt doit se faire avant le passage piéton ou à la limite de la chaussée.",
    useCase: "Peinte sur la chaussée à l'approche des intersections équipées d'un panneau STOP ou de feux tricolores.",
    shape: "rectangle",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "give_way",
    name: "Ligne de cédez le passage",
    description: "Ligne blanche discontinue formée de larges triangles pointant vers le conducteur, perpendiculaire à la route.",
    meaning: "Indique l'endroit où le conducteur doit s'assurer qu'il peut s'engager sans gêner les véhicules prioritaires. L'arrêt n'est obligatoire que si un véhicule approche. Le conducteur doit ralentir à l'approche de cette ligne et céder le passage aux véhicules circulant sur la route prioritaire.",
    useCase: "Peinte sur la chaussée à l'approche des intersections non régulées où le cédez-le-passage est obligatoire.",
    shape: "triangle",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "emergency",
    name: "Bande d'arrêt d'urgence",
    description: "Ligne continue blanche ou orange délimitant la bande d'arrêt d'urgence sur le côté droit de l'autoroute.",
    meaning: "Délimite la bande d'arrêt d'urgence réservée aux véhicules en panne ou impliqués dans un accident. La circulation normale ne doit pas emprunter cette bande. En cas de panne, le conducteur doit se garer sur la bande d'arrêt d'urgence, allumer les feux de détresse et quitter le véhicule par le côté droit.",
    useCase: "Peinte sur les autoroutes et voies rapides pour délimiter la bande d'arrêt d'urgence sur le côté droit de la chaussée.",
    shape: "rectangle",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "directional",
    name: "Marquage directionnel (flèches au sol)",
    description: "Flèches blanches peintes sur la chaussée indiquant la direction à suivre.",
    meaning: "Guide le conducteur dans le choix de sa voie en fonction de sa destination. Les flèches peuvent être droites (tout droit), courbées (tourner) ou de présignalisation. Une flèche de présignalisation (longue flèche) indique que le conducteur doit choisir sa voie bien avant le carrefour.",
    useCase: "Peintes sur les voies de circulation à l'approche des carrefours, giratoires, sorties d'autoroute et intersections complexes.",
    shape: "arrow",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "reserved_lane",
    name: "Voie réservée (marquage au sol)",
    description: "Ligne continue blanche délimitant une voie réservée, avec un pictogramme (vélo, bus) peint au sol.",
    meaning: "Délimite une voie réservée à une catégorie d'usagers (bus, taxis, cyclistes). Les véhicules non autorisés ne doivent pas circuler sur cette voie. Les pictogrammes au sol rappellent régulièrement la catégorie d'usagers autorisée.",
    useCase: "Peinte sur les voies urbaines pour réserver une voie aux bus, taxis ou cyclistes, avec des pictogrammes répétés.",
    shape: "rectangle",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "longitudinal",
    name: "Ligne de rive",
    description: "Ligne blanche continue tracée sur le bord droit de la chaussée.",
    meaning: "Délimite le bord de la chaussée par rapport à l'accotement. Le franchissement de la ligne de rive est possible pour s'arrêter, stationner ou tourner, mais le stationnement est interdit si un panneau le précise. Cette ligne guide le conducteur sur la trajectoire à suivre.",
    useCase: "Peinte sur le bord droit des routes pour délimiter la chaussée et guider les conducteurs, notamment de nuit et par mauvais temps.",
    shape: "rectangle",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "longitudinal",
    name: "Ligne de guidage",
    description: "Ligne blanche continue ou discontinue peinte au centre de la chaussée.",
    meaning: "Sépare les flux de circulation dans le sens longitudinal. Sur une route à double sens sans séparateur central, la ligne de guidage sépare les deux sens de circulation. Sur une route à chaussées séparées, elle sépare les voies de circulation dans le même sens.",
    useCase: "Peinte au milieu des routes à double sens et entre les voies des routes à multi-voies.",
    shape: "rectangle",
    colors: JSON.stringify(["white"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "special",
    name: "Zébra (passage piétonn alterné)",
    description: "Passage piéton avec des bandes blanches et bleues alternées.",
    meaning: "Variante du passage piéton classique avec un marquage alterné blanc et bleu. Les règles de priorité sont identiques au passage piéton classique : le conducteur doit céder le passage aux piétons engagés sur le passage. Ce marquage est parfois utilisé pour améliorer la visibilité.",
    useCase: "Utilisé comme alternative au passage piéton classique dans certaines communes pour améliorer la visibilité des passages piétons.",
    shape: "rectangle",
    colors: JSON.stringify(["white", "blue"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "marking",
    subcategory: "special",
    name: "Cédez-le-passage cycliste au feu",
    description: "Ligne discontinue verte et cycliste peint au sol à l'approche d'un feu.",
    meaning: "Autorise les cyclistes à franchir le feu rouge après avoir cédé le passage aux piétons et aux véhicules prioritaires. Ce marquage, spécifique à certaines villes françaises, permet aux cyclistes de tourner à droite ou d'aller tout droit au feu rouge, à condition de s'assurer que la manœuvre est sans danger.",
    useCase: "Installé dans certaines villes françaises (Paris, Strasbourg, Nantes, Bordeaux) aux carrefours à feux pour faciliter la circulation des cyclistes.",
    shape: "rectangle",
    colors: JSON.stringify(["green", "white"]),
    questions: null,
  },
  // ═══════════════════════════════════════════════════════════════
  // TRAFFIC LIGHTS — Feux tricolores
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: "FR",
    category: "traffic_light",
    subcategory: null,
    name: "Feu rouge (arrêt obligatoire)",
    description: "Cercle lumineux rouge allumé sur un feu tricolore.",
    meaning: "Oblige tout conducteur de marquer l'arrêt absolu devant la ligne d'arrêt. Le franchissement du feu rouge est un délit grave passible d'une amende de 135 €, d'un retrait de 4 points et éventuellement d'une suspension de permis. Le conducteur ne doit s'engager que lorsque le feu passe au vert. Il est interdit de tourner à droite au feu rouge en France (contrairement à certains pays).",
    useCase: "Présent à toutes les intersections régulées par des feux tricolores en France.",
    shape: "circle",
    colors: JSON.stringify(["red"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "traffic_light",
    subcategory: null,
    name: "Feu orange (avertissement)",
    description: "Cercle lumineux orange allumé sur un feu tricolore.",
    meaning: "Avertit le conducteur de l'imminence du passage au feu rouge. Si le conducteur peut s'arrêter en toute sécurité avant la ligne d'arrêt, il doit le faire. S'il est trop proche de la ligne d'arrêt lorsqu'il s'allume et qu'un freinage brusque créerait un danger, il peut continuer à traverser l'intersection. Le franchissement d'un feu orange est verbalisable si le véhicule était en mesure de s'arrêter.",
    useCase: "S'allume entre le feu vert et le feu rouge pour avertir de l'imminence du changement de signalisation.",
    shape: "circle",
    colors: JSON.stringify(["orange"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "traffic_light",
    subcategory: null,
    name: "Feu vert (passage autorisé)",
    meaning: "Autorise le passage mais n'accorde aucune priorité. Le conducteur peut s'engager dans l'intersection mais doit vérifier qu'elle est dégagée. Il doit également céder le passage aux véhicules non encore dégagés de l'intersection et aux piétons engagés sur le passage. Le conducteur ne doit pas s'engager si la file de véhicules est longue et risque de bloquer l'intersection.",
    useCase: "S'allume après le feu rouge pour autoriser la reprise de la circulation dans la direction concernée.",
    shape: "circle",
    colors: JSON.stringify(["green"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "traffic_light",
    subcategory: "flashing",
    name: "Feu clignotant orange",
    description: "Feu orange allumé en mode clignotant, sans feu rouge ni vert.",
    meaning: "Fonctionne comme un panneau cédez-le-passage. Le conducteur doit ralentir, vérifier que la voie est libre et céder le passage aux autres usagers avant de s'engager. Le feu clignotant orange remplace généralement le feu tricolore la nuit, en dehors des heures de pointe ou en cas de panne.",
    useCase: "Installé aux intersections où le feu tricolore fonctionne en mode dégradé (nuit, heures creuses, panne) ou en sortie de carrefour giratoire.",
    shape: "circle",
    colors: JSON.stringify(["orange"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "traffic_light",
    subcategory: "flashing",
    name: "Feu clignotant rouge",
    description: "Feu rouge allumé en mode clignotant, généralement en complément d'un panneau stop.",
    meaning: "Fonctionne comme un panneau STOP. Le conducteur doit obligatoirement marquer l'arrêt complet avant la ligne d'arrêt, vérifier que la voie est libre, puis s'engager avec prudence. Le feu clignotant rouge est souvent utilisé en sortie de carrefour giratoire et aux passages à niveau.",
    useCase: "Installé en sortie de carrefour à sens giratoire, aux passages à niveau et aux intersections à faible trafic en mode dégradé.",
    shape: "circle",
    colors: JSON.stringify(["red"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "traffic_light",
    subcategory: null,
    name: "Feu à l'arrêt (éteint / noir)",
    description: "Feu tricolore entièrement éteint, ne projetant aucune lumière.",
    meaning: "Un feu éteint ne s'impose pas. Le conducteur doit appliquer les règles de priorité habituelles (priorité à droite, cédez-le-passage, stop) comme si le feu n'existait pas. Il ne doit ni s'arrêter systématiquement, ni ignorer les règles de priorité. L'absence de fonctionnement doit être signalée aux autorités compétentes.",
    useCase: "Se produit en cas de panne électrique, de coupure de courant ou de maintenance du feu tricolore.",
    shape: "circle",
    colors: JSON.stringify(["black", "grey"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "traffic_light",
    subcategory: "supplementary",
    name: "Flèche directionnelle verte",
    description: "Feu vert en forme de flèche directionnelle orientée vers la gauche, la droite ou tout droit.",
    meaning: "Autorise le passage dans la direction indiquée par la flèche uniquement. Si une flèche verte est orientée à droite, le conducteur peut tourner à droite mais ne peut ni aller tout droit ni tourner à gauche. Ce signal permet de réguler séparément les différentes directions de circulation.",
    useCase: "Installé aux carrefours complexes pour autoriser sélectivement les différentes directions de circulation.",
    shape: "arrow",
    colors: JSON.stringify(["green"]),
    questions: null,
  },
  {
    countryCode: "FR",
    category: "traffic_light",
    subcategory: "pedestrian",
    name: "Feu piéton",
    description: "Petit feu bicolore dédié aux piétons, avec un pictogramme de piéton.",
    meaning: "Le feu rouge (piéton immobile) interdit aux piétons de s'engager sur le passage. Le feu vert (piéton en marche) autorise les piétons à traverser. Un feu clignotant vert indique la fin imminente du temps de traversée : les piétons déjà engagés peuvent terminer leur traversée, mais ceux qui ne sont pas encore partis ne doivent pas s'engager.",
    useCase: "Installé sur les trottoirs à côté des passages piétons régulés par des feux tricolores pour guider les piétons.",
    shape: "rectangle",
    colors: JSON.stringify(["red", "green"]),
    questions: null,
  },
];
