// ═══════════════════════════════════════════════════════════
// ADSO V3 — Seed Data: World Countries Database
// 65 countries with comprehensive driving regulations
// ═══════════════════════════════════════════════════════════

export const seedCountries = [
  {
    code: "ML",
    name: "Mali",
    flag: "🇲🇱",
    continent: "Afrique",
    capital: "Bamako",
    languages: JSON.stringify(["Français", "Bambara"]),
    currency: JSON.stringify({"code": "XOF", "symbol": "CFA", "name": "Franc CFA BCEAO"}),
    drivingSide: "right",
    authority: "Direction Nationale des Transports",
    emergencyPhone: "15",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Carte d'identité"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Code de la route inspiré du système francophone"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port du casque", "Alcoolémie", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 5 000 - 50 000 CFA", "Retrait de points", "Suspension du permis"]),
  },
  {
    code: "SN",
    name: "Sénégal",
    flag: "🇸🇳",
    continent: "Afrique",
    capital: "Dakar",
    languages: JSON.stringify(["Français", "Wolof"]),
    currency: JSON.stringify({"code": "XOF", "symbol": "CFA", "name": "Franc CFA BCEAO"}),
    drivingSide: "right",
    authority: "Direction de la Circulation Routière",
    emergencyPhone: "15",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet de sécurité", "Extincteur"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points en cours d'adoption"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 5 000 - 100 000 CFA", "Retrait de points", "Suspension du permis"]),
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    continent: "Afrique",
    capital: "Abidjan",
    languages: JSON.stringify(["Français", "Baoulé"]),
    currency: JSON.stringify({"code": "XOF", "symbol": "CFA", "name": "Franc CFA BCEAO"}),
    drivingSide: "right",
    authority: "Direction Générale des Transports Terrestres",
    emergencyPhone: "15",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Visite technique"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points depuis 2019"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Dépassement dangereux"]),
    sanctions: JSON.stringify(["Amende: 5 000 - 50 000 CFA", "Retrait de points"]),
  },
  {
    code: "BF",
    name: "Burkina Faso",
    flag: "🇧🇫",
    continent: "Afrique",
    capital: "Ouagadougou",
    languages: JSON.stringify(["Français", "Mooré"]),
    currency: JSON.stringify({"code": "XOF", "symbol": "CFA", "name": "Franc CFA BCEAO"}),
    drivingSide: "right",
    authority: "Direction Générale des Transports",
    emergencyPhone: "17",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation"]),
    specialFeatures: JSON.stringify(["Priorité à droite"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port du casque", "Alcoolémie"]),
    sanctions: JSON.stringify(["Amende: 3 000 - 30 000 CFA"]),
  },
  {
    code: "NE",
    name: "Niger",
    flag: "🇳🇪",
    continent: "Afrique",
    capital: "Niamey",
    languages: JSON.stringify(["Français", "Haoussa"]),
    currency: JSON.stringify({"code": "XOF", "symbol": "CFA", "name": "Franc CFA BCEAO"}),
    drivingSide: "right",
    authority: "Direction des Transports Terrestres",
    emergencyPhone: "17",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Convois militaires prioritaires"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port du casque", "Alcoolémie"]),
    sanctions: JSON.stringify(["Amende: 5 000 - 50 000 CFA"]),
  },
  {
    code: "GN",
    name: "Guinée",
    flag: "🇬🇳",
    continent: "Afrique",
    capital: "Conakry",
    languages: JSON.stringify(["Français", "Malinké"]),
    currency: JSON.stringify({"code": "GNF", "symbol": "FG", "name": "Franc guinéen"}),
    drivingSide: "right",
    authority: "Ministère des Transports",
    emergencyPhone: "17",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation"]),
    specialFeatures: JSON.stringify(["Priorité à droite"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port du casque"]),
    sanctions: JSON.stringify(["Amende: 10 000 - 100 000 FG"]),
  },
  {
    code: "CM",
    name: "Cameroun",
    flag: "🇨🇲",
    continent: "Afrique",
    capital: "Yaoundé",
    languages: JSON.stringify(["Français", "Anglais"]),
    currency: JSON.stringify({"code": "XAF", "symbol": "CFA", "name": "Franc CFA BEAC"}),
    drivingSide: "right",
    authority: "Ministère des Transports",
    emergencyPhone: "17",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Vignette obligatoire"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 5 000 - 100 000 CFA"]),
  },
  {
    code: "TG",
    name: "Togo",
    flag: "🇹🇬",
    continent: "Afrique",
    capital: "Lomé",
    languages: JSON.stringify(["Français", "Éwé"]),
    currency: JSON.stringify({"code": "XOF", "symbol": "CFA", "name": "Franc CFA BCEAO"}),
    drivingSide: "right",
    authority: "Direction des Transports Terrestres",
    emergencyPhone: "17",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation"]),
    specialFeatures: JSON.stringify(["Priorité à droite"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port du casque", "Alcoolémie"]),
    sanctions: JSON.stringify(["Amende: 5 000 - 50 000 CFA"]),
  },
  {
    code: "BJ",
    name: "Bénin",
    flag: "🇧🇯",
    continent: "Afrique",
    capital: "Porto-Novo",
    languages: JSON.stringify(["Français", "Fon"]),
    currency: JSON.stringify({"code": "XOF", "symbol": "CFA", "name": "Franc CFA BCEAO"}),
    drivingSide: "right",
    authority: "Direction Générale des Transports Terrestres",
    emergencyPhone: "17",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation"]),
    specialFeatures: JSON.stringify(["Priorité à droite"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie"]),
    sanctions: JSON.stringify(["Amende: 5 000 - 50 000 CFA"]),
  },
  {
    code: "CD",
    name: "RDC",
    flag: "🇨🇩",
    continent: "Afrique",
    capital: "Kinshasa",
    languages: JSON.stringify(["Français", "Lingala"]),
    currency: JSON.stringify({"code": "CDF", "symbol": "FC", "name": "Franc congolais"}),
    drivingSide: "right",
    authority: "Régie des Voies Aériennes, Fluviales, Maritimes et Terrestres",
    emergencyPhone: "15",
    minAge: 18,
    speedUrban: 60,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Conduite en convoi possible"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port du casque", "Alcoolémie"]),
    sanctions: JSON.stringify(["Amende: 5 000 - 50 000 CDF"]),
  },
  {
    code: "MA",
    name: "Maroc",
    flag: "🇲🇦",
    continent: "Afrique",
    capital: "Rabat",
    languages: JSON.stringify(["Arabe", "Français"]),
    currency: JSON.stringify({"code": "MAD", "symbol": "MAD", "name": "Dirham marocain"}),
    drivingSide: "right",
    authority: "Ministère de l'Équipement et du Transport",
    emergencyPhone: "15",
    minAge: 18,
    speedUrban: 60,
    speedRural: 100,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique", "Vignette"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet de sécurité", "Extincteur"]),
    specialFeatures: JSON.stringify(["Système de points (25 points) depuis 2016", "Priorité à droite"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 100 - 2 500 MAD", "Retrait de points", "Suspension du permis"]),
  },
  {
    code: "TN",
    name: "Tunisie",
    flag: "🇹🇳",
    continent: "Afrique",
    capital: "Tunis",
    languages: JSON.stringify(["Arabe", "Français"]),
    currency: JSON.stringify({"code": "TND", "symbol": "DT", "name": "Dinar tunisien"}),
    drivingSide: "right",
    authority: "Ministère des Transports",
    emergencyPhone: "19",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 110,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points depuis 2010"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 10 - 1 500 DT", "Retrait de points"]),
  },
  {
    code: "DZ",
    name: "Algérie",
    flag: "🇩🇿",
    continent: "Afrique",
    capital: "Alger",
    languages: JSON.stringify(["Arabe", "Français"]),
    currency: JSON.stringify({"code": "DZD", "symbol": "DA", "name": "Dinar algérien"}),
    drivingSide: "right",
    authority: "Ministère des Transports",
    emergencyPhone: "14",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 120,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique", "Vignette"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points (42 points)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 500 - 20 000 DA", "Retrait de points"]),
  },
  {
    code: "KE",
    name: "Kenya",
    flag: "🇰🇪",
    continent: "Afrique",
    capital: "Nairobi",
    languages: JSON.stringify(["Swahili", "Anglais"]),
    currency: JSON.stringify({"code": "KES", "symbol": "KSh", "name": "Shilling kényan"}),
    drivingSide: "left",
    authority: "National Transport and Safety Authority (NTSA)",
    emergencyPhone: "999",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 110,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "Système de points"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Surcharge"]),
    sanctions: JSON.stringify(["Amende: 500 - 100 000 KSh", "Suspension du permis"]),
  },
  {
    code: "ZA",
    name: "Afrique du Sud",
    flag: "🇿🇦",
    continent: "Afrique",
    capital: "Pretoria",
    languages: JSON.stringify(["Anglais", "Afrikaans", "Zoulou"]),
    currency: JSON.stringify({"code": "ZAR", "symbol": "R", "name": "Rand sud-africain"}),
    drivingSide: "left",
    authority: "Department of Transport",
    emergencyPhone: "10111",
    minAge: 18,
    speedUrban: 60,
    speedRural: 100,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Trousse de premiers secours", "Gilet réfléchissant"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "Système de démérite (3 strikes)"]),
    licenseCategories: JSON.stringify(["A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie (sévère)", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 250 - 50 000 R", "Prison possible", "Suspension du permis"]),
  },
  {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    continent: "Europe",
    capital: "Paris",
    languages: JSON.stringify(["Français"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Préfecture / Ministère de l'Intérieur",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 130,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique", "Constataire européen d'assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet de sécurité (dans l'habitacle)", "Éthylotest non utilisé"]),
    specialFeatures: JSON.stringify(["Priorité à droite sauf signalisation contraire", "Système de points (12 points initial)", "Conduite accompagnée dès 16 ans", "Limitation 80 km/h par temps de pluie depuis 2018"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "B96", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port de la ceinture", "Téléphone au volant", "Alcoolémie", "Franchissement de ligne continue"]),
    sanctions: JSON.stringify(["Amende: 35 - 1 500 €", "Retrait de points: 1-6 points", "Suspension du permis", "Stage de récupération de points"]),
  },
  {
    code: "BE",
    name: "Belgique",
    flag: "🇧🇪",
    continent: "Europe",
    capital: "Bruxelles",
    languages: JSON.stringify(["Français", "Néerlandais", "Allemand"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Service public fédéral Mobilité et Transports",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet de sécurité"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points", "Ignition obligatoire jour et nuit"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "B96", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 58 - 2 750 €", "Retrait de points"]),
  },
  {
    code: "CH",
    name: "Suisse",
    flag: "🇨🇭",
    continent: "Europe",
    capital: "Berne",
    languages: JSON.stringify(["Allemand", "Français", "Italien"]),
    currency: JSON.stringify({"code": "CHF", "symbol": "CHF", "name": "Franc suisse"}),
    drivingSide: "right",
    authority: "Office fédéral des routes (OFROU)",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique", "Autocollant vignette (autoroute)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet de sécurité", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Vignette autoroute obligatoire", "Conduite accompagnée dès 17 ans"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "B96", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse (sévèrement sanctionné)", "Alcoolémie", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 60 - 250 CHF (léger), jusqu'à 10 000 CHF (grave)", "Retrait de points"]),
  },
  {
    code: "DE",
    name: "Allemagne",
    flag: "🇩🇪",
    continent: "Europe",
    capital: "Berlin",
    languages: JSON.stringify(["Allemand"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Kraftfahrt-Bundesamt (KBA)",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 100,
    speedHighway: 130,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique (TÜV)", "Autobahn vignette"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet de sécurité", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Autobahn sans limitation générale de vitesse", "Conduite accompagnée dès 17 ans (BF17)", "Système de points à Flensburg (8 points max)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant", "Franchissement de ligne continue"]),
    sanctions: JSON.stringify(["Amende: 10 - 680 €", "Retrait de points (1-3)", "Suspend/Revoke (Fahrverbot)"]),
  },
  {
    code: "ES",
    name: "Espagne",
    flag: "🇪🇸",
    continent: "Europe",
    capital: "Madrid",
    languages: JSON.stringify(["Espagnol", "Catalan", "Basque"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Dirección General de Tráfico (DGT)",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "ITV (contrôle technique)", "Assurance", "Ficha técnica"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant (2)", "Trousse de premiers secours", "Roue de secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points (12 points)", "ITV obligatoire", "Gilet obligatoire hors véhicule en panne"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "B96", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant", "Non-port du casque (moto)"]),
    sanctions: JSON.stringify(["Amende: 100 - 500 €", "Retrait de points: 2-6 points", "Suspension du permis"]),
  },
  {
    code: "IT",
    name: "Italie",
    flag: "🇮🇹",
    continent: "Europe",
    capital: "Rome",
    languages: JSON.stringify(["Italien"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Ministero delle Infrastrutture e dei Trasporti",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 130,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise (libretto)", "Assurance", "Contrôle technique (revisione)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points (20 points)", "Limitations ZTL (zones à trafic limité)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "B96", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 41 - 1 700 €", "Retrait de points: 1-10 points"]),
  },
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    continent: "Europe",
    capital: "Lisbonne",
    languages: JSON.stringify(["Portugais"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Autoridade Nacional de Segurança Rodoviária (ANSR)",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique (Inspeção Periódica)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Trousse de premiers secours", "2 roues de secours ou kit réparation"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points (12 points)", "Portugueses Highway Vignette (Portagem)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "B96", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 60 - 2 500 €", "Retrait de points"]),
  },
  {
    code: "GB",
    name: "Royaume-Uni",
    flag: "🇬🇧",
    continent: "Europe",
    capital: "Londres",
    languages: JSON.stringify(["Anglais", "Gallois"]),
    currency: JSON.stringify({"code": "GBP", "symbol": "£", "name": "Livre sterling"}),
    drivingSide: "left",
    authority: "Driver and Vehicle Licensing Agency (DVLA)",
    emergencyPhone: "999",
    minAge: 17,
    speedUrban: 48,
    speedRural: 96,
    speedHighway: 112,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise (V5C)", "Assurance (MOT/SORN)", "Contrôle technique (MOT)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation (conseillé)", "Gilet réfléchissant"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "Système de points (12 points)", "Provisional license possible à 17 ans", "MOT test obligatoire (3 ans pour neuf)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant", "Conduite sans assurance"]),
    sanctions: JSON.stringify(["Amende: 100 - 10 000 £", "Points de pénalité: 3-6", "Disqualification du permis"]),
  },
  {
    code: "NL",
    name: "Pays-Bas",
    flag: "🇳🇱",
    continent: "Europe",
    capital: "Amsterdam",
    languages: JSON.stringify(["Néerlandais"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Rijksdienst voor het Wegverkeer (RDW)",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique (APK/MOT)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant"]),
    specialFeatures: JSON.stringify(["Priorité à droite (sauf vélos prioritaires)", "Vélos très nombreux, attention cyclistes", "Système de points (entree)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "B96", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant", "Non-respect cyclistes"]),
    sanctions: JSON.stringify(["Amende: 70 - 400 €", "Retrait de points"]),
  },
  {
    code: "LU",
    name: "Luxembourg",
    flag: "🇱🇺",
    continent: "Europe",
    capital: "Luxembourg",
    languages: JSON.stringify(["Français", "Allemand", "Luxembourgeois"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Administration de l'enregistrement et des transports",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 130,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet de sécurité"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Transport public gratuit (national)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "B96", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 74 - 1 000 €", "Retrait de points"]),
  },
  {
    code: "PL",
    name: "Pologne",
    flag: "🇵🇱",
    continent: "Europe",
    capital: "Varsovie",
    languages: JSON.stringify(["Polonais"]),
    currency: JSON.stringify({"code": "PLN", "symbol": "zł", "name": "Zloty polonais"}),
    drivingSide: "right",
    authority: "Ministerstwo Infrastruktury",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 140,
    bloodAlcohol: 0.2,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Extincteur"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points (24 points initial)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie (zéro tolérance)", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 50 - 5 000 PLN", "Retrait de points"]),
  },
  {
    code: "CZ",
    name: "Tchéquie",
    flag: "🇨🇿",
    continent: "Europe",
    capital: "Prague",
    languages: JSON.stringify(["Tchèque"]),
    currency: JSON.stringify({"code": "CZK", "symbol": "Kč", "name": "Couronne tchèque"}),
    drivingSide: "right",
    authority: "Ministerstvo dopravy",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 130,
    bloodAlcohol: 0.0,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique (STK)", "Autobahn vignette"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Zéro tolérance alcool", "Vignette autoroute obligatoire"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Alcoolémie (zéro tolérance)", "Excès de vitesse", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 0 - 2 000 CZK (immédiat), jusqu'à 20 000 CZK", "Retrait de points (12 initial)"]),
  },
  {
    code: "AT",
    name: "Autriche",
    flag: "🇦🇹",
    continent: "Europe",
    capital: "Vienne",
    languages: JSON.stringify(["Allemand"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Ministerium für Klimaschutz, Mobilität, Innovation und Technologie",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 100,
    speedHighway: 130,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique", "Autobahn vignette"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Vignette autoroute obligatoire", "Conduite accompagnée (L17)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 36 - 2 180 €", "Retrait de points"]),
  },
  {
    code: "SE",
    name: "Suède",
    flag: "🇸🇪",
    continent: "Europe",
    capital: "Stockholm",
    languages: JSON.stringify(["Suédois"]),
    currency: JSON.stringify({"code": "SEK", "symbol": "kr", "name": "Couronne suédoise"}),
    drivingSide: "right",
    authority: "Transportstyrelsen",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 70,
    speedHighway: 110,
    bloodAlcohol: 0.2,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Tolérance alcool très basse (0.2 g/L)", "Feux de croisement obligatoires jour et nuit"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Alcoolémie (très sévère)", "Excès de vitesse", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 2 000 - 10 000 SEK", "Prison possible pour alcool"]),
  },
  {
    code: "NO",
    name: "Norvège",
    flag: "🇳🇴",
    continent: "Europe",
    capital: "Oslo",
    languages: JSON.stringify(["Norvégien"]),
    currency: JSON.stringify({"code": "NOK", "symbol": "kr", "name": "Couronne norvégienne"}),
    drivingSide: "right",
    authority: "Statens vegvesen",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 110,
    bloodAlcohol: 0.2,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique (EU-kontroll)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Tolérance alcool très basse (0.2 g/L)", "Fjords: attention aux tunnels et ferries"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Alcoolémie (très sévère)", "Excès de vitesse"]),
    sanctions: JSON.stringify(["Amende: 9 500 - 50% revenu mensuel", "Prison possible (1-3 semaines)"]),
  },
  {
    code: "FI",
    name: "Finlande",
    flag: "🇫🇮",
    continent: "Europe",
    capital: "Helsinki",
    languages: JSON.stringify(["Finnois", "Suédois"]),
    currency: JSON.stringify({"code": "EUR", "symbol": "€", "name": "Euro"}),
    drivingSide: "right",
    authority: "Liikenne- ja viestintävirasto (Traficom)",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Contrôle technique (Katsastus)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Feux de croisement obligatoires jour et nuit", "Hiver: pneus neige obligatoires (décembre-février)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 10 - 1 200 € (revenus-dépendant)", "Retrait de points"]),
  },
  {
    code: "US",
    name: "États-Unis",
    flag: "🇺🇸",
    continent: "Amériques",
    capital: "Washington D.C.",
    languages: JSON.stringify(["Anglais", "Espagnol"]),
    currency: JSON.stringify({"code": "USD", "symbol": "$", "name": "Dollar américain"}),
    drivingSide: "right",
    authority: "Department of Motor Vehicles (DMV) - par État",
    emergencyPhone: "911",
    minAge: 16,
    speedUrban: 40,
    speedRural: 90,
    speedHighway: 120,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise (Title)", "Assurance", "Immatriculation"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation (conseillé)", "Extincteur (conseillé)"]),
    specialFeatures: JSON.stringify(["Règles variables par État", "Permis Graduated Driver Licensing (GDL)", "Right turn on red autorisé (sauf signal contraire)", "School buses: arrêt obligatoire"]),
    licenseCategories: JSON.stringify(["A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "DUI (alcool)", "Running a red light", "Téléphone au volant (variable par État)"]),
    sanctions: JSON.stringify(["Amende: variable par État ($50-$2,500)", "Points (variable)", "Suspension/Revocation du permis"]),
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    continent: "Amériques",
    capital: "Ottawa",
    languages: JSON.stringify(["Anglais", "Français"]),
    currency: JSON.stringify({"code": "CAD", "symbol": "C$", "name": "Dollar canadien"}),
    drivingSide: "right",
    authority: "Ministry of Transportation (province) / SAAQ (Québec)",
    emergencyPhone: "911",
    minAge: 16,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Immatriculation", "Contrôle technique (variable par province)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Règles variables par province", "Permis gradué (GDL)", "Hiver: pneus neige obligatoires au Québec"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: variable par province", "Points de démérite", "Suspension du permis"]),
  },
  {
    code: "BR",
    name: "Brésil",
    flag: "🇧🇷",
    continent: "Amériques",
    capital: "Brasília",
    languages: JSON.stringify(["Portugais"]),
    currency: JSON.stringify({"code": "BRL", "symbol": "R$", "name": "Réal brésilien"}),
    drivingSide: "right",
    authority: "Departamento Nacional de Trânsito (DENATRAN)",
    emergencyPhone: "190",
    minAge: 18,
    speedUrban: 40,
    speedRural: 60,
    speedHighway: 120,
    bloodAlcohol: 0.0,
    requiredDocuments: JSON.stringify(["Permis de conduire (CNH)", "CRLV", "Assurance (DPVAT)", "Contrôle technique (selon État)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Macaron réfléchissant", "Extincteur", "Cric", "Chave de roda"]),
    specialFeatures: JSON.stringify(["Zéro tolérance alcool (Lei Seca)", "Système de points (20 points)", "CNH catégories A-E"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C", "CE", "D", "DE"]),
    commonInfractions: JSON.stringify(["Alcoolémie (Lei Seca - zéro tolérance)", "Excès de vitesse", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: R$ 294 (base), jusqu'à R$ 2 940", "Retrait de points: 4-8", "Suspension du permis"]),
  },
  {
    code: "MX",
    name: "Mexique",
    flag: "🇲🇽",
    continent: "Amériques",
    capital: "Mexico",
    languages: JSON.stringify(["Espagnol"]),
    currency: JSON.stringify({"code": "MXN", "symbol": "MX$", "name": "Peso mexicain"}),
    drivingSide: "right",
    authority: "Secretaría de Comunicaciones y Transportes (SCT)",
    emergencyPhone: "911",
    minAge: 18,
    speedUrban: 20,
    speedRural: 80,
    speedHighway: 110,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Tarjeta de circulación", "Assurance (variable)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur (conseillé)"]),
    specialFeatures: JSON.stringify(["Règles variables par État", "Antigüedad (permis temporaire pour nouveaux conducteurs)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C", "CE", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: variable par État ($500-$5 000 MXN)", "Points de démérite"]),
  },
  {
    code: "AR",
    name: "Argentine",
    flag: "🇦🇷",
    continent: "Amériques",
    capital: "Buenos Aires",
    languages: JSON.stringify(["Espagnol"]),
    currency: JSON.stringify({"code": "ARS", "symbol": "AR$", "name": "Peso argentin"}),
    drivingSide: "right",
    authority: "Agencia Nacional de Seguridad Vial (ANSV)",
    emergencyPhone: "911",
    minAge: 17,
    speedUrban: 40,
    speedRural: 80,
    speedHighway: 130,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Licencia de conducir", "Cédula verde", "Ruta", "Seguro (obligatoire)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Limitations variables par province"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C", "CE", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: $1 000 - $50 000 ARS", "Retrait de points"]),
  },
  {
    code: "CO",
    name: "Colombie",
    flag: "🇨🇴",
    continent: "Amériques",
    capital: "Bogotá",
    languages: JSON.stringify(["Espagnol"]),
    currency: JSON.stringify({"code": "COP", "symbol": "COL$", "name": "Peso colombien"}),
    drivingSide: "right",
    authority: "Ministerio de Transporte",
    emergencyPhone: "123",
    minAge: 16,
    speedUrban: 60,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.2,
    requiredDocuments: JSON.stringify(["Licencia de conducción", "Tarjeta de propiedad", "SOAT (assurance obligatoire)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Botiquín de primeros auxilios"]),
    specialFeatures: JSON.stringify(["Pico y placa (restriction par jour)", "SOAT obligatoire", "Tolérance alcool très basse (0.2 g/L)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D", "DE"]),
    commonInfractions: JSON.stringify(["Alcoolémie (sévère)", "Excès de vitesse", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 15 - 90 salaires minimum", "Suspension du permis"]),
  },
  {
    code: "CL",
    name: "Chili",
    flag: "🇨🇱",
    continent: "Amériques",
    capital: "Santiago",
    languages: JSON.stringify(["Espagnol"]),
    currency: JSON.stringify({"code": "CLP", "symbol": "CLP$", "name": "Peso chilien"}),
    drivingSide: "right",
    authority: "Ministerio de Transportes y Telecomunicaciones",
    emergencyPhone: "131",
    minAge: 18,
    speedUrban: 60,
    speedRural: 100,
    speedHighway: 120,
    bloodAlcohol: 0.3,
    requiredDocuments: JSON.stringify(["Licencia de conducir", "Padrón del vehículo", "Permiso de circulación", "Revisión técnica (2 ans)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Revision técnica obligatoire", "BIO-TOX (alcoolémie sévère)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D", "DE"]),
    commonInfractions: JSON.stringify(["Alcoolémie", "Excès de vitesse", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 1 - 5 UTM", "Retrait de points"]),
  },
  {
    code: "PE",
    name: "Pérou",
    flag: "🇵🇪",
    continent: "Amériques",
    capital: "Lima",
    languages: JSON.stringify(["Espagnol"]),
    currency: JSON.stringify({"code": "PEN", "symbol": "S/", "name": "Sol péruvien"}),
    drivingSide: "right",
    authority: "Ministerio de Transportes y Comunicaciones",
    emergencyPhone: "105",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Licencia de conducir", "Tarjeta de propiedad", "SOAT (assurance obligatoire)", "Revisión técnica"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["SOAT obligatoire", "Revision técnica obligatoire"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 50% UIT (≈ S/ 2 425)", "Suspension du permis"]),
  },
  {
    code: "CN",
    name: "Chine",
    flag: "🇨🇳",
    continent: "Asie",
    capital: "Pékin",
    languages: JSON.stringify(["Mandarin", "Cantonais"]),
    currency: JSON.stringify({"code": "CNY", "symbol": "¥", "name": "Yuan chinois"}),
    drivingSide: "right",
    authority: "Ministry of Public Security (Traffic Management Bureau)",
    emergencyPhone: "122 / 120",
    minAge: 18,
    speedUrban: 60,
    speedRural: 80,
    speedHighway: 120,
    bloodAlcohol: 0.2,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Certificat d'immatriculation", "Assurance obligatoire (交强险)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Gilet réfléchissant"]),
    specialFeatures: JSON.stringify(["Permis de conduire 12 points", "Tolérance alcool très basse (0.2 g/L)", "Restrictions urbaines par plaque"]),
    licenseCategories: JSON.stringify(["A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F"]),
    commonInfractions: JSON.stringify(["Alcoolémie (très sévère, prison possible)", "Excès de vitesse", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 200 - 2 000 CNY", "Retrait de points: 1-12", "Prison possible (alcool)"]),
  },
  {
    code: "JP",
    name: "Japon",
    flag: "🇯🇵",
    continent: "Asie",
    capital: "Tokyo",
    languages: JSON.stringify(["Japonais"]),
    currency: JSON.stringify({"code": "JPY", "symbol": "¥", "name": "Yen japonais"}),
    drivingSide: "left",
    authority: "National Police Agency (Keisatsu-chō)",
    emergencyPhone: "110",
    minAge: 18,
    speedUrban: 40,
    speedRural: 60,
    speedHighway: 100,
    bloodAlcohol: 0.3,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Certificat d'immatriculation (自動車検査証)", "Assurance (jidosha hoken)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Gilet réfléchissant", "Cric", "Jacks"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "Tolérance alcool basse (0.3 g/L)", "Shaken (inspection technique obligatoire tous les 2-3 ans)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Alcoolémie (très sévère)", "Excès de vitesse", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 9 000 - 100 000 JPY", "Retrait de points: 1-25", "Prison possible (alcool)"]),
  },
  {
    code: "KR",
    name: "Corée du Sud",
    flag: "🇰🇷",
    continent: "Asie",
    capital: "Séoul",
    languages: JSON.stringify(["Coréen"]),
    currency: JSON.stringify({"code": "KRW", "symbol": "₩", "name": "Won sud-coréen"}),
    drivingSide: "right",
    authority: "National Police Agency (Korea Road Traffic Authority)",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 120,
    bloodAlcohol: 0.3,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Certificat d'immatriculation", "Assurance obligatoire"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Gilet réfléchissant"]),
    specialFeatures: JSON.stringify(["Tolérance alcool basse (0.3 g/L)", "Système de points (demerit)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F"]),
    commonInfractions: JSON.stringify(["Alcoolémie (sévère)", "Excès de vitesse", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 30 000 - 300 000 KRW", "Retrait de points: 1-15"]),
  },
  {
    code: "IN",
    name: "Inde",
    flag: "🇮🇳",
    continent: "Asie",
    capital: "New Delhi",
    languages: JSON.stringify(["Hindi", "Anglais"]),
    currency: JSON.stringify({"code": "INR", "symbol": "₹", "name": "Roupie indienne"}),
    drivingSide: "left",
    authority: "Ministry of Road Transport and Highways",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.3,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Certificat d'enregistrement", "Assurance obligatoire", "Certificat de pollution (PUC)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Premiers secours"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "PUC (pollution control) obligatoire", "Tolérance alcool basse (0.3 g/L)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Alcoolémie (sévère)", "Excès de vitesse", "Non-port du casque (moto)"]),
    sanctions: JSON.stringify(["Amende: 1 000 - 10 000 INR", "Suspension du permis"]),
  },
  {
    code: "AE",
    name: "Émirats Arabes Unis",
    flag: "🇦🇪",
    continent: "Moyen-Orient",
    capital: "Abu Dhabi",
    languages: JSON.stringify(["Arabe", "Anglais"]),
    currency: JSON.stringify({"code": "AED", "symbol": "AED", "name": "Dirham des Émirats"}),
    drivingSide: "right",
    authority: "Ministry of Interior / RTA (Dubai)",
    emergencyPhone: "999",
    minAge: 18,
    speedUrban: 60,
    speedRural: 100,
    speedHighway: 140,
    bloodAlcohol: 0.0,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte de circulation (Mulkiya)", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Zéro tolérance alcool", "Salik (péage autoroutier à Dubaï)", "Radars très nombreux"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Alcoolémie (zéro tolérance, prison)", "Excès de vitesse (radars)", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 500 - 50 000 AED", "Prison possible (alcool)", "Points noirs (23 initial)"]),
  },
  {
    code: "SA",
    name: "Arabie Saoudite",
    flag: "🇸🇦",
    continent: "Moyen-Orient",
    capital: "Riyad",
    languages: JSON.stringify(["Arabe"]),
    currency: JSON.stringify({"code": "SAR", "symbol": "SAR", "name": "Riyal saoudien"}),
    drivingSide: "right",
    authority: "Ministry of Interior",
    emergencyPhone: "911",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 120,
    bloodAlcohol: 0.0,
    requiredDocuments: JSON.stringify(["Permis de conduire (Istimara)", "Carte d'immatriculation (Feha)", "Assurance obligatoire"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Zéro tolérance alcool", "Femmes autorisées à conduire depuis 2018"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Alcoolémie (zéro tolérance, prison)", "Excès de vitesse (Saher cameras)"]),
    sanctions: JSON.stringify(["Amende: 500 - 3 000 SAR", "Prison possible (alcool)"]),
  },
  {
    code: "TR",
    name: "Turquie",
    flag: "🇹🇷",
    continent: "Asie",
    capital: "Ankara",
    languages: JSON.stringify(["Turc"]),
    currency: JSON.stringify({"code": "TRY", "symbol": "₺", "name": "Livre turque"}),
    drivingSide: "right",
    authority: "Ministry of Transport and Infrastructure",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire (Ehliyet)", "Carte grise (Ruhsat)", "Assurance (Zorunlu trafik sigortası)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Système de points (20 initial)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 1 000 - 10 000 TRY", "Retrait de points"]),
  },
  {
    code: "SG",
    name: "Singapour",
    flag: "🇸🇬",
    continent: "Asie",
    capital: "Singapour",
    languages: JSON.stringify(["Anglais", "Mandarin", "Malais", "Tamoul"]),
    currency: JSON.stringify({"code": "SGD", "symbol": "S$", "name": "Dollar de Singapour"}),
    drivingSide: "left",
    authority: "Land Transport Authority (LTA)",
    emergencyPhone: "995",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 90,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Certificat d'immatriculation", "Assurance", "Road tax (ERP)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "COE (Certificate of Entitlement) obligatoire pour acheter un véhicule", "ERP (péage électronique)", "Tolérance alcool: 0.35 promille / 0.08%"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: S$ 200 - 5 000", "Retrait de points", "Disqualification"]),
  },
  {
    code: "TH",
    name: "Thaïlande",
    flag: "🇹🇭",
    continent: "Asie",
    capital: "Bangkok",
    languages: JSON.stringify(["Thaï", "Anglais"]),
    currency: JSON.stringify({"code": "THB", "symbol": "฿", "name": "Baht thaïlandais"}),
    drivingSide: "left",
    authority: "Department of Land Transport",
    emergencyPhone: "191",
    minAge: 18,
    speedUrban: 50,
    speedRural: 90,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance obligatoire (Por Ror Bor)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "Motos omniprésentes", "Permis temporaire pour étrangers"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port du casque (moto)"]),
    sanctions: JSON.stringify(["Amende: 200 - 4 000 THB", "Suspension du permis"]),
  },
  {
    code: "VN",
    name: "Vietnam",
    flag: "🇻🇳",
    continent: "Asie",
    capital: "Hanoï",
    languages: JSON.stringify(["Vietnamien"]),
    currency: JSON.stringify({"code": "VND", "symbol": "₫", "name": "Dong vietnamien"}),
    drivingSide: "right",
    authority: "Directorate for Roads of Vietnam",
    emergencyPhone: "115",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.25,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance obligatoire"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Grand nombre de motos", "Tolérance alcool basse (0.25)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C"]),
    commonInfractions: JSON.stringify(["Alcoolémie", "Excès de vitesse", "Non-port du casque (moto)"]),
    sanctions: JSON.stringify(["Amende: 100 000 - 40 000 000 VND", "Retrait de points"]),
  },
  {
    code: "ID",
    name: "Indonésie",
    flag: "🇮🇩",
    continent: "Océanie",
    capital: "Jakarta",
    languages: JSON.stringify(["Indonésien", "Anglais"]),
    currency: JSON.stringify({"code": "IDR", "symbol": "Rp", "name": "Roupie indonésienne"}),
    drivingSide: "left",
    authority: "National Police Traffic Corps (Korlantas Polri)",
    emergencyPhone: "112",
    minAge: 17,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.0,
    requiredDocuments: JSON.stringify(["SIM (Permis de conduire)", "STNK (Immatriculation)", "SKCK (Assurance)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "Zéro tolérance alcool (nouvelle loi)"]),
    licenseCategories: JSON.stringify(["A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port du casque (moto)"]),
    sanctions: JSON.stringify(["Amende: 250 000 - 1 000 000 IDR"]),
  },
  {
    code: "PH",
    name: "Philippines",
    flag: "🇵🇭",
    continent: "Asie",
    capital: "Manille",
    languages: JSON.stringify(["Filipino", "Anglais"]),
    currency: JSON.stringify({"code": "PHP", "symbol": "₱", "name": "Peso philippin"}),
    drivingSide: "right",
    authority: "Land Transportation Office (LTO)",
    emergencyPhone: "911",
    minAge: 18,
    speedUrban: 60,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire (LTO)", "OR/CR (Immatriculation)", "Assurance (CTPL)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Number coding (restriction par jour à Manille)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port du casque (moto)", "Alcoolémie"]),
    sanctions: JSON.stringify(["Amende: 1 000 - 10 000 PHP", "Retrait de points"]),
  },
  {
    code: "MY",
    name: "Malaisie",
    flag: "🇲🇾",
    continent: "Asie",
    capital: "Kuala Lumpur",
    languages: JSON.stringify(["Malais", "Anglais"]),
    currency: JSON.stringify({"code": "MYR", "symbol": "RM", "name": "Ringgit malaisien"}),
    drivingSide: "left",
    authority: "Road Transport Department (JPJ)",
    emergencyPhone: "999",
    minAge: 17,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 110,
    bloodAlcohol: 0.8,
    requiredDocuments: JSON.stringify(["Permis de conduire (Lesen Memandu)", "Carte grise", "Assurance", "Road tax"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "Touch'n Go (péage électronique)", "Saman (contraventions en ligne)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port de la ceinture", "Non-port du casque (moto)"]),
    sanctions: JSON.stringify(["Amende: 150 - 1 000 MYR", "Retrait de points (KEJARA - 15 points)"]),
  },
  {
    code: "EG",
    name: "Égypte",
    flag: "🇪🇬",
    continent: "Afrique",
    capital: "Le Caire",
    languages: JSON.stringify(["Arabe"]),
    currency: JSON.stringify({"code": "EGP", "symbol": "E£", "name": "Livre égyptienne"}),
    drivingSide: "right",
    authority: "Ministry of Interior - Traffic Department",
    emergencyPhone: "122",
    minAge: 18,
    speedUrban: 60,
    speedRural: 90,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Circulation dense au Caire"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port de la ceinture", "Alcoolémie"]),
    sanctions: JSON.stringify(["Amende: 100 - 3 000 EGP", "Retrait de points"]),
  },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    continent: "Afrique",
    capital: "Abuja",
    languages: JSON.stringify(["Anglais", "Haoussa"]),
    currency: JSON.stringify({"code": "NGN", "symbol": "₦", "name": "Naira nigérian"}),
    drivingSide: "right",
    authority: "Federal Road Safety Corps (FRSC)",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance", "Vehicle licence"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["LASTMA (Lagos traffic enforcement)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port de la ceinture", "Alcoolémie"]),
    sanctions: JSON.stringify(["Amende: 2 000 - 50 000 NGN", "Retrait de points"]),
  },
  {
    code: "RU",
    name: "Russie",
    flag: "🇷🇺",
    continent: "Europe",
    capital: "Moscou",
    languages: JSON.stringify(["Russe"]),
    currency: JSON.stringify({"code": "RUB", "symbol": "₽", "name": "Rouble russe"}),
    drivingSide: "right",
    authority: "Ministry of Internal Affairs (GIBDD)",
    emergencyPhone: "112",
    minAge: 18,
    speedUrban: 60,
    speedRural: 90,
    speedHighway: 110,
    bloodAlcohol: 0.35,
    requiredDocuments: JSON.stringify(["Permis de conduire (VU)", "Certificat d'immatriculation (PTS)", "Assurance (OSAGO)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur", "Trousse de premiers secours", "Gilet réfléchissant"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "OSAGO assurance obligatoire", "Givre: pneus hiver obligatoires (déc.-fév.)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 500 - 30 000 RUB", "Retrait de points", "Suspension du permis"]),
  },
  {
    code: "AU",
    name: "Australie",
    flag: "🇦🇺",
    continent: "Océanie",
    capital: "Canberra",
    languages: JSON.stringify(["Anglais"]),
    currency: JSON.stringify({"code": "AUD", "symbol": "A$", "name": "Dollar australien"}),
    drivingSide: "left",
    authority: "State/Territory transport authority",
    emergencyPhone: "000",
    minAge: 17,
    speedUrban: 50,
    speedRural: 100,
    speedHighway: 110,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance (CTP/Green Slip obligatoire)", "Contrôle technique (régières variable)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "Règles variables par État/territoire", "Graduated licensing system (L/P1/P2/full)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: variable par État", "Points de démérite", "Suspension du permis"]),
  },
  {
    code: "NZ",
    name: "Nouvelle-Zélande",
    flag: "🇳🇿",
    continent: "Océanie",
    capital: "Wellington",
    languages: JSON.stringify(["Anglais", "Maori"]),
    currency: JSON.stringify({"code": "NZD", "symbol": "NZ$", "name": "Dollar néo-zélandais"}),
    drivingSide: "left",
    authority: "NZ Transport Agency (Waka Kotahi)",
    emergencyPhone: "111",
    minAge: 16,
    speedUrban: 50,
    speedRural: 100,
    speedHighway: 110,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise (MR6A)", "Assurance (ACC obligatoire, tiers conseillé)"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Gilet réfléchissant", "Trousse de premiers secours"]),
    specialFeatures: JSON.stringify(["Conduite à gauche", "Graduated licensing (L/R/F)", "Give way rules (2022 reform)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE", "F", "G"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Téléphone au volant"]),
    sanctions: JSON.stringify(["Amende: 100 - 2 000 NZD", "Retrait de points (20 initial)"]),
  },
  {
    code: "HT",
    name: "Haïti",
    flag: "🇭🇹",
    continent: "Caraïbes",
    capital: "Port-au-Prince",
    languages: JSON.stringify(["Créole haïtien", "Français"]),
    currency: JSON.stringify({"code": "HTG", "symbol": "G", "name": "Gourde haïtienne"}),
    drivingSide: "right",
    authority: "Ministère des Travaux Publics",
    emergencyPhone: "114",
    minAge: 18,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 100,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation"]),
    specialFeatures: JSON.stringify(["Priorité à droite"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Non-port du casque", "Alcoolémie"]),
    sanctions: JSON.stringify(["Amende: 500 - 5 000 HTG"]),
  },
  {
    code: "DO",
    name: "République Dominicaine",
    flag: "🇩🇴",
    continent: "Caraïbes",
    capital: "Saint-Domingue",
    languages: JSON.stringify(["Espagnol"]),
    currency: JSON.stringify({"code": "DOP", "symbol": "RD$", "name": "Peso dominicain"}),
    drivingSide: "right",
    authority: "Ministerio de Obras Públicas y Comunicaciones",
    emergencyPhone: "911",
    minAge: 18,
    speedUrban: 60,
    speedRural: 80,
    speedHighway: 120,
    bloodAlcohol: 0.5,
    requiredDocuments: JSON.stringify(["Permis de conducir", "Tarjeta de circulación", "Seguro obligatorio"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Priorité à droite", "Seguro obligatoire (ARS)"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 500 - 5 000 DOP"]),
  },
  {
    code: "JM",
    name: "Jamaïque",
    flag: "🇯🇲",
    continent: "Caraïbes",
    capital: "Kingston",
    languages: JSON.stringify(["Anglais", "Créole jamaïcain"]),
    currency: JSON.stringify({"code": "JMD", "symbol": "J$", "name": "Dollar jamaïcain"}),
    drivingSide: "left",
    authority: "Road Safety Unit (Ministry of Transport)",
    emergencyPhone: "119",
    minAge: 17,
    speedUrban: 50,
    speedRural: 80,
    speedHighway: 110,
    bloodAlcohol: 0.35,
    requiredDocuments: JSON.stringify(["Permis de conduire", "Carte grise", "Assurance obligatoire"]),
    requiredEquipment: JSON.stringify(["Triangle de signalisation", "Extincteur"]),
    specialFeatures: JSON.stringify(["Conduite à gauche"]),
    licenseCategories: JSON.stringify(["AM", "A1", "A2", "A", "B", "BE", "C1", "C", "CE", "D1", "D", "DE"]),
    commonInfractions: JSON.stringify(["Excès de vitesse", "Alcoolémie", "Non-port de la ceinture"]),
    sanctions: JSON.stringify(["Amende: 3 000 - 30 000 JMD"]),
  }
];
